apiVersion: apps/v1
kind: Deployment
metadata:
  name: klio-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: klio-server
  template:
    metadata:
      labels:
        app: klio-server
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
              
      initContainers:
      - name: klio-initialize
        command:
        - klio
        - server
        - initialize
        - --config=/config/klio.yaml

        image: klio
        imagePullPolicy: Always

        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config

      containers:
      - name: klio-wal-server
        command:
        - klio
        - --config=/config/klio.yaml
        - server
        - start-wal

        image: klio:latest
        imagePullPolicy: Always

        resources:
          requests:
            memory: '512Mi'
            cpu: 750m
          limits:
            memory: '512Mi'
            cpu: 750m
                    
        ports:
        - containerPort: 52000
          protocol: TCP
          name: klio
        - containerPort: 51515
          protocol: TCP
          name: kopia

        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
        - name: tls
          mountPath: /certs
      - name: klio-pgdata-server
        command:
        - klio
        - --config=/config/klio.yaml
        - server
        - start-pgdata

        image: klio
        imagePullPolicy: Always

        resources:
          requests:
            memory: '1024Mi'
            cpu: 750m
          limits:
            memory: '1024Mi'
            cpu: 750m

        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
        - name: tls
          mountPath: /certs

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: klio-volume
      - name: config
        secret:
          secretName: config
      - name: tls
        secret:
          secretName: klio-server-tls
