apiVersion: v1
kind: Service
metadata:
  name: klio-server
spec:
  ports:
  - name: port-klio
    port: 52000
    protocol: TCP
    targetPort: 52000
  - name: port-kopia
    port: 51515
    protocol: TCP
    targetPort: 51515
  selector:
    app: klio-server
status:
  loadBalancer: {}
