resources:
  - deployment.yaml
  - service-account.yaml
  - role-binding.yaml
  - role.yaml
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - apiservice.yaml
  - service.yaml
  - snapshot-reader-certificate.yaml
