name: Setup dagger
description: Sets up dagger and task
runs:
  using: composite
  steps:
    - name: Install Task
      uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa # v2
      env:
        # renovate: datasource=github-tags depName=go-task/task versioning=semver
        TASK_VERSION: 3.51.1
      with:
        version: ${{ env.TASK_VERSION }}

    - name: Install Dagger
      shell: bash
      env:
        # renovate: datasource=github-tags depName=dagger/dagger versioning=semver
        DAGGER_VERSION: 0.21.7
      run: |
        curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
