apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rustfs-server
spec:
  secretName: rustfs-tls
  commonName: rustfs
  dnsNames:
    - rustfs
    - rustfs.default
    - rustfs.default.svc

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
