apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  labels:
    app.kubernetes.io/instance: rustfs
    app.kubernetes.io/name: rustfs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: rustfs
      app.kubernetes.io/name: rustfs
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: rustfs
        app.kubernetes.io/name: rustfs
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsUser: 10001
      initContainers:
      - name: init-step
        image: busybox:1.37.0-musl
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          mkdir -p /data /logs
          chown 10001:10001 /data /logs
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /logs
          name: logs
      containers:
      - name: rustfs
        image: rustfs/rustfs:1.0.0-alpha.83
        imagePullPolicy: IfNotPresent
        command:
        - /usr/bin/rustfs
        ports:
        - containerPort: 9000
          name: endpoint
          protocol: TCP
        - containerPort: 9001
          name: console
          protocol: TCP
        envFrom:
        - configMapRef:
            name: rustfs-config
        - secretRef:
            name: rustfs-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 2Gi
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /logs
          name: logs
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
        - mountPath: /certs/rustfs_cert.pem
          name: certs
          subPath: rustfs_cert.pem
        - mountPath: /certs/rustfs_key.pem
          name: certs
          subPath: rustfs_key.pem
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 1Gi
      - name: logs
        persistentVolumeClaim:
          claimName: rustfs-logs
      - name: data
        persistentVolumeClaim:
          claimName: rustfs-data
      - name: certs
        secret:
          secretName: rustfs-tls
          items:
          - key: tls.crt
            path: rustfs_cert.pem
          - key: tls.key
            path: rustfs_key.pem
