# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=boringcrypto
    flags:
      - -tags=viper_bind_struct
    goos:
      - linux
    goarch:
      - amd64
      - arm64

nfpms:
  - id: klio
    package_name: klio
    file_name_template: "{{ .ConventionalFileName }}"
    maintainer: Cloud Native Team <info@enterprisedb.com>

    contents:
      - src: systemd/klio.service
        dst: /usr/share/klio/klio.service

      - src: systemd/klio-send-wal.service
        dst: /usr/share/klio/klio-send-wal.service

      - src: systemd/kopia.service
        dst: /usr/share/klio/kopia.service

    formats:
      - deb
      - rpm

    provides:
      - klio

    recommends:
      - kopia

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  disable: true

release:
  mode: keep-existing
  github:
    owner: EnterpriseDB
    name: klio
