apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-cluster-example
spec:
  serverAddress: klio.default
  clientIdentity:
    volume:
      secret:
        secretName: cluster-example-klio-user
    certPath: tls.crt
    keyPath: tls.key
  serverCa:
    fileReference:
      volume:
        secret:
          secretName: klio-server-ca
          items:
          - key: ca.crt
            path: ca.crt
      path: ca.crt
  clusterName: cluster-example
  containers:
    - name: klio-plugin
      env:
        - name: OTEL_SERVICE_NAME
          value: "klio-plugin"
      envFrom:
        - configMapRef:
            name: cluster-klio-otel-config
