apiVersion: klio.cnpg.io/v1alpha1
kind: Server
metadata:
  name: klio
spec:
  cacheConfiguration:
    pvcTemplate:
      resources:
        requests:
          storage: 1Gi
      accessModes:
      - ReadWriteOnce

  dataConfiguration:
    pvcTemplate:
      resources:
        requests:
          storage: 1Gi
      accessModes:
      - ReadWriteOnce

  password:
    name: klio-encryption
    key: password

  caSecretName: klio-server-ca
  tlsSecretName: klio-server-tls

  image: registry.dev:5000/klio-testing:dev
  imagePullPolicy: Always

  template:
    spec:
      containers:
        - name: base
          env:
            # Use the downward API to get pod and node information
            # These environment variables will be used in the OTEL_RESOURCE_ATTRIBUTES
            # to provide more context about the telemetry data for the otel collector k8sattributes processor
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            # OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES are set specifically for each container
            - name: OTEL_SERVICE_NAME
              value: "klio-base"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.node.name=$(NODE_NAME),k8s.pod.uid=$(POD_UID)"
          envFrom:
            # Use a common config map for all shared OTEL settings
            - configMapRef:
                name: klio-server-otel-config
          volumeMounts:
            - mountPath: /otel
              name: otel
        - name: wal
          env:
            # Use the downward API to get pod and node information
            # These environment variables will be used in the OTEL_RESOURCE_ATTRIBUTES
            # to provide more context about the telemetry data for the otel collector k8sattributes processor
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            # OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES are set specifically for each container
            - name: OTEL_SERVICE_NAME
              value: "klio-wal"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.node.name=$(NODE_NAME),k8s.pod.uid=$(POD_UID)"
          envFrom:
            # Use a common config map for all shared OTEL settings
            - configMapRef:
                name: klio-server-otel-config
          volumeMounts:
            - mountPath: /otel
              name: otel
      volumes:
        - name: otel
          projected:
            sources:
              - secret:
                  name: otel-collector-tls
                  items:
                    - key: ca.crt
                      path: ca.crt
              - secret:
                  name: klio-server-otel-client-tls
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
