apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: klio-server-ca
spec:
  commonName: klio-server
  secretName: klio-server-ca

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: true
  usages:
    - cert sign

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
