# REQUIRES:
# kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
resources:
  - cluster_klio_otel_config.yaml
  - cluster.yaml
  - cluster_klio_client_auth.yaml
  - issuer.yaml
  - jaeger.yaml
  - klio_admin.yaml
  - klio_encryption.yaml
  - klio_server.yaml
  - klio_server_ca.yaml
  - klio_server_ca_issuer.yaml
  - klio_server_certificate.yaml
  - klio_server_otel_client_certificate.yaml
  - klio_server_otel_config.yaml
  - otel_collector.yaml
  - otel_collector_certificate.yaml
  - otel_collector_clusterrole.yaml
  - otel_collector_clusterrolebinding.yaml
  - otel_collector_sa.yaml
  - otel_collector_svc_monitor.yaml
  - plugin_configuration.yaml
