# OpenTelemetry Collector instance
# A full-fledged configuration is outside of the scope of this example.
# This example receives OTLP data over gRPC with TLS, adds Kubernetes attributes,
# and exports to a Jaeger instance (without TLS, for simplicity) and to Prometheus.
# It also exports to a debug exporter, which prints the data to the collector's logs.
# OpenTelemetry Operator is required to run this:
#   kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  image: "otel/opentelemetry-collector-contrib:0.149.0@sha256:0fba96233274f6d665ac8831ad99dfe6479a9a20459f6e2719c0d20945773b46"
  config:
    receivers:
      # otlp receiver to receive data in OTLP format over gRPC. TLS is enabled.
      # Must match the settings in the clients.
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            tls:
              cert_file: /etc/otel/certs/tls.crt
              key_file: /etc/otel/certs/tls.key
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      k8sattributes:
        auth_type: 'serviceAccount'
        extract:
          metadata: # extracted from the pod
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.name
            - k8s.pod.start_time
            - k8s.pod.uid
            - container.image.name
            - container.image.tag
            - k8s.container.name
        pod_association: # How to associate the data to a pod (order matters)
          - sources: # First try to use the value of the resource attribute k8s.pod.ip
              - from: resource_attribute
                name: k8s.pod.ip
          - sources: # Then try to use the value of the resource attribute k8s.pod.uid
              - from: resource_attribute
                name: k8s.pod.uid
          - sources: # If neither of those work, use the request's connection to get the pod IP.
              - from: connection
    exporters:
      debug:
        verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:9464"
        send_timestamps: true
        resource_to_telemetry_conversion:
          enabled: true
      otlp:
        endpoint: jaeger:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch, k8sattributes ]
          exporters: [ debug, otlp ]
        metrics:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch, k8sattributes ]
          exporters: [ debug, prometheus ]
  volumeMounts:
    - name: otel-tls
      mountPath: /etc/otel/certs
      readOnly: true
  volumes:
    - name: otel-tls
      secret:
        secretName: otel-collector-tls
