apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-cluster-example
spec:
  serverAddress: klio.default
  clientSecretName: cluster-example-klio-user
  serverSecretName: klio-server-tls
  clusterName: cluster-example
  containers:
    - name: klio-plugin
      envFrom:
        # Use a common config map for all shared OTEL settings
        - configMapRef:
            name: cluster-klio-otel-config
    - name: klio-restore
      envFrom:
        # Use a common config map for all shared OTEL settings
        - configMapRef:
            name: cluster-klio-otel-config
