/*
Copyright © contributors to CloudNativePG, established as
CloudNativePG a Series of LF Projects, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package controller

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"

	kliov1alpha1 "github.com/cloudnative-pg/klio/operator/api/v1alpha1"
)

const (
	// queueVolumeName is the name of the dedicated queue volume, and of its
	// VolumeClaimTemplate.
	queueVolumeName = "queue"

	// queueVolumeMountPath is where the dedicated queue volume is mounted.
	queueVolumeMountPath = "/queue"

	// queueDataPath is the queue location used when no dedicated queue volume
	// is configured: a directory inside the tier1 data volume.
	queueDataPath = kopiaDataMountPath + "/" + queueVolumeName
)

// queueLayout describes where the work queue lives for a given Server, and
// where the server must migrate it from when the location just changed.
type queueLayout struct {
	// directory is the queue location the server has to use.
	directory string

	// migrationSource is the other queue location, whose content must be
	// moved into directory before the queue is opened. Empty when that
	// location is not mounted, hence has nothing to migrate.
	migrationSource string

	// mountDedicatedVolume is true when the dedicated queue volume has to be
	// mounted, either because it is the configured location or because it
	// still holds the queue to migrate away.
	mountDedicatedVolume bool

	// claimName is set when the dedicated queue volume is no longer part of
	// the spec and must be mounted by claim name, as the StatefulSet no longer
	// declares a VolumeClaimTemplate for it.
	claimName string
}

// buildQueueLayout computes the queue layout of a Server. queuePVCPresent
// tells whether the PVC of a previously configured dedicated queue volume is
// still around.
func buildQueueLayout(server *kliov1alpha1.Server, statefulSetName string, queuePVCPresent bool) queueLayout {
	if server.Spec.Tier1 == nil {
		return queueLayout{}
	}

	if server.Spec.Queue != nil {
		return queueLayout{
			directory:            queueVolumeMountPath,
			migrationSource:      queueDataPath,
			mountDedicatedVolume: true,
		}
	}

	layout := queueLayout{directory: queueDataPath}
	if queuePVCPresent {
		layout.migrationSource = queueVolumeMountPath
		layout.mountDedicatedVolume = true
		layout.claimName = queuePVCName(statefulSetName)
	}

	return layout
}

// queuePVCName is the name of the PVC generated by the queue
// VolumeClaimTemplate of the server StatefulSet.
func queuePVCName(statefulSetName string) string {
	return fmt.Sprintf("%s-%s-0", queueVolumeName, statefulSetName)
}

// isQueuePVCPresent tells whether the PVC of the dedicated queue volume exists
// and is usable. A PVC being deleted counts as absent: that is how an operator
// tells us the volume is gone for good, and keeping it mounted would block its
// deletion forever.
func (r *ServerReconciler) isQueuePVCPresent(
	ctx context.Context, namespace, statefulSetName string,
) (bool, error) {
	var pvc corev1.PersistentVolumeClaim
	err := r.Get(ctx, client.ObjectKey{Namespace: namespace, Name: queuePVCName(statefulSetName)}, &pvc)
	if apierrors.IsNotFound(err) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("failed to get the queue PVC: %w", err)
	}

	return pvc.DeletionTimestamp.IsZero(), nil
}
