apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-a
spec:
  instances: 3
  imagePullPolicy: Always

  projectedVolumeTemplate:
    sources:
      - secret:
          name: otel-collector-tls
          items:
            - key: ca.crt
              path: ca.crt
      - secret:
          name: klio-server-otel-client-tls
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key

  postgresql:
    pg_hba:
      - local replication all peer map=local

  plugins:
    - name: klio.cnpg.io
      enabled: true
      parameters:
        pluginConfigurationRef: client-config-cluster-a

  storage:
    size: 1Gi
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-cluster-a
spec:
  serverAddress: klio-a.default
  clientSecretName: cluster-a-klio-user
  serverSecretName: klio-a-tls
  clusterName: cluster-a
  containers:
    - name: klio-plugin
      env:
        - name: OTEL_SERVICE_NAME
          value: "klio-plugin"
      envFrom:
        - configMapRef:
            name: cluster-klio-otel-config
    - name: klio-restore
      env:
        - name: OTEL_SERVICE_NAME
          value: "klio-restore"
      envFrom:
        - configMapRef:
            name: cluster-klio-otel-config
