// @exclude
//
// Copyright © contributors to CloudNativePG, established as
// CloudNativePG a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/klio_admin.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tier represents a storage tier in the backup system.
type Tier int32

const (
	// TIER_UNSPECIFIED is the default value and should not be used.
	Tier_TIER_UNSPECIFIED Tier = 0
	// TIER_1 represents the local cache storage.
	Tier_TIER_1 Tier = 1
	// TIER_2 represents the object storage.
	Tier_TIER_2 Tier = 2
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_1",
		2: "TIER_2",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"TIER_1":           1,
		"TIER_2":           2,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_klio_admin_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_proto_klio_admin_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{0}
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{0}
}

type RefreshResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResult) Reset() {
	*x = RefreshResult{}
	mi := &file_proto_klio_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResult) ProtoMessage() {}

func (x *RefreshResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResult.ProtoReflect.Descriptor instead.
func (*RefreshResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{1}
}

type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{2}
}

type ListBackupsResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-serialized array of backup manifests.
	// Each manifest contains fields like:
	//   - id: string
	//   - cluster_name: string
	//   - timestamp: RFC3339 string
	//   - size_bytes: number
	//
	// See klioclient.BackupManifest for the canonical structure.
	// We use JSON bytes here to avoid duplicating the internal type definition
	// and conversion logic, as this is a local admin API.
	BackupManifests []byte `protobuf:"bytes,1,opt,name=backup_manifests,json=backupManifests,proto3" json:"backup_manifests,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListBackupsResult) Reset() {
	*x = ListBackupsResult{}
	mi := &file_proto_klio_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResult) ProtoMessage() {}

func (x *ListBackupsResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResult.ProtoReflect.Descriptor instead.
func (*ListBackupsResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListBackupsResult) GetBackupManifests() []byte {
	if x != nil {
		return x.BackupManifests
	}
	return nil
}

type QueueListFailedBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   *string                `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3,oneof" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueListFailedBackupsRequest) Reset() {
	*x = QueueListFailedBackupsRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueListFailedBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueListFailedBackupsRequest) ProtoMessage() {}

func (x *QueueListFailedBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueListFailedBackupsRequest.ProtoReflect.Descriptor instead.
func (*QueueListFailedBackupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{4}
}

func (x *QueueListFailedBackupsRequest) GetClusterName() string {
	if x != nil && x.ClusterName != nil {
		return *x.ClusterName
	}
	return ""
}

type QueueListFailedBackupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backups       []*FailedBackup        `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueListFailedBackupsResponse) Reset() {
	*x = QueueListFailedBackupsResponse{}
	mi := &file_proto_klio_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueListFailedBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueListFailedBackupsResponse) ProtoMessage() {}

func (x *QueueListFailedBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueListFailedBackupsResponse.ProtoReflect.Descriptor instead.
func (*QueueListFailedBackupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{5}
}

func (x *QueueListFailedBackupsResponse) GetBackups() []*FailedBackup {
	if x != nil {
		return x.Backups
	}
	return nil
}

type QueueListFailedWALsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   *string                `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3,oneof" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueListFailedWALsRequest) Reset() {
	*x = QueueListFailedWALsRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueListFailedWALsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueListFailedWALsRequest) ProtoMessage() {}

func (x *QueueListFailedWALsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueListFailedWALsRequest.ProtoReflect.Descriptor instead.
func (*QueueListFailedWALsRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{6}
}

func (x *QueueListFailedWALsRequest) GetClusterName() string {
	if x != nil && x.ClusterName != nil {
		return *x.ClusterName
	}
	return ""
}

type QueueListFailedWALsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wals          []*FailedWAL           `protobuf:"bytes,1,rep,name=wals,proto3" json:"wals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueListFailedWALsResponse) Reset() {
	*x = QueueListFailedWALsResponse{}
	mi := &file_proto_klio_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueListFailedWALsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueListFailedWALsResponse) ProtoMessage() {}

func (x *QueueListFailedWALsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueListFailedWALsResponse.ProtoReflect.Descriptor instead.
func (*QueueListFailedWALsResponse) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{7}
}

func (x *QueueListFailedWALsResponse) GetWals() []*FailedWAL {
	if x != nil {
		return x.Wals
	}
	return nil
}

type FailedBackup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClusterName     string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	LastAttemptTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_attempt_time,json=lastAttemptTime,proto3" json:"last_attempt_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FailedBackup) Reset() {
	*x = FailedBackup{}
	mi := &file_proto_klio_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedBackup) ProtoMessage() {}

func (x *FailedBackup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedBackup.ProtoReflect.Descriptor instead.
func (*FailedBackup) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{8}
}

func (x *FailedBackup) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *FailedBackup) GetLastAttemptTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttemptTime
	}
	return nil
}

type FailedWAL struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClusterName     string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	WalName         string                 `protobuf:"bytes,2,opt,name=wal_name,json=walName,proto3" json:"wal_name,omitempty"`
	Sequence        uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	LastAttemptTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_attempt_time,json=lastAttemptTime,proto3" json:"last_attempt_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FailedWAL) Reset() {
	*x = FailedWAL{}
	mi := &file_proto_klio_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedWAL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedWAL) ProtoMessage() {}

func (x *FailedWAL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedWAL.ProtoReflect.Descriptor instead.
func (*FailedWAL) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{9}
}

func (x *FailedWAL) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *FailedWAL) GetWalName() string {
	if x != nil {
		return x.WalName
	}
	return ""
}

func (x *FailedWAL) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *FailedWAL) GetLastAttemptTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttemptTime
	}
	return nil
}

type QueueRetryWALsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   *string                `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3,oneof" json:"cluster_name,omitempty"`
	WalNames      []string               `protobuf:"bytes,2,rep,name=wal_names,json=walNames,proto3" json:"wal_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRetryWALsRequest) Reset() {
	*x = QueueRetryWALsRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRetryWALsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRetryWALsRequest) ProtoMessage() {}

func (x *QueueRetryWALsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRetryWALsRequest.ProtoReflect.Descriptor instead.
func (*QueueRetryWALsRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{10}
}

func (x *QueueRetryWALsRequest) GetClusterName() string {
	if x != nil && x.ClusterName != nil {
		return *x.ClusterName
	}
	return ""
}

func (x *QueueRetryWALsRequest) GetWalNames() []string {
	if x != nil {
		return x.WalNames
	}
	return nil
}

type QueueRetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRetryResponse) Reset() {
	*x = QueueRetryResponse{}
	mi := &file_proto_klio_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRetryResponse) ProtoMessage() {}

func (x *QueueRetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRetryResponse.ProtoReflect.Descriptor instead.
func (*QueueRetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{11}
}

type QueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusRequest) Reset() {
	*x = QueueStatusRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusRequest) ProtoMessage() {}

func (x *QueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusRequest.ProtoReflect.Descriptor instead.
func (*QueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{12}
}

type QueueStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of backup synchronization tasks pending in the queue
	PendingBackups uint64 `protobuf:"varint,1,opt,name=pending_backups,json=pendingBackups,proto3" json:"pending_backups,omitempty"`
	// Number of WAL relay tasks pending in the queue
	PendingWals   uint64 `protobuf:"varint,2,opt,name=pending_wals,json=pendingWals,proto3" json:"pending_wals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusResponse) Reset() {
	*x = QueueStatusResponse{}
	mi := &file_proto_klio_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusResponse) ProtoMessage() {}

func (x *QueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusResponse.ProtoReflect.Descriptor instead.
func (*QueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{13}
}

func (x *QueueStatusResponse) GetPendingBackups() uint64 {
	if x != nil {
		return x.PendingBackups
	}
	return 0
}

func (x *QueueStatusResponse) GetPendingWals() uint64 {
	if x != nil {
		return x.PendingWals
	}
	return 0
}

// DeleteBackupRequest is the request to delete a backup from the server.
type DeleteBackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the backup to delete.
	BackupName string `protobuf:"bytes,1,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	// The storage tiers from which to delete the backup.
	// At least one tier must be specified.
	Tiers []Tier `protobuf:"varint,2,rep,packed,name=tiers,proto3,enum=klio.wal.v1.Tier" json:"tiers,omitempty"`
	// The name of the cluster that owns the backup.
	ClusterName   string `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteBackupRequest) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

func (x *DeleteBackupRequest) GetTiers() []Tier {
	if x != nil {
		return x.Tiers
	}
	return nil
}

func (x *DeleteBackupRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

// DeleteBackupResponse is the response to a backup deletion request.
type DeleteBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupResponse) Reset() {
	*x = DeleteBackupResponse{}
	mi := &file_proto_klio_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupResponse) ProtoMessage() {}

func (x *DeleteBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{15}
}

var File_proto_klio_admin_proto protoreflect.FileDescriptor

const file_proto_klio_admin_proto_rawDesc = "" +
	"\n" +
	"\x16proto/klio_admin.proto\x12\vklio.wal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x10\n" +
	"\x0eRefreshRequest\"\x0f\n" +
	"\rRefreshResult\"\x14\n" +
	"\x12ListBackupsRequest\">\n" +
	"\x11ListBackupsResult\x12)\n" +
	"\x10backup_manifests\x18\x01 \x01(\fR\x0fbackupManifests\"X\n" +
	"\x1dQueueListFailedBackupsRequest\x12&\n" +
	"\fcluster_name\x18\x01 \x01(\tH\x00R\vclusterName\x88\x01\x01B\x0f\n" +
	"\r_cluster_name\"U\n" +
	"\x1eQueueListFailedBackupsResponse\x123\n" +
	"\abackups\x18\x01 \x03(\v2\x19.klio.wal.v1.FailedBackupR\abackups\"U\n" +
	"\x1aQueueListFailedWALsRequest\x12&\n" +
	"\fcluster_name\x18\x01 \x01(\tH\x00R\vclusterName\x88\x01\x01B\x0f\n" +
	"\r_cluster_name\"I\n" +
	"\x1bQueueListFailedWALsResponse\x12*\n" +
	"\x04wals\x18\x01 \x03(\v2\x16.klio.wal.v1.FailedWALR\x04wals\"y\n" +
	"\fFailedBackup\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12F\n" +
	"\x11last_attempt_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastAttemptTime\"\xad\x01\n" +
	"\tFailedWAL\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x19\n" +
	"\bwal_name\x18\x02 \x01(\tR\awalName\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12F\n" +
	"\x11last_attempt_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastAttemptTime\"m\n" +
	"\x15QueueRetryWALsRequest\x12&\n" +
	"\fcluster_name\x18\x01 \x01(\tH\x00R\vclusterName\x88\x01\x01\x12\x1b\n" +
	"\twal_names\x18\x02 \x03(\tR\bwalNamesB\x0f\n" +
	"\r_cluster_name\"\x14\n" +
	"\x12QueueRetryResponse\"\x14\n" +
	"\x12QueueStatusRequest\"a\n" +
	"\x13QueueStatusResponse\x12'\n" +
	"\x0fpending_backups\x18\x01 \x01(\x04R\x0ependingBackups\x12!\n" +
	"\fpending_wals\x18\x02 \x01(\x04R\vpendingWals\"\x82\x01\n" +
	"\x13DeleteBackupRequest\x12\x1f\n" +
	"\vbackup_name\x18\x01 \x01(\tR\n" +
	"backupName\x12'\n" +
	"\x05tiers\x18\x02 \x03(\x0e2\x11.klio.wal.v1.TierR\x05tiers\x12!\n" +
	"\fcluster_name\x18\x03 \x01(\tR\vclusterName\"\x16\n" +
	"\x14DeleteBackupResponse*4\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06TIER_1\x10\x01\x12\n" +
	"\n" +
	"\x06TIER_2\x10\x022\x84\x05\n" +
	"\x05Admin\x12D\n" +
	"\aRefresh\x12\x1b.klio.wal.v1.RefreshRequest\x1a\x1a.klio.wal.v1.RefreshResult\"\x00\x12P\n" +
	"\vListBackups\x12\x1f.klio.wal.v1.ListBackupsRequest\x1a\x1e.klio.wal.v1.ListBackupsResult\"\x00\x12s\n" +
	"\x16QueueListFailedBackups\x12*.klio.wal.v1.QueueListFailedBackupsRequest\x1a+.klio.wal.v1.QueueListFailedBackupsResponse\"\x00\x12j\n" +
	"\x13QueueListFailedWALs\x12'.klio.wal.v1.QueueListFailedWALsRequest\x1a(.klio.wal.v1.QueueListFailedWALsResponse\"\x00\x12W\n" +
	"\x0eQueueRetryWALs\x12\".klio.wal.v1.QueueRetryWALsRequest\x1a\x1f.klio.wal.v1.QueueRetryResponse\"\x00\x12R\n" +
	"\vQueueStatus\x12\x1f.klio.wal.v1.QueueStatusRequest\x1a .klio.wal.v1.QueueStatusResponse\"\x00\x12U\n" +
	"\fDeleteBackup\x12 .klio.wal.v1.DeleteBackupRequest\x1a!.klio.wal.v1.DeleteBackupResponse\"\x00B3Z1github.com/cloudnative-pg/klio/core/internal/grpcb\x06proto3"

var (
	file_proto_klio_admin_proto_rawDescOnce sync.Once
	file_proto_klio_admin_proto_rawDescData []byte
)

func file_proto_klio_admin_proto_rawDescGZIP() []byte {
	file_proto_klio_admin_proto_rawDescOnce.Do(func() {
		file_proto_klio_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_klio_admin_proto_rawDesc), len(file_proto_klio_admin_proto_rawDesc)))
	})
	return file_proto_klio_admin_proto_rawDescData
}

var file_proto_klio_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_klio_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_klio_admin_proto_goTypes = []any{
	(Tier)(0),                              // 0: klio.wal.v1.Tier
	(*RefreshRequest)(nil),                 // 1: klio.wal.v1.RefreshRequest
	(*RefreshResult)(nil),                  // 2: klio.wal.v1.RefreshResult
	(*ListBackupsRequest)(nil),             // 3: klio.wal.v1.ListBackupsRequest
	(*ListBackupsResult)(nil),              // 4: klio.wal.v1.ListBackupsResult
	(*QueueListFailedBackupsRequest)(nil),  // 5: klio.wal.v1.QueueListFailedBackupsRequest
	(*QueueListFailedBackupsResponse)(nil), // 6: klio.wal.v1.QueueListFailedBackupsResponse
	(*QueueListFailedWALsRequest)(nil),     // 7: klio.wal.v1.QueueListFailedWALsRequest
	(*QueueListFailedWALsResponse)(nil),    // 8: klio.wal.v1.QueueListFailedWALsResponse
	(*FailedBackup)(nil),                   // 9: klio.wal.v1.FailedBackup
	(*FailedWAL)(nil),                      // 10: klio.wal.v1.FailedWAL
	(*QueueRetryWALsRequest)(nil),          // 11: klio.wal.v1.QueueRetryWALsRequest
	(*QueueRetryResponse)(nil),             // 12: klio.wal.v1.QueueRetryResponse
	(*QueueStatusRequest)(nil),             // 13: klio.wal.v1.QueueStatusRequest
	(*QueueStatusResponse)(nil),            // 14: klio.wal.v1.QueueStatusResponse
	(*DeleteBackupRequest)(nil),            // 15: klio.wal.v1.DeleteBackupRequest
	(*DeleteBackupResponse)(nil),           // 16: klio.wal.v1.DeleteBackupResponse
	(*timestamppb.Timestamp)(nil),          // 17: google.protobuf.Timestamp
}
var file_proto_klio_admin_proto_depIdxs = []int32{
	9,  // 0: klio.wal.v1.QueueListFailedBackupsResponse.backups:type_name -> klio.wal.v1.FailedBackup
	10, // 1: klio.wal.v1.QueueListFailedWALsResponse.wals:type_name -> klio.wal.v1.FailedWAL
	17, // 2: klio.wal.v1.FailedBackup.last_attempt_time:type_name -> google.protobuf.Timestamp
	17, // 3: klio.wal.v1.FailedWAL.last_attempt_time:type_name -> google.protobuf.Timestamp
	0,  // 4: klio.wal.v1.DeleteBackupRequest.tiers:type_name -> klio.wal.v1.Tier
	1,  // 5: klio.wal.v1.Admin.Refresh:input_type -> klio.wal.v1.RefreshRequest
	3,  // 6: klio.wal.v1.Admin.ListBackups:input_type -> klio.wal.v1.ListBackupsRequest
	5,  // 7: klio.wal.v1.Admin.QueueListFailedBackups:input_type -> klio.wal.v1.QueueListFailedBackupsRequest
	7,  // 8: klio.wal.v1.Admin.QueueListFailedWALs:input_type -> klio.wal.v1.QueueListFailedWALsRequest
	11, // 9: klio.wal.v1.Admin.QueueRetryWALs:input_type -> klio.wal.v1.QueueRetryWALsRequest
	13, // 10: klio.wal.v1.Admin.QueueStatus:input_type -> klio.wal.v1.QueueStatusRequest
	15, // 11: klio.wal.v1.Admin.DeleteBackup:input_type -> klio.wal.v1.DeleteBackupRequest
	2,  // 12: klio.wal.v1.Admin.Refresh:output_type -> klio.wal.v1.RefreshResult
	4,  // 13: klio.wal.v1.Admin.ListBackups:output_type -> klio.wal.v1.ListBackupsResult
	6,  // 14: klio.wal.v1.Admin.QueueListFailedBackups:output_type -> klio.wal.v1.QueueListFailedBackupsResponse
	8,  // 15: klio.wal.v1.Admin.QueueListFailedWALs:output_type -> klio.wal.v1.QueueListFailedWALsResponse
	12, // 16: klio.wal.v1.Admin.QueueRetryWALs:output_type -> klio.wal.v1.QueueRetryResponse
	14, // 17: klio.wal.v1.Admin.QueueStatus:output_type -> klio.wal.v1.QueueStatusResponse
	16, // 18: klio.wal.v1.Admin.DeleteBackup:output_type -> klio.wal.v1.DeleteBackupResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_klio_admin_proto_init() }
func file_proto_klio_admin_proto_init() {
	if File_proto_klio_admin_proto != nil {
		return
	}
	file_proto_klio_admin_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_klio_admin_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_klio_admin_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_klio_admin_proto_rawDesc), len(file_proto_klio_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_klio_admin_proto_goTypes,
		DependencyIndexes: file_proto_klio_admin_proto_depIdxs,
		EnumInfos:         file_proto_klio_admin_proto_enumTypes,
		MessageInfos:      file_proto_klio_admin_proto_msgTypes,
	}.Build()
	File_proto_klio_admin_proto = out.File
	file_proto_klio_admin_proto_goTypes = nil
	file_proto_klio_admin_proto_depIdxs = nil
}
