// @exclude
//
// Copyright © contributors to CloudNativePG, established as
// CloudNativePG a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/klio_wal.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	WalName       string                 `protobuf:"bytes,2,opt,name=wal_name,json=walName,proto3" json:"wal_name,omitempty"`
	WalBlock      []byte                 `protobuf:"bytes,3,opt,name=wal_block,json=walBlock,proto3" json:"wal_block,omitempty"`
	SegmentSize   uint64                 `protobuf:"varint,4,opt,name=segment_size,json=segmentSize,proto3" json:"segment_size,omitempty"`
	SendToTier2   bool                   `protobuf:"varint,7,opt,name=send_to_tier2,json=sendToTier2,proto3" json:"send_to_tier2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_klio_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *PutRequest) GetWalName() string {
	if x != nil {
		return x.WalName
	}
	return ""
}

func (x *PutRequest) GetWalBlock() []byte {
	if x != nil {
		return x.WalBlock
	}
	return nil
}

func (x *PutRequest) GetSegmentSize() uint64 {
	if x != nil {
		return x.SegmentSize
	}
	return 0
}

func (x *PutRequest) GetSendToTier2() bool {
	if x != nil {
		return x.SendToTier2
	}
	return false
}

// This is streamed back by the WAL server on the Put stream. Each message
// acknowledges that the bytes up to written_size have been durably persisted
// (fsynced) on the server. The client uses it to advance the flush position it
// reports to PostgreSQL only up to data that is genuinely durable.
type PutResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cumulative number of bytes of the current WAL file that have been durably
	// persisted (fsynced) on the server.
	WrittenSize   uint64 `protobuf:"varint,1,opt,name=written_size,json=writtenSize,proto3" json:"written_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResult) Reset() {
	*x = PutResult{}
	mi := &file_proto_klio_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResult) ProtoMessage() {}

func (x *PutResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResult.ProtoReflect.Descriptor instead.
func (*PutResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{1}
}

func (x *PutResult) GetWrittenSize() uint64 {
	if x != nil {
		return x.WrittenSize
	}
	return 0
}

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_proto_klio_wal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{2}
}

func (x *GetMetadataRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	WalName       string                 `protobuf:"bytes,2,opt,name=wal_name,json=walName,proto3" json:"wal_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_klio_wal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *GetRequest) GetWalName() string {
	if x != nil {
		return x.WalName
	}
	return ""
}

type GetResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalBlock      []byte                 `protobuf:"bytes,1,opt,name=wal_block,json=walBlock,proto3" json:"wal_block,omitempty"`
	SegmentSize   uint64                 `protobuf:"varint,2,opt,name=segment_size,json=segmentSize,proto3" json:"segment_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResult) Reset() {
	*x = GetResult{}
	mi := &file_proto_klio_wal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResult) ProtoMessage() {}

func (x *GetResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResult.ProtoReflect.Descriptor instead.
func (*GetResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{4}
}

func (x *GetResult) GetWalBlock() []byte {
	if x != nil {
		return x.WalBlock
	}
	return nil
}

func (x *GetResult) GetSegmentSize() uint64 {
	if x != nil {
		return x.SegmentSize
	}
	return 0
}

type RequestWALStartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This is the cluster name
	ClusterName string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// This is the system ID
	SystemId string `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	// This is the current WAL name that is being written
	// by PostgreSQL. If empty, the start WAL name will be
	// found by looking at the stored WAL files.
	CurrentWalName string `protobuf:"bytes,3,opt,name=current_wal_name,json=currentWalName,proto3" json:"current_wal_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestWALStartRequest) Reset() {
	*x = RequestWALStartRequest{}
	mi := &file_proto_klio_wal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWALStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWALStartRequest) ProtoMessage() {}

func (x *RequestWALStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWALStartRequest.ProtoReflect.Descriptor instead.
func (*RequestWALStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{5}
}

func (x *RequestWALStartRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *RequestWALStartRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *RequestWALStartRequest) GetCurrentWalName() string {
	if x != nil {
		return x.CurrentWalName
	}
	return ""
}

type RequestWALStartResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The WAL file where the client is expected to start
	// streaming.
	WalName       string `protobuf:"bytes,1,opt,name=wal_name,json=walName,proto3" json:"wal_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWALStartResult) Reset() {
	*x = RequestWALStartResult{}
	mi := &file_proto_klio_wal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWALStartResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWALStartResult) ProtoMessage() {}

func (x *RequestWALStartResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWALStartResult.ProtoReflect.Descriptor instead.
func (*RequestWALStartResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{6}
}

func (x *RequestWALStartResult) GetWalName() string {
	if x != nil {
		return x.WalName
	}
	return ""
}

type ResetWALStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This is the cluster name
	ClusterName string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// This is the system ID
	SystemId string `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	// This is the current WAL name that is being written
	// by PostgreSQL. If empty, the start WAL name will be
	// found by looking at the stored WAL files.
	CurrentWalName string `protobuf:"bytes,3,opt,name=current_wal_name,json=currentWalName,proto3" json:"current_wal_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResetWALStreamRequest) Reset() {
	*x = ResetWALStreamRequest{}
	mi := &file_proto_klio_wal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetWALStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetWALStreamRequest) ProtoMessage() {}

func (x *ResetWALStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetWALStreamRequest.ProtoReflect.Descriptor instead.
func (*ResetWALStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{7}
}

func (x *ResetWALStreamRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ResetWALStreamRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *ResetWALStreamRequest) GetCurrentWalName() string {
	if x != nil {
		return x.CurrentWalName
	}
	return ""
}

type ResetWALStreamResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The WAL file where the client is expected to start
	// streaming.
	WalName       string `protobuf:"bytes,1,opt,name=wal_name,json=walName,proto3" json:"wal_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetWALStreamResult) Reset() {
	*x = ResetWALStreamResult{}
	mi := &file_proto_klio_wal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetWALStreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetWALStreamResult) ProtoMessage() {}

func (x *ResetWALStreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetWALStreamResult.ProtoReflect.Descriptor instead.
func (*ResetWALStreamResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{8}
}

func (x *ResetWALStreamResult) GetWalName() string {
	if x != nil {
		return x.WalName
	}
	return ""
}

// The following messages are written in the cluster metadata
// file
type ClusterMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The system ID of the current cluster
	SystemId string `protobuf:"bytes,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	// The gaps we are aware of in the collected WALs.
	Gaps          []*WALGap `protobuf:"bytes,2,rep,name=gaps,proto3" json:"gaps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMetadata) Reset() {
	*x = ClusterMetadata{}
	mi := &file_proto_klio_wal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMetadata) ProtoMessage() {}

func (x *ClusterMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMetadata.ProtoReflect.Descriptor instead.
func (*ClusterMetadata) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{9}
}

func (x *ClusterMetadata) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *ClusterMetadata) GetGaps() []*WALGap {
	if x != nil {
		return x.Gaps
	}
	return nil
}

// WALGap is a know gap in the WAL collection process.
// This is usually caused by an invocation of the reset-lsn Klio
// feature.
type WALGap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When this gap was detected and created.
	Ts *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	// When the gap started.
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// When the gap ends.
	End           string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALGap) Reset() {
	*x = WALGap{}
	mi := &file_proto_klio_wal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALGap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALGap) ProtoMessage() {}

func (x *WALGap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALGap.ProtoReflect.Descriptor instead.
func (*WALGap) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{10}
}

func (x *WALGap) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *WALGap) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *WALGap) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

// The following messages are used to write a WAL file
// in the Klio WAL Storage area
type StartWALFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KlioVersion   uint64                 `protobuf:"varint,1,opt,name=klio_version,json=klioVersion,proto3" json:"klio_version,omitempty"`
	FileLength    uint64                 `protobuf:"varint,2,opt,name=file_length,json=fileLength,proto3" json:"file_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWALFile) Reset() {
	*x = StartWALFile{}
	mi := &file_proto_klio_wal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWALFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWALFile) ProtoMessage() {}

func (x *StartWALFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWALFile.ProtoReflect.Descriptor instead.
func (*StartWALFile) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{11}
}

func (x *StartWALFile) GetKlioVersion() uint64 {
	if x != nil {
		return x.KlioVersion
	}
	return 0
}

func (x *StartWALFile) GetFileLength() uint64 {
	if x != nil {
		return x.FileLength
	}
	return 0
}

// This is sent to the WAL server every time a backup has
// been completed.
type CloseBackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the cluster.
	ClusterName string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// The name of the backup.
	BackupName string `protobuf:"bytes,3,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	// The backup timeline
	Timeline int32 `protobuf:"varint,4,opt,name=timeline,proto3" json:"timeline,omitempty"`
	// the first WAL required to restore this backup.
	StartWal string `protobuf:"bytes,5,opt,name=start_wal,json=startWal,proto3" json:"start_wal,omitempty"`
	// The last WAL required to restore this backup.
	EndWal string `protobuf:"bytes,6,opt,name=end_wal,json=endWal,proto3" json:"end_wal,omitempty"`
	// The size of a WAL segment. Needed to generate
	// the sequence of WAL files between the start and the end.
	SegmentSize uint64 `protobuf:"varint,7,opt,name=segment_size,json=segmentSize,proto3" json:"segment_size,omitempty"`
	// Require this backup to be sent to tier2.
	SendToTier2 bool `protobuf:"varint,8,opt,name=send_to_tier2,json=sendToTier2,proto3" json:"send_to_tier2,omitempty"`
	// When present, set the tier2 retention policy to the specified JSON-serialized policy.
	Tier2RetentionPolicy string `protobuf:"bytes,9,opt,name=tier2_retention_policy,json=tier2RetentionPolicy,proto3" json:"tier2_retention_policy,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CloseBackupRequest) Reset() {
	*x = CloseBackupRequest{}
	mi := &file_proto_klio_wal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseBackupRequest) ProtoMessage() {}

func (x *CloseBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseBackupRequest.ProtoReflect.Descriptor instead.
func (*CloseBackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{12}
}

func (x *CloseBackupRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *CloseBackupRequest) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

func (x *CloseBackupRequest) GetTimeline() int32 {
	if x != nil {
		return x.Timeline
	}
	return 0
}

func (x *CloseBackupRequest) GetStartWal() string {
	if x != nil {
		return x.StartWal
	}
	return ""
}

func (x *CloseBackupRequest) GetEndWal() string {
	if x != nil {
		return x.EndWal
	}
	return ""
}

func (x *CloseBackupRequest) GetSegmentSize() uint64 {
	if x != nil {
		return x.SegmentSize
	}
	return 0
}

func (x *CloseBackupRequest) GetSendToTier2() bool {
	if x != nil {
		return x.SendToTier2
	}
	return false
}

func (x *CloseBackupRequest) GetTier2RetentionPolicy() string {
	if x != nil {
		return x.Tier2RetentionPolicy
	}
	return ""
}

// This is sent by the WAL server in response to a CloseBackupRequest
// message.
type CloseBackupResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the backup has been scheduled to be synchronized
	// to tier2 storage
	Tier2Schedule bool `protobuf:"varint,1,opt,name=tier2_schedule,json=tier2Schedule,proto3" json:"tier2_schedule,omitempty"`
	// List of WAL files needed by this backup but still not
	// uploaded to tier1
	MissingWalFiles []string `protobuf:"bytes,2,rep,name=missing_wal_files,json=missingWalFiles,proto3" json:"missing_wal_files,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloseBackupResult) Reset() {
	*x = CloseBackupResult{}
	mi := &file_proto_klio_wal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseBackupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseBackupResult) ProtoMessage() {}

func (x *CloseBackupResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_wal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseBackupResult.ProtoReflect.Descriptor instead.
func (*CloseBackupResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_wal_proto_rawDescGZIP(), []int{13}
}

func (x *CloseBackupResult) GetTier2Schedule() bool {
	if x != nil {
		return x.Tier2Schedule
	}
	return false
}

func (x *CloseBackupResult) GetMissingWalFiles() []string {
	if x != nil {
		return x.MissingWalFiles
	}
	return nil
}

var File_proto_klio_wal_proto protoreflect.FileDescriptor

const file_proto_klio_wal_proto_rawDesc = "" +
	"\n" +
	"\x14proto/klio_wal.proto\x12\vklio.wal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x01\n" +
	"\n" +
	"PutRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x19\n" +
	"\bwal_name\x18\x02 \x01(\tR\awalName\x12\x1b\n" +
	"\twal_block\x18\x03 \x01(\fR\bwalBlock\x12!\n" +
	"\fsegment_size\x18\x04 \x01(\x04R\vsegmentSize\x12\"\n" +
	"\rsend_to_tier2\x18\a \x01(\bR\vsendToTier2J\x04\b\x05\x10\x06J\x04\b\x06\x10\aR\btrace_idR\aspan_id\".\n" +
	"\tPutResult\x12!\n" +
	"\fwritten_size\x18\x01 \x01(\x04R\vwrittenSize\"7\n" +
	"\x12GetMetadataRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\"J\n" +
	"\n" +
	"GetRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x19\n" +
	"\bwal_name\x18\x02 \x01(\tR\awalName\"K\n" +
	"\tGetResult\x12\x1b\n" +
	"\twal_block\x18\x01 \x01(\fR\bwalBlock\x12!\n" +
	"\fsegment_size\x18\x02 \x01(\x04R\vsegmentSize\"\x82\x01\n" +
	"\x16RequestWALStartRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12(\n" +
	"\x10current_wal_name\x18\x03 \x01(\tR\x0ecurrentWalName\"2\n" +
	"\x15RequestWALStartResult\x12\x19\n" +
	"\bwal_name\x18\x01 \x01(\tR\awalName\"\x81\x01\n" +
	"\x15ResetWALStreamRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12(\n" +
	"\x10current_wal_name\x18\x03 \x01(\tR\x0ecurrentWalName\"1\n" +
	"\x14ResetWALStreamResult\x12\x19\n" +
	"\bwal_name\x18\x01 \x01(\tR\awalName\"W\n" +
	"\x0fClusterMetadata\x12\x1b\n" +
	"\tsystem_id\x18\x01 \x01(\tR\bsystemId\x12'\n" +
	"\x04gaps\x18\x02 \x03(\v2\x13.klio.wal.v1.WALGapR\x04gaps\"\\\n" +
	"\x06WALGap\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x14\n" +
	"\x05start\x18\x02 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\tR\x03end\"R\n" +
	"\fStartWALFile\x12!\n" +
	"\fklio_version\x18\x01 \x01(\x04R\vklioVersion\x12\x1f\n" +
	"\vfile_length\x18\x02 \x01(\x04R\n" +
	"fileLength\"\xa7\x02\n" +
	"\x12CloseBackupRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x1f\n" +
	"\vbackup_name\x18\x03 \x01(\tR\n" +
	"backupName\x12\x1a\n" +
	"\btimeline\x18\x04 \x01(\x05R\btimeline\x12\x1b\n" +
	"\tstart_wal\x18\x05 \x01(\tR\bstartWal\x12\x17\n" +
	"\aend_wal\x18\x06 \x01(\tR\x06endWal\x12!\n" +
	"\fsegment_size\x18\a \x01(\x04R\vsegmentSize\x12\"\n" +
	"\rsend_to_tier2\x18\b \x01(\bR\vsendToTier2\x124\n" +
	"\x16tier2_retention_policy\x18\t \x01(\tR\x14tier2RetentionPolicy\"f\n" +
	"\x11CloseBackupResult\x12%\n" +
	"\x0etier2_schedule\x18\x01 \x01(\bR\rtier2Schedule\x12*\n" +
	"\x11missing_wal_files\x18\x02 \x03(\tR\x0fmissingWalFiles2\xda\x03\n" +
	"\x03WAL\x12<\n" +
	"\x03Put\x12\x17.klio.wal.v1.PutRequest\x1a\x16.klio.wal.v1.PutResult\"\x00(\x010\x01\x12:\n" +
	"\x03Get\x12\x17.klio.wal.v1.GetRequest\x1a\x16.klio.wal.v1.GetResult\"\x000\x01\x12N\n" +
	"\vGetMetadata\x12\x1f.klio.wal.v1.GetMetadataRequest\x1a\x1c.klio.wal.v1.ClusterMetadata\"\x00\x12\\\n" +
	"\x0fRequestWALStart\x12#.klio.wal.v1.RequestWALStartRequest\x1a\".klio.wal.v1.RequestWALStartResult\"\x00\x12Y\n" +
	"\x0eResetWALStream\x12\".klio.wal.v1.ResetWALStreamRequest\x1a!.klio.wal.v1.ResetWALStreamResult\"\x00\x12P\n" +
	"\vCloseBackup\x12\x1f.klio.wal.v1.CloseBackupRequest\x1a\x1e.klio.wal.v1.CloseBackupResult\"\x00B3Z1github.com/cloudnative-pg/klio/core/internal/grpcb\x06proto3"

var (
	file_proto_klio_wal_proto_rawDescOnce sync.Once
	file_proto_klio_wal_proto_rawDescData []byte
)

func file_proto_klio_wal_proto_rawDescGZIP() []byte {
	file_proto_klio_wal_proto_rawDescOnce.Do(func() {
		file_proto_klio_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_klio_wal_proto_rawDesc), len(file_proto_klio_wal_proto_rawDesc)))
	})
	return file_proto_klio_wal_proto_rawDescData
}

var file_proto_klio_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_klio_wal_proto_goTypes = []any{
	(*PutRequest)(nil),             // 0: klio.wal.v1.PutRequest
	(*PutResult)(nil),              // 1: klio.wal.v1.PutResult
	(*GetMetadataRequest)(nil),     // 2: klio.wal.v1.GetMetadataRequest
	(*GetRequest)(nil),             // 3: klio.wal.v1.GetRequest
	(*GetResult)(nil),              // 4: klio.wal.v1.GetResult
	(*RequestWALStartRequest)(nil), // 5: klio.wal.v1.RequestWALStartRequest
	(*RequestWALStartResult)(nil),  // 6: klio.wal.v1.RequestWALStartResult
	(*ResetWALStreamRequest)(nil),  // 7: klio.wal.v1.ResetWALStreamRequest
	(*ResetWALStreamResult)(nil),   // 8: klio.wal.v1.ResetWALStreamResult
	(*ClusterMetadata)(nil),        // 9: klio.wal.v1.ClusterMetadata
	(*WALGap)(nil),                 // 10: klio.wal.v1.WALGap
	(*StartWALFile)(nil),           // 11: klio.wal.v1.StartWALFile
	(*CloseBackupRequest)(nil),     // 12: klio.wal.v1.CloseBackupRequest
	(*CloseBackupResult)(nil),      // 13: klio.wal.v1.CloseBackupResult
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_proto_klio_wal_proto_depIdxs = []int32{
	10, // 0: klio.wal.v1.ClusterMetadata.gaps:type_name -> klio.wal.v1.WALGap
	14, // 1: klio.wal.v1.WALGap.ts:type_name -> google.protobuf.Timestamp
	0,  // 2: klio.wal.v1.WAL.Put:input_type -> klio.wal.v1.PutRequest
	3,  // 3: klio.wal.v1.WAL.Get:input_type -> klio.wal.v1.GetRequest
	2,  // 4: klio.wal.v1.WAL.GetMetadata:input_type -> klio.wal.v1.GetMetadataRequest
	5,  // 5: klio.wal.v1.WAL.RequestWALStart:input_type -> klio.wal.v1.RequestWALStartRequest
	7,  // 6: klio.wal.v1.WAL.ResetWALStream:input_type -> klio.wal.v1.ResetWALStreamRequest
	12, // 7: klio.wal.v1.WAL.CloseBackup:input_type -> klio.wal.v1.CloseBackupRequest
	1,  // 8: klio.wal.v1.WAL.Put:output_type -> klio.wal.v1.PutResult
	4,  // 9: klio.wal.v1.WAL.Get:output_type -> klio.wal.v1.GetResult
	9,  // 10: klio.wal.v1.WAL.GetMetadata:output_type -> klio.wal.v1.ClusterMetadata
	6,  // 11: klio.wal.v1.WAL.RequestWALStart:output_type -> klio.wal.v1.RequestWALStartResult
	8,  // 12: klio.wal.v1.WAL.ResetWALStream:output_type -> klio.wal.v1.ResetWALStreamResult
	13, // 13: klio.wal.v1.WAL.CloseBackup:output_type -> klio.wal.v1.CloseBackupResult
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_klio_wal_proto_init() }
func file_proto_klio_wal_proto_init() {
	if File_proto_klio_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_klio_wal_proto_rawDesc), len(file_proto_klio_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_klio_wal_proto_goTypes,
		DependencyIndexes: file_proto_klio_wal_proto_depIdxs,
		MessageInfos:      file_proto_klio_wal_proto_msgTypes,
	}.Build()
	File_proto_klio_wal_proto = out.File
	file_proto_klio_wal_proto_goTypes = nil
	file_proto_klio_wal_proto_depIdxs = nil
}
