// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/klio_admin.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tier represents a storage tier in the backup system.
type Tier int32

const (
	// TIER_UNSPECIFIED is the default value and should not be used.
	Tier_TIER_UNSPECIFIED Tier = 0
	// TIER_1 represents the local cache storage.
	Tier_TIER_1 Tier = 1
	// TIER_2 represents the object storage.
	Tier_TIER_2 Tier = 2
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_1",
		2: "TIER_2",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"TIER_1":           1,
		"TIER_2":           2,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_klio_admin_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_proto_klio_admin_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{0}
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{0}
}

type RefreshResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResult) Reset() {
	*x = RefreshResult{}
	mi := &file_proto_klio_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResult) ProtoMessage() {}

func (x *RefreshResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResult.ProtoReflect.Descriptor instead.
func (*RefreshResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{1}
}

type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{2}
}

type ListBackupsResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-serialized array of backup manifests.
	// Each manifest contains fields like:
	//   - id: string
	//   - cluster_name: string
	//   - timestamp: RFC3339 string
	//   - size_bytes: number
	//
	// See klioclient.BackupManifest for the canonical structure.
	// We use JSON bytes here to avoid duplicating the internal type definition
	// and conversion logic, as this is a local admin API.
	BackupManifests []byte `protobuf:"bytes,1,opt,name=backup_manifests,json=backupManifests,proto3" json:"backup_manifests,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListBackupsResult) Reset() {
	*x = ListBackupsResult{}
	mi := &file_proto_klio_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResult) ProtoMessage() {}

func (x *ListBackupsResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResult.ProtoReflect.Descriptor instead.
func (*ListBackupsResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListBackupsResult) GetBackupManifests() []byte {
	if x != nil {
		return x.BackupManifests
	}
	return nil
}

type QueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusRequest) Reset() {
	*x = QueueStatusRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusRequest) ProtoMessage() {}

func (x *QueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusRequest.ProtoReflect.Descriptor instead.
func (*QueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{4}
}

type QueueStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of backup synchronization tasks pending in the queue
	PendingBackups uint64 `protobuf:"varint,1,opt,name=pending_backups,json=pendingBackups,proto3" json:"pending_backups,omitempty"`
	// Number of WAL relay tasks pending in the queue
	PendingWals   uint64 `protobuf:"varint,2,opt,name=pending_wals,json=pendingWals,proto3" json:"pending_wals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusResponse) Reset() {
	*x = QueueStatusResponse{}
	mi := &file_proto_klio_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusResponse) ProtoMessage() {}

func (x *QueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusResponse.ProtoReflect.Descriptor instead.
func (*QueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{5}
}

func (x *QueueStatusResponse) GetPendingBackups() uint64 {
	if x != nil {
		return x.PendingBackups
	}
	return 0
}

func (x *QueueStatusResponse) GetPendingWals() uint64 {
	if x != nil {
		return x.PendingWals
	}
	return 0
}

// DeleteBackupRequest is the request to delete a backup from the server.
type DeleteBackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the backup to delete.
	BackupName string `protobuf:"bytes,1,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	// The storage tiers from which to delete the backup.
	// At least one tier must be specified.
	Tiers []Tier `protobuf:"varint,2,rep,packed,name=tiers,proto3,enum=klio.wal.v1.Tier" json:"tiers,omitempty"`
	// The name of the cluster that owns the backup.
	ClusterName   string `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBackupRequest) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

func (x *DeleteBackupRequest) GetTiers() []Tier {
	if x != nil {
		return x.Tiers
	}
	return nil
}

func (x *DeleteBackupRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

// DeleteBackupResponse is the response to a backup deletion request.
type DeleteBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupResponse) Reset() {
	*x = DeleteBackupResponse{}
	mi := &file_proto_klio_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupResponse) ProtoMessage() {}

func (x *DeleteBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{7}
}

var File_proto_klio_admin_proto protoreflect.FileDescriptor

const file_proto_klio_admin_proto_rawDesc = "" +
	"\n" +
	"\x16proto/klio_admin.proto\x12\vklio.wal.v1\"\x10\n" +
	"\x0eRefreshRequest\"\x0f\n" +
	"\rRefreshResult\"\x14\n" +
	"\x12ListBackupsRequest\">\n" +
	"\x11ListBackupsResult\x12)\n" +
	"\x10backup_manifests\x18\x01 \x01(\fR\x0fbackupManifests\"\x14\n" +
	"\x12QueueStatusRequest\"a\n" +
	"\x13QueueStatusResponse\x12'\n" +
	"\x0fpending_backups\x18\x01 \x01(\x04R\x0ependingBackups\x12!\n" +
	"\fpending_wals\x18\x02 \x01(\x04R\vpendingWals\"\x82\x01\n" +
	"\x13DeleteBackupRequest\x12\x1f\n" +
	"\vbackup_name\x18\x01 \x01(\tR\n" +
	"backupName\x12'\n" +
	"\x05tiers\x18\x02 \x03(\x0e2\x11.klio.wal.v1.TierR\x05tiers\x12!\n" +
	"\fcluster_name\x18\x03 \x01(\tR\vclusterName\"\x16\n" +
	"\x14DeleteBackupResponse*4\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06TIER_1\x10\x01\x12\n" +
	"\n" +
	"\x06TIER_2\x10\x022\xca\x02\n" +
	"\x05Admin\x12D\n" +
	"\aRefresh\x12\x1b.klio.wal.v1.RefreshRequest\x1a\x1a.klio.wal.v1.RefreshResult\"\x00\x12P\n" +
	"\vListBackups\x12\x1f.klio.wal.v1.ListBackupsRequest\x1a\x1e.klio.wal.v1.ListBackupsResult\"\x00\x12R\n" +
	"\vQueueStatus\x12\x1f.klio.wal.v1.QueueStatusRequest\x1a .klio.wal.v1.QueueStatusResponse\"\x00\x12U\n" +
	"\fDeleteBackup\x12 .klio.wal.v1.DeleteBackupRequest\x1a!.klio.wal.v1.DeleteBackupResponse\"\x00B1Z/github.com/cloudnative-pg/klio/core/internal/grpcb\x06proto3"

var (
	file_proto_klio_admin_proto_rawDescOnce sync.Once
	file_proto_klio_admin_proto_rawDescData []byte
)

func file_proto_klio_admin_proto_rawDescGZIP() []byte {
	file_proto_klio_admin_proto_rawDescOnce.Do(func() {
		file_proto_klio_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_klio_admin_proto_rawDesc), len(file_proto_klio_admin_proto_rawDesc)))
	})
	return file_proto_klio_admin_proto_rawDescData
}

var file_proto_klio_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_klio_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_klio_admin_proto_goTypes = []any{
	(Tier)(0),                    // 0: klio.wal.v1.Tier
	(*RefreshRequest)(nil),       // 1: klio.wal.v1.RefreshRequest
	(*RefreshResult)(nil),        // 2: klio.wal.v1.RefreshResult
	(*ListBackupsRequest)(nil),   // 3: klio.wal.v1.ListBackupsRequest
	(*ListBackupsResult)(nil),    // 4: klio.wal.v1.ListBackupsResult
	(*QueueStatusRequest)(nil),   // 5: klio.wal.v1.QueueStatusRequest
	(*QueueStatusResponse)(nil),  // 6: klio.wal.v1.QueueStatusResponse
	(*DeleteBackupRequest)(nil),  // 7: klio.wal.v1.DeleteBackupRequest
	(*DeleteBackupResponse)(nil), // 8: klio.wal.v1.DeleteBackupResponse
}
var file_proto_klio_admin_proto_depIdxs = []int32{
	0, // 0: klio.wal.v1.DeleteBackupRequest.tiers:type_name -> klio.wal.v1.Tier
	1, // 1: klio.wal.v1.Admin.Refresh:input_type -> klio.wal.v1.RefreshRequest
	3, // 2: klio.wal.v1.Admin.ListBackups:input_type -> klio.wal.v1.ListBackupsRequest
	5, // 3: klio.wal.v1.Admin.QueueStatus:input_type -> klio.wal.v1.QueueStatusRequest
	7, // 4: klio.wal.v1.Admin.DeleteBackup:input_type -> klio.wal.v1.DeleteBackupRequest
	2, // 5: klio.wal.v1.Admin.Refresh:output_type -> klio.wal.v1.RefreshResult
	4, // 6: klio.wal.v1.Admin.ListBackups:output_type -> klio.wal.v1.ListBackupsResult
	6, // 7: klio.wal.v1.Admin.QueueStatus:output_type -> klio.wal.v1.QueueStatusResponse
	8, // 8: klio.wal.v1.Admin.DeleteBackup:output_type -> klio.wal.v1.DeleteBackupResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_klio_admin_proto_init() }
func file_proto_klio_admin_proto_init() {
	if File_proto_klio_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_klio_admin_proto_rawDesc), len(file_proto_klio_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_klio_admin_proto_goTypes,
		DependencyIndexes: file_proto_klio_admin_proto_depIdxs,
		EnumInfos:         file_proto_klio_admin_proto_enumTypes,
		MessageInfos:      file_proto_klio_admin_proto_msgTypes,
	}.Build()
	File_proto_klio_admin_proto = out.File
	file_proto_klio_admin_proto_goTypes = nil
	file_proto_klio_admin_proto_depIdxs = nil
}
