// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/klio_admin.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{0}
}

type RefreshResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResult) Reset() {
	*x = RefreshResult{}
	mi := &file_proto_klio_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResult) ProtoMessage() {}

func (x *RefreshResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResult.ProtoReflect.Descriptor instead.
func (*RefreshResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{1}
}

type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{2}
}

type ListBackupsResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-serialized array of backup manifests.
	// Each manifest contains fields like:
	//   - id: string
	//   - cluster_name: string
	//   - timestamp: RFC3339 string
	//   - size_bytes: number
	//
	// See klioclient.BackupManifest for the canonical structure.
	// We use JSON bytes here to avoid duplicating the internal type definition
	// and conversion logic, as this is a local admin API.
	BackupManifests []byte `protobuf:"bytes,1,opt,name=backup_manifests,json=backupManifests,proto3" json:"backup_manifests,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListBackupsResult) Reset() {
	*x = ListBackupsResult{}
	mi := &file_proto_klio_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResult) ProtoMessage() {}

func (x *ListBackupsResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResult.ProtoReflect.Descriptor instead.
func (*ListBackupsResult) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListBackupsResult) GetBackupManifests() []byte {
	if x != nil {
		return x.BackupManifests
	}
	return nil
}

type QueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusRequest) Reset() {
	*x = QueueStatusRequest{}
	mi := &file_proto_klio_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusRequest) ProtoMessage() {}

func (x *QueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusRequest.ProtoReflect.Descriptor instead.
func (*QueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{4}
}

type QueueStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of backup synchronization tasks pending in the queue
	PendingBackups uint64 `protobuf:"varint,1,opt,name=pending_backups,json=pendingBackups,proto3" json:"pending_backups,omitempty"`
	// Number of WAL relay tasks pending in the queue
	PendingWals   uint64 `protobuf:"varint,2,opt,name=pending_wals,json=pendingWals,proto3" json:"pending_wals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusResponse) Reset() {
	*x = QueueStatusResponse{}
	mi := &file_proto_klio_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusResponse) ProtoMessage() {}

func (x *QueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_klio_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusResponse.ProtoReflect.Descriptor instead.
func (*QueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_klio_admin_proto_rawDescGZIP(), []int{5}
}

func (x *QueueStatusResponse) GetPendingBackups() uint64 {
	if x != nil {
		return x.PendingBackups
	}
	return 0
}

func (x *QueueStatusResponse) GetPendingWals() uint64 {
	if x != nil {
		return x.PendingWals
	}
	return 0
}

var File_proto_klio_admin_proto protoreflect.FileDescriptor

const file_proto_klio_admin_proto_rawDesc = "" +
	"\n" +
	"\x16proto/klio_admin.proto\x12\vklio.wal.v1\"\x10\n" +
	"\x0eRefreshRequest\"\x0f\n" +
	"\rRefreshResult\"\x14\n" +
	"\x12ListBackupsRequest\">\n" +
	"\x11ListBackupsResult\x12)\n" +
	"\x10backup_manifests\x18\x01 \x01(\fR\x0fbackupManifests\"\x14\n" +
	"\x12QueueStatusRequest\"a\n" +
	"\x13QueueStatusResponse\x12'\n" +
	"\x0fpending_backups\x18\x01 \x01(\x04R\x0ependingBackups\x12!\n" +
	"\fpending_wals\x18\x02 \x01(\x04R\vpendingWals2\xf3\x01\n" +
	"\x05Admin\x12D\n" +
	"\aRefresh\x12\x1b.klio.wal.v1.RefreshRequest\x1a\x1a.klio.wal.v1.RefreshResult\"\x00\x12P\n" +
	"\vListBackups\x12\x1f.klio.wal.v1.ListBackupsRequest\x1a\x1e.klio.wal.v1.ListBackupsResult\"\x00\x12R\n" +
	"\vQueueStatus\x12\x1f.klio.wal.v1.QueueStatusRequest\x1a .klio.wal.v1.QueueStatusResponse\"\x00B1Z/github.com/cloudnative-pg/klio/core/internal/grpcb\x06proto3"

var (
	file_proto_klio_admin_proto_rawDescOnce sync.Once
	file_proto_klio_admin_proto_rawDescData []byte
)

func file_proto_klio_admin_proto_rawDescGZIP() []byte {
	file_proto_klio_admin_proto_rawDescOnce.Do(func() {
		file_proto_klio_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_klio_admin_proto_rawDesc), len(file_proto_klio_admin_proto_rawDesc)))
	})
	return file_proto_klio_admin_proto_rawDescData
}

var file_proto_klio_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_klio_admin_proto_goTypes = []any{
	(*RefreshRequest)(nil),      // 0: klio.wal.v1.RefreshRequest
	(*RefreshResult)(nil),       // 1: klio.wal.v1.RefreshResult
	(*ListBackupsRequest)(nil),  // 2: klio.wal.v1.ListBackupsRequest
	(*ListBackupsResult)(nil),   // 3: klio.wal.v1.ListBackupsResult
	(*QueueStatusRequest)(nil),  // 4: klio.wal.v1.QueueStatusRequest
	(*QueueStatusResponse)(nil), // 5: klio.wal.v1.QueueStatusResponse
}
var file_proto_klio_admin_proto_depIdxs = []int32{
	0, // 0: klio.wal.v1.Admin.Refresh:input_type -> klio.wal.v1.RefreshRequest
	2, // 1: klio.wal.v1.Admin.ListBackups:input_type -> klio.wal.v1.ListBackupsRequest
	4, // 2: klio.wal.v1.Admin.QueueStatus:input_type -> klio.wal.v1.QueueStatusRequest
	1, // 3: klio.wal.v1.Admin.Refresh:output_type -> klio.wal.v1.RefreshResult
	3, // 4: klio.wal.v1.Admin.ListBackups:output_type -> klio.wal.v1.ListBackupsResult
	5, // 5: klio.wal.v1.Admin.QueueStatus:output_type -> klio.wal.v1.QueueStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_klio_admin_proto_init() }
func file_proto_klio_admin_proto_init() {
	if File_proto_klio_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_klio_admin_proto_rawDesc), len(file_proto_klio_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_klio_admin_proto_goTypes,
		DependencyIndexes: file_proto_klio_admin_proto_depIdxs,
		MessageInfos:      file_proto_klio_admin_proto_msgTypes,
	}.Build()
	File_proto_klio_admin_proto = out.File
	file_proto_klio_admin_proto_goTypes = nil
	file_proto_klio_admin_proto_depIdxs = nil
}
