// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/klio_wal.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WAL_Put_FullMethodName                 = "/klio.wal.v1.WAL/Put"
	WAL_Get_FullMethodName                 = "/klio.wal.v1.WAL/Get"
	WAL_GetMetadata_FullMethodName         = "/klio.wal.v1.WAL/GetMetadata"
	WAL_RequestWALStart_FullMethodName     = "/klio.wal.v1.WAL/RequestWALStart"
	WAL_ResetWALStream_FullMethodName      = "/klio.wal.v1.WAL/ResetWALStream"
	WAL_SetFirstRequiredWAL_FullMethodName = "/klio.wal.v1.WAL/SetFirstRequiredWAL"
	WAL_CloseBackup_FullMethodName         = "/klio.wal.v1.WAL/CloseBackup"
)

// WALClient is the client API for WAL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WALClient interface {
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, PutResult], error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResult], error)
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*ClusterMetadata, error)
	RequestWALStart(ctx context.Context, in *RequestWALStartRequest, opts ...grpc.CallOption) (*RequestWALStartResult, error)
	ResetWALStream(ctx context.Context, in *ResetWALStreamRequest, opts ...grpc.CallOption) (*ResetWALStreamResult, error)
	SetFirstRequiredWAL(ctx context.Context, in *SetFirstRequiredWALRequest, opts ...grpc.CallOption) (*SetFirstRequiredWALResult, error)
	CloseBackup(ctx context.Context, in *CloseBackupRequest, opts ...grpc.CallOption) (*CloseBackupResult, error)
}

type wALClient struct {
	cc grpc.ClientConnInterface
}

func NewWALClient(cc grpc.ClientConnInterface) WALClient {
	return &wALClient{cc}
}

func (c *wALClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, PutResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WAL_ServiceDesc.Streams[0], WAL_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutRequest, PutResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WAL_PutClient = grpc.ClientStreamingClient[PutRequest, PutResult]

func (c *wALClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WAL_ServiceDesc.Streams[1], WAL_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WAL_GetClient = grpc.ServerStreamingClient[GetResult]

func (c *wALClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*ClusterMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterMetadata)
	err := c.cc.Invoke(ctx, WAL_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wALClient) RequestWALStart(ctx context.Context, in *RequestWALStartRequest, opts ...grpc.CallOption) (*RequestWALStartResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestWALStartResult)
	err := c.cc.Invoke(ctx, WAL_RequestWALStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wALClient) ResetWALStream(ctx context.Context, in *ResetWALStreamRequest, opts ...grpc.CallOption) (*ResetWALStreamResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetWALStreamResult)
	err := c.cc.Invoke(ctx, WAL_ResetWALStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wALClient) SetFirstRequiredWAL(ctx context.Context, in *SetFirstRequiredWALRequest, opts ...grpc.CallOption) (*SetFirstRequiredWALResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFirstRequiredWALResult)
	err := c.cc.Invoke(ctx, WAL_SetFirstRequiredWAL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wALClient) CloseBackup(ctx context.Context, in *CloseBackupRequest, opts ...grpc.CallOption) (*CloseBackupResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseBackupResult)
	err := c.cc.Invoke(ctx, WAL_CloseBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WALServer is the server API for WAL service.
// All implementations must embed UnimplementedWALServer
// for forward compatibility.
type WALServer interface {
	Put(grpc.ClientStreamingServer[PutRequest, PutResult]) error
	Get(*GetRequest, grpc.ServerStreamingServer[GetResult]) error
	GetMetadata(context.Context, *GetMetadataRequest) (*ClusterMetadata, error)
	RequestWALStart(context.Context, *RequestWALStartRequest) (*RequestWALStartResult, error)
	ResetWALStream(context.Context, *ResetWALStreamRequest) (*ResetWALStreamResult, error)
	SetFirstRequiredWAL(context.Context, *SetFirstRequiredWALRequest) (*SetFirstRequiredWALResult, error)
	CloseBackup(context.Context, *CloseBackupRequest) (*CloseBackupResult, error)
	mustEmbedUnimplementedWALServer()
}

// UnimplementedWALServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWALServer struct{}

func (UnimplementedWALServer) Put(grpc.ClientStreamingServer[PutRequest, PutResult]) error {
	return status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedWALServer) Get(*GetRequest, grpc.ServerStreamingServer[GetResult]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedWALServer) GetMetadata(context.Context, *GetMetadataRequest) (*ClusterMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedWALServer) RequestWALStart(context.Context, *RequestWALStartRequest) (*RequestWALStartResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestWALStart not implemented")
}
func (UnimplementedWALServer) ResetWALStream(context.Context, *ResetWALStreamRequest) (*ResetWALStreamResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetWALStream not implemented")
}
func (UnimplementedWALServer) SetFirstRequiredWAL(context.Context, *SetFirstRequiredWALRequest) (*SetFirstRequiredWALResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFirstRequiredWAL not implemented")
}
func (UnimplementedWALServer) CloseBackup(context.Context, *CloseBackupRequest) (*CloseBackupResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseBackup not implemented")
}
func (UnimplementedWALServer) mustEmbedUnimplementedWALServer() {}
func (UnimplementedWALServer) testEmbeddedByValue()             {}

// UnsafeWALServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WALServer will
// result in compilation errors.
type UnsafeWALServer interface {
	mustEmbedUnimplementedWALServer()
}

func RegisterWALServer(s grpc.ServiceRegistrar, srv WALServer) {
	// If the following call panics, it indicates UnimplementedWALServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WAL_ServiceDesc, srv)
}

func _WAL_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WALServer).Put(&grpc.GenericServerStream[PutRequest, PutResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WAL_PutServer = grpc.ClientStreamingServer[PutRequest, PutResult]

func _WAL_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WALServer).Get(m, &grpc.GenericServerStream[GetRequest, GetResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WAL_GetServer = grpc.ServerStreamingServer[GetResult]

func _WAL_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WALServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WAL_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WALServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAL_RequestWALStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWALStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WALServer).RequestWALStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WAL_RequestWALStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WALServer).RequestWALStart(ctx, req.(*RequestWALStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAL_ResetWALStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetWALStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WALServer).ResetWALStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WAL_ResetWALStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WALServer).ResetWALStream(ctx, req.(*ResetWALStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAL_SetFirstRequiredWAL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFirstRequiredWALRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WALServer).SetFirstRequiredWAL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WAL_SetFirstRequiredWAL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WALServer).SetFirstRequiredWAL(ctx, req.(*SetFirstRequiredWALRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WAL_CloseBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WALServer).CloseBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WAL_CloseBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WALServer).CloseBackup(ctx, req.(*CloseBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WAL_ServiceDesc is the grpc.ServiceDesc for WAL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WAL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "klio.wal.v1.WAL",
	HandlerType: (*WALServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _WAL_GetMetadata_Handler,
		},
		{
			MethodName: "RequestWALStart",
			Handler:    _WAL_RequestWALStart_Handler,
		},
		{
			MethodName: "ResetWALStream",
			Handler:    _WAL_ResetWALStream_Handler,
		},
		{
			MethodName: "SetFirstRequiredWAL",
			Handler:    _WAL_SetFirstRequiredWAL_Handler,
		},
		{
			MethodName: "CloseBackup",
			Handler:    _WAL_CloseBackup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _WAL_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _WAL_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/klio_wal.proto",
}
