//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/cloudnative-pg/machinery/pkg/api"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheConfiguration) DeepCopyInto(out *CacheConfiguration) {
	*out = *in
	in.PersistentVolumeClaimTemplate.DeepCopyInto(&out.PersistentVolumeClaimTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheConfiguration.
func (in *CacheConfiguration) DeepCopy() *CacheConfiguration {
	if in == nil {
		return nil
	}
	out := new(CacheConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConfiguration) DeepCopyInto(out *DataConfiguration) {
	*out = *in
	in.PersistentVolumeClaimTemplate.DeepCopyInto(&out.PersistentVolumeClaimTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConfiguration.
func (in *DataConfiguration) DeepCopy() *DataConfiguration {
	if in == nil {
		return nil
	}
	out := new(DataConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfiguration) DeepCopyInto(out *ImageConfiguration) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfiguration.
func (in *ImageConfiguration) DeepCopy() *ImageConfiguration {
	if in == nil {
		return nil
	}
	out := new(ImageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfiguration) DeepCopyInto(out *PluginConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfiguration.
func (in *PluginConfiguration) DeepCopy() *PluginConfiguration {
	if in == nil {
		return nil
	}
	out := new(PluginConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PluginConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfigurationList) DeepCopyInto(out *PluginConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PluginConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfigurationList.
func (in *PluginConfigurationList) DeepCopy() *PluginConfigurationList {
	if in == nil {
		return nil
	}
	out := new(PluginConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PluginConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfigurationSpec) DeepCopyInto(out *PluginConfigurationSpec) {
	*out = *in
	in.Tier1.DeepCopyInto(&out.Tier1)
	in.Tier2.DeepCopyInto(&out.Tier2)
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfigurationSpec.
func (in *PluginConfigurationSpec) DeepCopy() *PluginConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(PluginConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfigurationStatus) DeepCopyInto(out *PluginConfigurationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfigurationStatus.
func (in *PluginConfigurationStatus) DeepCopy() *PluginConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(PluginConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueConfiguration) DeepCopyInto(out *QueueConfiguration) {
	*out = *in
	in.PersistentVolumeClaimTemplate.DeepCopyInto(&out.PersistentVolumeClaimTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueConfiguration.
func (in *QueueConfiguration) DeepCopy() *QueueConfiguration {
	if in == nil {
		return nil
	}
	out := new(QueueConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoverySource) DeepCopyInto(out *RecoverySource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoverySource.
func (in *RecoverySource) DeepCopy() *RecoverySource {
	if in == nil {
		return nil
	}
	out := new(RecoverySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoverySource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoverySourceList) DeepCopyInto(out *RecoverySourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecoverySource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoverySourceList.
func (in *RecoverySourceList) DeepCopy() *RecoverySourceList {
	if in == nil {
		return nil
	}
	out := new(RecoverySourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecoverySourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoverySourceSpec) DeepCopyInto(out *RecoverySourceSpec) {
	*out = *in
	in.ImageConfiguration.DeepCopyInto(&out.ImageConfiguration)
	out.TLSConfiguration = in.TLSConfiguration
	in.Tier2.DeepCopyInto(&out.Tier2)
	in.Storage.DeepCopyInto(&out.Storage)
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoverySourceSpec.
func (in *RecoverySourceSpec) DeepCopy() *RecoverySourceSpec {
	if in == nil {
		return nil
	}
	out := new(RecoverySourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoverySourceStatus) DeepCopyInto(out *RecoverySourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoverySourceStatus.
func (in *RecoverySourceStatus) DeepCopy() *RecoverySourceStatus {
	if in == nil {
		return nil
	}
	out := new(RecoverySourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoverySourceStorageConfiguration) DeepCopyInto(out *RecoverySourceStorageConfiguration) {
	*out = *in
	in.Cache.DeepCopyInto(&out.Cache)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoverySourceStorageConfiguration.
func (in *RecoverySourceStorageConfiguration) DeepCopy() *RecoverySourceStorageConfiguration {
	if in == nil {
		return nil
	}
	out := new(RecoverySourceStorageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
	if in.KeepLatest != nil {
		in, out := &in.KeepLatest, &out.KeepLatest
		*out = new(int)
		**out = **in
	}
	if in.KeepAnnual != nil {
		in, out := &in.KeepAnnual, &out.KeepAnnual
		*out = new(int)
		**out = **in
	}
	if in.KeepMonthly != nil {
		in, out := &in.KeepMonthly, &out.KeepMonthly
		*out = new(int)
		**out = **in
	}
	if in.KeepWeekly != nil {
		in, out := &in.KeepWeekly, &out.KeepWeekly
		*out = new(int)
		**out = **in
	}
	if in.KeepDaily != nil {
		in, out := &in.KeepDaily, &out.KeepDaily
		*out = new(int)
		**out = **in
	}
	if in.KeepHourly != nil {
		in, out := &in.KeepHourly, &out.KeepHourly
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicy.
func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Configuration) DeepCopyInto(out *S3Configuration) {
	*out = *in
	if in.AccessKeyID != nil {
		in, out := &in.AccessKeyID, &out.AccessKeyID
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.SecretAccessKey != nil {
		in, out := &in.SecretAccessKey, &out.SecretAccessKey
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.SessionToken != nil {
		in, out := &in.SessionToken, &out.SessionToken
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.CustomCABundle != nil {
		in, out := &in.CustomCABundle, &out.CustomCABundle
		*out = new(api.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Configuration.
func (in *S3Configuration) DeepCopy() *S3Configuration {
	if in == nil {
		return nil
	}
	out := new(S3Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Server) DeepCopyInto(out *Server) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Server.
func (in *Server) DeepCopy() *Server {
	if in == nil {
		return nil
	}
	out := new(Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Server) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerList) DeepCopyInto(out *ServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Server, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerList.
func (in *ServerList) DeepCopy() *ServerList {
	if in == nil {
		return nil
	}
	out := new(ServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSpec) DeepCopyInto(out *ServerSpec) {
	*out = *in
	in.ImageConfiguration.DeepCopyInto(&out.ImageConfiguration)
	out.TLSConfiguration = in.TLSConfiguration
	in.CacheConfiguration.DeepCopyInto(&out.CacheConfiguration)
	in.DataConfiguration.DeepCopyInto(&out.DataConfiguration)
	if in.QueueConfiguration != nil {
		in, out := &in.QueueConfiguration, &out.QueueConfiguration
		*out = new(QueueConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.Tier2 != nil {
		in, out := &in.Tier2, &out.Tier2
		*out = new(Tier2Configuration)
		(*in).DeepCopyInto(*out)
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSpec.
func (in *ServerSpec) DeepCopy() *ServerSpec {
	if in == nil {
		return nil
	}
	out := new(ServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerStatus) DeepCopyInto(out *ServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerStatus.
func (in *ServerStatus) DeepCopy() *ServerStatus {
	if in == nil {
		return nil
	}
	out := new(ServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfiguration) DeepCopyInto(out *TLSConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfiguration.
func (in *TLSConfiguration) DeepCopy() *TLSConfiguration {
	if in == nil {
		return nil
	}
	out := new(TLSConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tier1PluginConfiguration) DeepCopyInto(out *Tier1PluginConfiguration) {
	*out = *in
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(RetentionPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tier1PluginConfiguration.
func (in *Tier1PluginConfiguration) DeepCopy() *Tier1PluginConfiguration {
	if in == nil {
		return nil
	}
	out := new(Tier1PluginConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tier2Configuration) DeepCopyInto(out *Tier2Configuration) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Configuration)
		(*in).DeepCopyInto(*out)
	}
	if in.EncryptionPassword != nil {
		in, out := &in.EncryptionPassword, &out.EncryptionPassword
		*out = new(api.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tier2Configuration.
func (in *Tier2Configuration) DeepCopy() *Tier2Configuration {
	if in == nil {
		return nil
	}
	out := new(Tier2Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tier2PluginConfiguration) DeepCopyInto(out *Tier2PluginConfiguration) {
	*out = *in
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(RetentionPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tier2PluginConfiguration.
func (in *Tier2PluginConfiguration) DeepCopy() *Tier2PluginConfiguration {
	if in == nil {
		return nil
	}
	out := new(Tier2PluginConfiguration)
	in.DeepCopyInto(out)
	return out
}
