// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.2
// source: proto/wal.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WAL_UploadWAL_FullMethodName = "/klio.wal.v1.WAL/UploadWAL"
	WAL_GetWAL_FullMethodName    = "/klio.wal.v1.WAL/GetWAL"
)

// WALClient is the client API for WAL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WALClient interface {
	UploadWAL(ctx context.Context, opts ...grpc.CallOption) (WAL_UploadWALClient, error)
	GetWAL(ctx context.Context, in *GetWALRequest, opts ...grpc.CallOption) (WAL_GetWALClient, error)
}

type wALClient struct {
	cc grpc.ClientConnInterface
}

func NewWALClient(cc grpc.ClientConnInterface) WALClient {
	return &wALClient{cc}
}

func (c *wALClient) UploadWAL(ctx context.Context, opts ...grpc.CallOption) (WAL_UploadWALClient, error) {
	stream, err := c.cc.NewStream(ctx, &WAL_ServiceDesc.Streams[0], WAL_UploadWAL_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &wALUploadWALClient{stream}
	return x, nil
}

type WAL_UploadWALClient interface {
	Send(*UploadWALRequest) error
	CloseAndRecv() (*UploadWALResult, error)
	grpc.ClientStream
}

type wALUploadWALClient struct {
	grpc.ClientStream
}

func (x *wALUploadWALClient) Send(m *UploadWALRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *wALUploadWALClient) CloseAndRecv() (*UploadWALResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadWALResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wALClient) GetWAL(ctx context.Context, in *GetWALRequest, opts ...grpc.CallOption) (WAL_GetWALClient, error) {
	stream, err := c.cc.NewStream(ctx, &WAL_ServiceDesc.Streams[1], WAL_GetWAL_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &wALGetWALClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WAL_GetWALClient interface {
	Recv() (*GetWALResult, error)
	grpc.ClientStream
}

type wALGetWALClient struct {
	grpc.ClientStream
}

func (x *wALGetWALClient) Recv() (*GetWALResult, error) {
	m := new(GetWALResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WALServer is the server API for WAL service.
// All implementations must embed UnimplementedWALServer
// for forward compatibility
type WALServer interface {
	UploadWAL(WAL_UploadWALServer) error
	GetWAL(*GetWALRequest, WAL_GetWALServer) error
	mustEmbedUnimplementedWALServer()
}

// UnimplementedWALServer must be embedded to have forward compatible implementations.
type UnimplementedWALServer struct {
}

func (UnimplementedWALServer) UploadWAL(WAL_UploadWALServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadWAL not implemented")
}
func (UnimplementedWALServer) GetWAL(*GetWALRequest, WAL_GetWALServer) error {
	return status.Errorf(codes.Unimplemented, "method GetWAL not implemented")
}
func (UnimplementedWALServer) mustEmbedUnimplementedWALServer() {}

// UnsafeWALServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WALServer will
// result in compilation errors.
type UnsafeWALServer interface {
	mustEmbedUnimplementedWALServer()
}

func RegisterWALServer(s grpc.ServiceRegistrar, srv WALServer) {
	s.RegisterService(&WAL_ServiceDesc, srv)
}

func _WAL_UploadWAL_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WALServer).UploadWAL(&wALUploadWALServer{stream})
}

type WAL_UploadWALServer interface {
	SendAndClose(*UploadWALResult) error
	Recv() (*UploadWALRequest, error)
	grpc.ServerStream
}

type wALUploadWALServer struct {
	grpc.ServerStream
}

func (x *wALUploadWALServer) SendAndClose(m *UploadWALResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *wALUploadWALServer) Recv() (*UploadWALRequest, error) {
	m := new(UploadWALRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WAL_GetWAL_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWALRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WALServer).GetWAL(m, &wALGetWALServer{stream})
}

type WAL_GetWALServer interface {
	Send(*GetWALResult) error
	grpc.ServerStream
}

type wALGetWALServer struct {
	grpc.ServerStream
}

func (x *wALGetWALServer) Send(m *GetWALResult) error {
	return x.ServerStream.SendMsg(m)
}

// WAL_ServiceDesc is the grpc.ServiceDesc for WAL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WAL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "klio.wal.v1.WAL",
	HandlerType: (*WALServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadWAL",
			Handler:       _WAL_UploadWAL_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetWAL",
			Handler:       _WAL_GetWAL_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/wal.proto",
}
