apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-b-klio-user
spec:
  commonName: klio@cluster-b
  secretName: cluster-b-klio-user

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - client auth

  issuerRef:
    name: klio-server-ca
    kind: ClusterIssuer
    group: cert-manager.io
