version: "2"
linters:
  default: all
  disable:
    - mnd
    - depguard
    - exhaustruct
    - exhaustruct_v5
    - funlen
    - paralleltest
    - testpackage
    - wsl
    - wsl_v5
    - err113
    - wrapcheck
    - varnamelen
    - nilnil
    - goconst
    - godox
    - gomodguard
    - noinlineerr
  settings:
    gomoddirectives:
      replace-allow-list:
        - github.com/fclairamb/afero-s3
    lll:
      line-length: 120
    nlreturn:
      block-size: 3
    ireturn:
      allow:
        - afero.Fs
        - blob.Storage
        - error
        - stdlib
        - github.com/cloudnative-pg/klio/core/internal/client/klioclient.Client
        - k8s.io/apimachinery/pkg/runtime.Object
    varnamelen:
      ignore-decls:
        - g Gomega
    tagliatelle:
      case:
        extended-rules:
          json:
            initialism-overrides:
              LSN: true
              WAL: true
        overrides:
          - pkg: pkg/config
            rules:
              json: snake
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: should not use dot imports
        source: ginkgo|gomega
      - linters:
          - revive
        text: avoid meaningless package names
        path: internal/client/klioclient/common
      - linters:
          - lll
        source: //\s*\+
    paths:
      - zz_generated.*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cloudnative-pg/klio)
        - blank
        - dot
  exclusions:
    generated: lax
    paths:
      - zz_generated.*
      - third_party$
      - builtin$
      - examples$
