apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: klio-server-otel-client
spec:
  secretName: klio-server-otel-client-tls
  commonName: klio
  dnsNames:
    - klio
    - klio.default
    - klio.default.svc

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
