// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/wal.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	WalName       string                 `protobuf:"bytes,2,opt,name=wal_name,json=walName,proto3" json:"wal_name,omitempty"`
	WalBlock      []byte                 `protobuf:"bytes,3,opt,name=wal_block,json=walBlock,proto3" json:"wal_block,omitempty"`
	SegmentSize   uint64                 `protobuf:"varint,4,opt,name=segment_size,json=segmentSize,proto3" json:"segment_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *PutRequest) GetWalName() string {
	if x != nil {
		return x.WalName
	}
	return ""
}

func (x *PutRequest) GetWalBlock() []byte {
	if x != nil {
		return x.WalBlock
	}
	return nil
}

func (x *PutRequest) GetSegmentSize() uint64 {
	if x != nil {
		return x.SegmentSize
	}
	return 0
}

type PutResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrittenSize   uint64                 `protobuf:"varint,1,opt,name=written_size,json=writtenSize,proto3" json:"written_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResult) Reset() {
	*x = PutResult{}
	mi := &file_proto_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResult) ProtoMessage() {}

func (x *PutResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResult.ProtoReflect.Descriptor instead.
func (*PutResult) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{1}
}

func (x *PutResult) GetWrittenSize() uint64 {
	if x != nil {
		return x.WrittenSize
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	WalName       string                 `protobuf:"bytes,2,opt,name=wal_name,json=walName,proto3" json:"wal_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_wal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *GetRequest) GetWalName() string {
	if x != nil {
		return x.WalName
	}
	return ""
}

type GetResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalBlock      []byte                 `protobuf:"bytes,1,opt,name=wal_block,json=walBlock,proto3" json:"wal_block,omitempty"`
	SegmentSize   uint64                 `protobuf:"varint,2,opt,name=segment_size,json=segmentSize,proto3" json:"segment_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResult) Reset() {
	*x = GetResult{}
	mi := &file_proto_wal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResult) ProtoMessage() {}

func (x *GetResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResult.ProtoReflect.Descriptor instead.
func (*GetResult) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{3}
}

func (x *GetResult) GetWalBlock() []byte {
	if x != nil {
		return x.WalBlock
	}
	return nil
}

func (x *GetResult) GetSegmentSize() uint64 {
	if x != nil {
		return x.SegmentSize
	}
	return 0
}

type GetLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestRequest) Reset() {
	*x = GetLatestRequest{}
	mi := &file_proto_wal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRequest) ProtoMessage() {}

func (x *GetLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRequest.ProtoReflect.Descriptor instead.
func (*GetLatestRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type GetLatestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalName       *string                `protobuf:"bytes,1,opt,name=wal_name,json=walName,proto3,oneof" json:"wal_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestResult) Reset() {
	*x = GetLatestResult{}
	mi := &file_proto_wal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestResult) ProtoMessage() {}

func (x *GetLatestResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestResult.ProtoReflect.Descriptor instead.
func (*GetLatestResult) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestResult) GetWalName() string {
	if x != nil && x.WalName != nil {
		return *x.WalName
	}
	return ""
}

type StartWALFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KlioVersion   uint64                 `protobuf:"varint,1,opt,name=klio_version,json=klioVersion,proto3" json:"klio_version,omitempty"`
	FileLength    uint64                 `protobuf:"varint,2,opt,name=file_length,json=fileLength,proto3" json:"file_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWALFile) Reset() {
	*x = StartWALFile{}
	mi := &file_proto_wal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWALFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWALFile) ProtoMessage() {}

func (x *StartWALFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWALFile.ProtoReflect.Descriptor instead.
func (*StartWALFile) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{6}
}

func (x *StartWALFile) GetKlioVersion() uint64 {
	if x != nil {
		return x.KlioVersion
	}
	return 0
}

func (x *StartWALFile) GetFileLength() uint64 {
	if x != nil {
		return x.FileLength
	}
	return 0
}

type WALFileBlock struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Range             []byte                 `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	EncryptionVersion uint64                 `protobuf:"varint,2,opt,name=encryption_version,json=encryptionVersion,proto3" json:"encryption_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WALFileBlock) Reset() {
	*x = WALFileBlock{}
	mi := &file_proto_wal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALFileBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALFileBlock) ProtoMessage() {}

func (x *WALFileBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALFileBlock.ProtoReflect.Descriptor instead.
func (*WALFileBlock) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{7}
}

func (x *WALFileBlock) GetRange() []byte {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *WALFileBlock) GetEncryptionVersion() uint64 {
	if x != nil {
		return x.EncryptionVersion
	}
	return 0
}

var File_proto_wal_proto protoreflect.FileDescriptor

const file_proto_wal_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/wal.proto\x12\vklio.wal.v1\"\x8a\x01\n" +
	"\n" +
	"PutRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x19\n" +
	"\bwal_name\x18\x02 \x01(\tR\awalName\x12\x1b\n" +
	"\twal_block\x18\x03 \x01(\fR\bwalBlock\x12!\n" +
	"\fsegment_size\x18\x04 \x01(\x04R\vsegmentSize\".\n" +
	"\tPutResult\x12!\n" +
	"\fwritten_size\x18\x01 \x01(\x04R\vwrittenSize\"J\n" +
	"\n" +
	"GetRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x19\n" +
	"\bwal_name\x18\x02 \x01(\tR\awalName\"K\n" +
	"\tGetResult\x12\x1b\n" +
	"\twal_block\x18\x01 \x01(\fR\bwalBlock\x12!\n" +
	"\fsegment_size\x18\x02 \x01(\x04R\vsegmentSize\"5\n" +
	"\x10GetLatestRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\">\n" +
	"\x0fGetLatestResult\x12\x1e\n" +
	"\bwal_name\x18\x01 \x01(\tH\x00R\awalName\x88\x01\x01B\v\n" +
	"\t_wal_name\"R\n" +
	"\fStartWALFile\x12!\n" +
	"\fklio_version\x18\x01 \x01(\x04R\vklioVersion\x12\x1f\n" +
	"\vfile_length\x18\x02 \x01(\x04R\n" +
	"fileLength\"S\n" +
	"\fWALFileBlock\x12\x14\n" +
	"\x05range\x18\x01 \x01(\fR\x05range\x12-\n" +
	"\x12encryption_version\x18\x02 \x01(\x04R\x11encryptionVersion2\xc9\x01\n" +
	"\x03WAL\x12:\n" +
	"\x03Put\x12\x17.klio.wal.v1.PutRequest\x1a\x16.klio.wal.v1.PutResult\"\x00(\x01\x12:\n" +
	"\x03Get\x12\x17.klio.wal.v1.GetRequest\x1a\x16.klio.wal.v1.GetResult\"\x000\x01\x12J\n" +
	"\tGetLatest\x12\x1d.klio.wal.v1.GetLatestRequest\x1a\x1c.klio.wal.v1.GetLatestResult\"\x00B,Z*github.com/EnterpriseDB/klio/internal/grpcb\x06proto3"

var (
	file_proto_wal_proto_rawDescOnce sync.Once
	file_proto_wal_proto_rawDescData []byte
)

func file_proto_wal_proto_rawDescGZIP() []byte {
	file_proto_wal_proto_rawDescOnce.Do(func() {
		file_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wal_proto_rawDesc), len(file_proto_wal_proto_rawDesc)))
	})
	return file_proto_wal_proto_rawDescData
}

var file_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_wal_proto_goTypes = []any{
	(*PutRequest)(nil),       // 0: klio.wal.v1.PutRequest
	(*PutResult)(nil),        // 1: klio.wal.v1.PutResult
	(*GetRequest)(nil),       // 2: klio.wal.v1.GetRequest
	(*GetResult)(nil),        // 3: klio.wal.v1.GetResult
	(*GetLatestRequest)(nil), // 4: klio.wal.v1.GetLatestRequest
	(*GetLatestResult)(nil),  // 5: klio.wal.v1.GetLatestResult
	(*StartWALFile)(nil),     // 6: klio.wal.v1.StartWALFile
	(*WALFileBlock)(nil),     // 7: klio.wal.v1.WALFileBlock
}
var file_proto_wal_proto_depIdxs = []int32{
	0, // 0: klio.wal.v1.WAL.Put:input_type -> klio.wal.v1.PutRequest
	2, // 1: klio.wal.v1.WAL.Get:input_type -> klio.wal.v1.GetRequest
	4, // 2: klio.wal.v1.WAL.GetLatest:input_type -> klio.wal.v1.GetLatestRequest
	1, // 3: klio.wal.v1.WAL.Put:output_type -> klio.wal.v1.PutResult
	3, // 4: klio.wal.v1.WAL.Get:output_type -> klio.wal.v1.GetResult
	5, // 5: klio.wal.v1.WAL.GetLatest:output_type -> klio.wal.v1.GetLatestResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wal_proto_init() }
func file_proto_wal_proto_init() {
	if File_proto_wal_proto != nil {
		return
	}
	file_proto_wal_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wal_proto_rawDesc), len(file_proto_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wal_proto_goTypes,
		DependencyIndexes: file_proto_wal_proto_depIdxs,
		MessageInfos:      file_proto_wal_proto_msgTypes,
	}.Build()
	File_proto_wal_proto = out.File
	file_proto_wal_proto_goTypes = nil
	file_proto_wal_proto_depIdxs = nil
}
