// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.2
// source: proto/wal.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WAL_Put_FullMethodName       = "/klio.wal.v1.WAL/Put"
	WAL_Get_FullMethodName       = "/klio.wal.v1.WAL/Get"
	WAL_GetLatest_FullMethodName = "/klio.wal.v1.WAL/GetLatest"
)

// WALClient is the client API for WAL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WALClient interface {
	Put(ctx context.Context, opts ...grpc.CallOption) (WAL_PutClient, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (WAL_GetClient, error)
	GetLatest(ctx context.Context, in *GetLatestRequest, opts ...grpc.CallOption) (*GetLatestResult, error)
}

type wALClient struct {
	cc grpc.ClientConnInterface
}

func NewWALClient(cc grpc.ClientConnInterface) WALClient {
	return &wALClient{cc}
}

func (c *wALClient) Put(ctx context.Context, opts ...grpc.CallOption) (WAL_PutClient, error) {
	stream, err := c.cc.NewStream(ctx, &WAL_ServiceDesc.Streams[0], WAL_Put_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &wALPutClient{stream}
	return x, nil
}

type WAL_PutClient interface {
	Send(*PutRequest) error
	CloseAndRecv() (*PutResult, error)
	grpc.ClientStream
}

type wALPutClient struct {
	grpc.ClientStream
}

func (x *wALPutClient) Send(m *PutRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *wALPutClient) CloseAndRecv() (*PutResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wALClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (WAL_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &WAL_ServiceDesc.Streams[1], WAL_Get_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &wALGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WAL_GetClient interface {
	Recv() (*GetResult, error)
	grpc.ClientStream
}

type wALGetClient struct {
	grpc.ClientStream
}

func (x *wALGetClient) Recv() (*GetResult, error) {
	m := new(GetResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wALClient) GetLatest(ctx context.Context, in *GetLatestRequest, opts ...grpc.CallOption) (*GetLatestResult, error) {
	out := new(GetLatestResult)
	err := c.cc.Invoke(ctx, WAL_GetLatest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WALServer is the server API for WAL service.
// All implementations must embed UnimplementedWALServer
// for forward compatibility
type WALServer interface {
	Put(WAL_PutServer) error
	Get(*GetRequest, WAL_GetServer) error
	GetLatest(context.Context, *GetLatestRequest) (*GetLatestResult, error)
	mustEmbedUnimplementedWALServer()
}

// UnimplementedWALServer must be embedded to have forward compatible implementations.
type UnimplementedWALServer struct {
}

func (UnimplementedWALServer) Put(WAL_PutServer) error {
	return status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedWALServer) Get(*GetRequest, WAL_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedWALServer) GetLatest(context.Context, *GetLatestRequest) (*GetLatestResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatest not implemented")
}
func (UnimplementedWALServer) mustEmbedUnimplementedWALServer() {}

// UnsafeWALServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WALServer will
// result in compilation errors.
type UnsafeWALServer interface {
	mustEmbedUnimplementedWALServer()
}

func RegisterWALServer(s grpc.ServiceRegistrar, srv WALServer) {
	s.RegisterService(&WAL_ServiceDesc, srv)
}

func _WAL_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WALServer).Put(&wALPutServer{stream})
}

type WAL_PutServer interface {
	SendAndClose(*PutResult) error
	Recv() (*PutRequest, error)
	grpc.ServerStream
}

type wALPutServer struct {
	grpc.ServerStream
}

func (x *wALPutServer) SendAndClose(m *PutResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *wALPutServer) Recv() (*PutRequest, error) {
	m := new(PutRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WAL_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WALServer).Get(m, &wALGetServer{stream})
}

type WAL_GetServer interface {
	Send(*GetResult) error
	grpc.ServerStream
}

type wALGetServer struct {
	grpc.ServerStream
}

func (x *wALGetServer) Send(m *GetResult) error {
	return x.ServerStream.SendMsg(m)
}

func _WAL_GetLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WALServer).GetLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WAL_GetLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WALServer).GetLatest(ctx, req.(*GetLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WAL_ServiceDesc is the grpc.ServiceDesc for WAL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WAL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "klio.wal.v1.WAL",
	HandlerType: (*WALServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatest",
			Handler:    _WAL_GetLatest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _WAL_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _WAL_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/wal.proto",
}
