//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlioBackup) DeepCopyInto(out *KlioBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlioBackup.
func (in *KlioBackup) DeepCopy() *KlioBackup {
	if in == nil {
		return nil
	}
	out := new(KlioBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlioBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlioBackupList) DeepCopyInto(out *KlioBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KlioBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlioBackupList.
func (in *KlioBackupList) DeepCopy() *KlioBackupList {
	if in == nil {
		return nil
	}
	out := new(KlioBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlioBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlioBackupSpec) DeepCopyInto(out *KlioBackupSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlioBackupSpec.
func (in *KlioBackupSpec) DeepCopy() *KlioBackupSpec {
	if in == nil {
		return nil
	}
	out := new(KlioBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlioBackupStatus) DeepCopyInto(out *KlioBackupStatus) {
	*out = *in
	if in.Tablespaces != nil {
		in, out := &in.Tablespaces, &out.Tablespaces
		*out = make(TablespaceLayoutList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.StoppedAt.DeepCopyInto(&out.StoppedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlioBackupStatus.
func (in *KlioBackupStatus) DeepCopy() *KlioBackupStatus {
	if in == nil {
		return nil
	}
	out := new(KlioBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TablespaceLayout) DeepCopyInto(out *TablespaceLayout) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TablespaceLayout.
func (in *TablespaceLayout) DeepCopy() *TablespaceLayout {
	if in == nil {
		return nil
	}
	out := new(TablespaceLayout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in TablespaceLayoutList) DeepCopyInto(out *TablespaceLayoutList) {
	{
		in := &in
		*out = make(TablespaceLayoutList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TablespaceLayoutList.
func (in TablespaceLayoutList) DeepCopy() TablespaceLayoutList {
	if in == nil {
		return nil
	}
	out := new(TablespaceLayoutList)
	in.DeepCopyInto(out)
	return *out
}
