syntax = "proto3";
package klio.wal.v1;
option go_package = "github.com/EnterpriseDB/klio/internal/grpc";

service WAL {
    rpc Put(stream PutRequest) returns (PutResult) {}
    rpc Get(GetRequest) returns (stream GetResult) {}
    rpc GetLatest(GetLatestRequest) returns (GetLatestResult) {}
}

message PutRequest {
    string cluster_name = 1;
    string wal_name = 2;
    bytes wal_block = 3;
    uint64 segment_size = 4;
}

message PutResult {
    uint64 written_size = 1;
}

message GetRequest {
    string cluster_name = 1;
    string wal_name = 2;
}

message GetResult {
    bytes wal_block = 1;
}

message GetLatestRequest {
    string cluster_name = 1;
}

message GetLatestResult {
    optional string wal_name = 1;
}
