apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: klio
  name: klio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: klio
    spec:
      containers:
      - image: registry:5000/klio:dev
        name: klio
        args:
        - run
        envFrom:
        - secretRef:
            name: klio
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /certificates
          name: certificates
        resources: {}
      volumes:
      - name: data
        emptyDir: {}
      - name: certificates
        projected:
          sources:
          - secret:
              name: cluster-example-replication
              items:
              - key: tls.crt
                path: tls.crt
                mode: 0o600
              - key: tls.key
                path: tls.key
                mode: 0o600
          - secret:
              name: cluster-example-ca
              items:
              - key: ca.crt
                path: ca.crt
                mode: 0o600

status: {}
