apiVersion: v1
stringData:
  CLUSTERNAME: cluster-example
  TIER1_PATH: /data
  TIER1_PASSWORD: thisismypassword
  SOURCE_SLOT: klio
  SOURCE_DSN: host=cluster-example-rw user=streaming_replica replication=yes dbname=replication sslcert=/certificates/tls.crt sslkey=/certificates/tls.key sslrootcert=/certificates/ca.crt
kind: Secret
metadata:
  creationTimestamp: null
  name: klio
