apiVersion: v1
stringData:
  CLUSTERNAME: cluster-example
  TIER1_PATH: /data
  TIER1_PASSWORD: thisismypassword
  SOURCE_SLOT: klio
  SOURCE_DSN: host=cluster-example-rw user=streaming_replica replication=yes dbname=replication sslcert=/certificates/tls.crt sslkey=/certificates/tls.key sslrootcert=/certificates/ca.crt
  SERVER_GENERATE_CERTIFICATES: "true"
  SERVER_TLS_CERT_PATH: /data/kopia-tls.crt
  SERVER_TLS_KEY_PATH: /data/kopia-tls.key
  SERVER_PORT: "51515"
kind: Secret
metadata:
  creationTimestamp: null
  name: klio
