apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: klio-api
  name: klio-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klio-api
  strategy: {}
  template:
    metadata:
      labels:
        app: klio-api
    spec:
      serviceAccountName: klio-api
      volumes:
        - name: klio-server-tls
          secret:
            defaultMode: 420
            secretName: server-sample-tls
        - name: klio-api-tls
          secret:
            defaultMode: 420
            secretName: klio-api-tls
        - name: klio-client-tls
          secret:
            defaultMode: 420
            secretName: client-sample-tls
        - emptyDir: {}
          name: scratch-data
      containers:
      - args:
          - server
          - api-server
        env:
          - name: CLIENT_BASE_HOSTNAME
            value: klio
          - name: CLIENT_BASE_URL
            value: https://server-sample.default:51515
          # Tier 2 support, if needed
          #- name: CLIENT_BASE_TIER2_URL
          #  value: https://server-sample.default:51516
          - name: CLIENT_BASE_SERVER_CERT_PATH
            value: /certs/tls.crt
          - name: CLIENT_BASE_API_SERVER_CERTFILE
            value: /klio-api/certs/tls.crt
          - name: CLIENT_BASE_API_SERVER_KEYFILE
            value: /klio-api/certs/tls.key
          - name: CLIENT_BASE_CLIENT_CERT_PATH
            value: /client-certs/tls.crt
          - name: CLIENT_BASE_CLIENT_KEY_PATH
            value: /client-certs/tls.key
          - name: TMPDIR
            value: /tmp
        image: registry.dev:5000/klio-testing:dev
        imagePullPolicy: Always
        name: api-server
        resources: {}
        securityContext:
          runAsNonRoot: true
        volumeMounts:
          - mountPath: /certs
            name: klio-server-tls
          - mountPath: /client-certs
            name: klio-client-tls
          - mountPath: /klio-api/certs
            name: klio-api-tls
          - mountPath: /tmp
            name: scratch-data
