apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: klio-api
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: klio-api
subjects:
  - kind: ServiceAccount
    name: klio-api
    namespace: default
