---
# Apply these steps to set up RustFS for Tier 2 testing
# kubectl apply -k operator/config/samples/rustfs
# kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=rustfs --timeout=120s
# kubectl apply -f operator/config/samples/rustfs/rustfs-job-create-bucket.yaml
#
# Then apply the Klio Server with Tier 2 sample
apiVersion: klio.cnpg.io/v1alpha1
kind: Server
metadata:
  name: server-ro
  annotations:
    klio.cnpg.io/pprof: "true"
spec:
  mode: read-only
  tier2:
    cache:
      pvcTemplate:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
    encryptionKeyFile:
      fileReference:
        volume:
          secret:
            secretName: server-ro-encryption
        path: encryption-key
    identityFile:
      fileReference:
        volume:
          secret:
            secretName: server-ro-encryption
        path: secret-key
    s3:
      prefix: klio
      bucketName: klio-bucket
      endpoint: https://rustfs:9000
      region: us-east-1
      accessKeyId:
        name: rustfs-secret
        key: RUSTFS_ACCESS_KEY
      secretAccessKey:
        name: rustfs-secret
        key: RUSTFS_SECRET_KEY
      customCaBundle:
        name: rustfs-tls
        key: tls.crt

  tlsSecretName: server-ro-tls
  caSecretName: server-ro-ca

  image: registry.dev:5000/klio-testing:dev
  imagePullPolicy: Always
---
apiVersion: v1
stringData:
  secret-key: AGE-SECRET-KEY-1P7TWJ8H837DPVLSRVHAP0ZCZVHXJRTUS7S0A5VZAR49URW0Z9Q0SFW4HVM
  public-key: age16y2zu5qptkzateyuarcahs0am75qjpu0xd2ty2dvm5jusnfzxg0scjh5uu
  encryption-key: |
    -----BEGIN AGE ENCRYPTED FILE-----
    YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMzJERW1QTUhjNGdlNmdi
    WmFLZ3FLL1lZclduUWEvZkJncGdJZmtVd1FzCmZwSHVTcWNMRFN6a2xpY0NHNVRv
    MlltSlNRY1B4bmNoOUxuZzZ5RENSSmsKLS0tIGNYUUNzSGVqNUZhS3VodnZ1cXNP
    T3JHS3JRSUNkR1RyeEROYnZYNnNSV00KUd3HyxvvqCyW6hC1sWNDn/xeptHsoz/e
    hxCgWoSJvfSfNk174njMwEeW+ic=
    -----END AGE ENCRYPTED FILE-----
kind: Secret
metadata:
  name: server-ro-encryption
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-ro-tls
spec:
  secretName: server-ro-tls
  commonName: server-ro
  dnsNames:
    - server-ro
    - server-ro.default
    - server-ro.default.svc

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-ro-ca
spec:
  commonName: server-ro
  secretName: server-ro-ca

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: true
  usages:
    - cert sign

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: server-ro-ca
spec:
  ca:
    secretName: server-ro-ca
