apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: pluginconfiguration-sample
spec:
  serverAddress: server-sample.default
  clusterName: cluster-example
  clientSecretName: cluster-example-klio-user
  serverSecretName: server-sample-tls
  tier1:
    retention:
      latest: 10
  tier2:
    enableBackup: true
    enableRecovery: true
    retention:
      latest: 10
  walPrefetch:
    count: 2
    maxConcurrentDownloads: 4
