apiVersion: klio.cnpg.io/v1alpha1
kind: Server
metadata:
  name: server-sample
  annotations:
    klio.cnpg.io/pprof: "true"
spec:
  baseConfiguration:
    adminUser:
      name: server-sample-adm

  cacheConfiguration:
    pvcTemplate:
      resources:
        requests:
          storage: 1Gi
      accessModes:
      - ReadWriteOnce

  dataConfiguration:
    pvcTemplate:
      resources:
        requests:
          storage: 1Gi
      accessModes:
      - ReadWriteOnce


  password:
    name: server-sample-encryption
    key: password

  tlsSecretName: server-sample-tls
  users:
    name: server-sample-users

  image: registry.dev:5000/klio-testing:dev
  imagePullPolicy: Always

  template:
    spec:
      containers:
        - name: base
          env: &otel-env-vars
            - name: OTEL_SERVICE_NAME
              value: "klio-base"
            - name: OTEL_RESOURCE_DETECTORS
              value: "telemetry.sdk,host,os.type,process.executable.name"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "https://simplest-collector:4317"
            - name: OTEL_EXPORTER_OTLP_TRACES_COMPRESSION
              value: "gzip"
            - name: OTEL_EXPORTER_OTLP_TRACES_TIMEOUT
              value: "10000"
            - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
              value: "false"
            - name: OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE
              value: "/otel/ca.crt"
            - name: OTEL_EXPORTER_OTLP_TRACES_CLIENT_CERTIFICATE
              value: "/otel/tls.crt"
            - name: OTEL_EXPORTER_OTLP_TRACES_CLIENT_KEY
              value: "/otel/tls.key"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "60000"
            - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: "https://simplest-collector:4317"
            - name: OTEL_EXPORTER_OTLP_METRICS_TIMEOUT
              value: "60000"
            - name: OTEL_EXPORTER_OTLP_METRICS_INSECURE
              value: "false"
            - name: OTEL_EXPORTER_OTLP_METRICS_CERTIFICATE
              value: "/otel/ca.crt"
            - name: OTEL_EXPORTER_OTLP_METRICS_CLIENT_CERTIFICATE
              value: "/otel/tls.crt"
            - name: OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEY
              value: "/otel/tls.key"
          volumeMounts:
            - mountPath: /otel
              name: otel
        - name: wal
          env: *otel-env-vars
          volumeMounts:
            - mountPath: /otel
              name: otel
      volumes:
        - name: otel
          projected:
            sources:
              - secret:
                  name: simplest-collector-tls
                  items:
                    - key: ca.crt
                      path: ca.crt
              - secret:
                  name: otel-client-cert
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
---
apiVersion: v1
data:
  htpasswd: a2xpb0BjbHVzdGVyLWV4YW1wbGU6JDJ5JDEwJE5zRHl1NG1Ha1pDTE93eGkvWjdkek9aOFVPTzBBQXBCY28ua3I2LlhyVFJGRERxRFpaMkFpCg==
kind: Secret
metadata:
  name: server-sample-users
---
apiVersion: v1
data:
  password: cGlwcG9waXBwbw==
  username: a29waWE=
kind: Secret
metadata:
  name: server-sample-adm
---
apiVersion: v1
data:
  password: dGhpc3Bhc3N3b3Jk
kind: Secret
metadata:
  name: server-sample-encryption
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# Certificate for the Klio server.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-sample
spec:
  secretName: server-sample-tls
  commonName: server-sample
  dnsNames:
    - server-sample
    - server-sample.default
    - server-sample.default.svc

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
# Certificate for the OpenTelemetry client of the Klio server.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-client-cert
spec:
  secretName: otel-client-cert
  commonName: server-sample
  dnsNames:
    - server-sample
    - server-sample.default
    - server-sample.default.svc

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
# Certificate for the OpenTelemetry Collector.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: simplest-collector-cert
spec:
  secretName: simplest-collector-tls     # cert-manager will create this Secret
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
    - simplest-collector.default.svc.cluster.local
    - simplest-collector.default.svc
    - simplest-collector
---
# OpenTelemetry Collector instance
# This is a very basic configuration that receives OTLP data over gRPC and HTTP,
# processes it with a memory limiter and batch processor, and exports it to
# a debug exporter and Prometheus exporter.
# OpenTelemetry Operator is required to run this:
#   kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            tls:
              cert_file: /etc/otel/certs/tls.crt
              key_file: /etc/otel/certs/tls.key
          http:
            endpoint: 0.0.0.0:4318
            tls:
              cert_file: /etc/otel/certs/tls.crt
              key_file: /etc/otel/certs/tls.key
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug:
        verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:9464"
      otlp:
        endpoint: jaeger:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ debug, otlp ]
        metrics:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ debug, prometheus ]
        logs:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ debug ]
  volumeMounts:
    - name: otel-tls
      mountPath: /etc/otel/certs
      readOnly: true
  volumes:
    - name: otel-tls
      secret:
        secretName: simplest-collector-tls
