---
# Apply these steps to set up RustFS for Tier 2 testing
# kubectl apply -k operator/config/samples/rustfs
# kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=rustfs --timeout=120s
# kubectl apply -f operator/config/samples/rustfs/rustfs-job-create-bucket.yaml
#
# Then apply the Klio Server with Tier 2 sample
apiVersion: klio.cnpg.io/v1alpha1
kind: Server
metadata:
  name: server-ro
  annotations:
    klio.cnpg.io/pprof: "true"
spec:
  readOnly: true
  tier2:
    cache:
      pvcTemplate:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
    encryptionKey:
      name: server-ro-encryption
      key: password
    s3:
      prefix: klio
      bucketName: klio-bucket
      endpoint: https://rustfs:9000
      region: us-east-1
      accessKeyId:
        name: rustfs-secret
        key: RUSTFS_ACCESS_KEY
      secretAccessKey:
        name: rustfs-secret
        key: RUSTFS_SECRET_KEY
      customCaBundle:
        name: rustfs-tls
        key: tls.crt

  tlsSecretName: server-ro-tls
  caSecretName: server-ro-ca

  image: registry.dev:5000/klio-testing:dev
  imagePullPolicy: Always
---
apiVersion: v1
data:
  password: dGhpc3Bhc3N3b3Jk
kind: Secret
metadata:
  name: server-ro-encryption
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-ro-tls
spec:
  secretName: server-ro-tls
  commonName: server-ro
  dnsNames:
    - server-ro
    - server-ro.default
    - server-ro.default.svc

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-ro-ca
spec:
  commonName: server-ro
  secretName: server-ro-ca

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: true
  usages:
    - cert sign

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: server-ro-ca
spec:
  ca:
    secretName: server-ro-ca
