apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: pluginconfiguration-sample
spec:
  serverAddress: server-sample.default
  clusterName: cluster-example
  clientTlsIdentity:
    volume:
      secret:
        secretName: cluster-example-klio-user
    certPath: tls.crt
    keyPath: tls.key
  serverCa:
    volume:
      secret:
        secretName: server-sample-server-ca
        items:
        - key: ca.crt
          path: ca.crt
    path: ca.crt
  tier1:
    retention:
      keepLatest: 10
      keepHourly: 48
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 24
      keepAnnual: 1
  tier2:
    enableBackup: true
    enableRecovery: true
    retention:
      keepLatest: 10
      keepHourly: 48
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 24
      keepAnnual: 1
  walPrefetch:
    count: 2
    maxConcurrentDownloads: 4
