name: Cleanup runner's disk
description: Free up disk space on the runner
runs:
  using: composite
  steps:
    - name: Cleanup Disk
      uses: jlumbroso/free-disk-space@3f13feab2962a87273d379ebc36ea159527e6cc9 # v1.3.2
      with:
        android: true
        dotnet: true
        haskell: true
        tool-cache: true
        large-packages: false
        swap-storage: false

    - name: Cleanup docker cache
      shell: bash
      run: |
        echo "-------------Disk info before cleanup----------------"
        df -h
        echo "-----------------------------------------------------"
        docker system prune -a -f
        echo "-------------Disk info after cleanup----------------"
        df -h
        echo "-----------------------------------------------------"
