apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-dc-a
  namespace: dc-a
spec:
  instances: 3
  imagePullPolicy: Always
  
  postgresql:
    pg_hba:
      - local replication all peer

  plugins:
    - name: klio.cnpg.io
      enabled: true
      parameters:
        serverAddress: klioserver-dc-a.dc-a
        clientSecretName: klio-client-dc-a
        serverSecretName: klioserver-dc-a-tls
        pprof: 't'

  storage:
    size: 1Gi

  replica:
    self: cluster-dc-a
    primary: cluster-dc-a
    source: cluster-dc-b

  externalClusters:
    - name: cluster-dc-a
      plugin:
        name: klio.cnpg.io
        parameters:
          serverAddress: klioserver-dc-a.dc-a
          clientSecretName: klio-client-dc-a
          serverSecretName: klioserver-dc-a-tls

    - name: cluster-dc-b
      plugin:
        name: klio.cnpg.io
        parameters:
          serverAddress: klioserver-db-b.dc-b
          clientSecretName: klio-client-dc-b
          serverSecretName: klioserver-dc-b-tls
---
apiVersion: v1
kind: Secret
metadata:
  name: klio-client-dc-b
  namespace: dc-b
data:
  password: ZGNicGFzc3dvcmQ=
  username: a2xpbw==
---
apiVersion: v1
kind: Secret
metadata:
  name: klio-client-dc-a
  namespace: dc-b
data:
  password: ZGNhcGFzc3dvcmQ=
  username: a2xpbw==
