apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-dc-b
  namespace: dc-b
spec:
  instances: 3
  imagePullPolicy: Always

  bootstrap:
    recovery:
      source: cluster-dc-a-recovery

  postgresql:
    pg_hba:
      - local replication all peer

  plugins:
    - name: klio.cnpg.io
      enabled: true
      parameters:
        pluginConfigurationRef: client-config-cluster-dc-b

  storage:
    size: 1Gi

  replica:
    self: cluster-dc-b
    primary: cluster-dc-a
    source: cluster-dc-a

  externalClusters:
  - name: cluster-dc-a
    plugin:
      name: klio.cnpg.io
      parameters:
        pluginConfigurationRef: client-config-external-cluster-dc-a

  - name: cluster-dc-a-recovery
    plugin:
      name: klio.cnpg.io
      parameters:
        pluginConfigurationRef: client-config-external-cluster-dc-a-recovery

  - name: cluster-dc-b
    plugin:
      name: klio.cnpg.io
      parameters:
        pluginConfigurationRef: client-config-cluster-dc-b

---
apiVersion: v1
kind: Secret
metadata:
  name: klio-client-dc-b
  namespace: dc-b
data:
  password: ZGNicGFzc3dvcmQ=
  username: a2xpbw==
---
apiVersion: v1
kind: Secret
metadata:
  name: klio-client-dc-a
  namespace: dc-b
data:
  password: ZGNhcGFzc3dvcmQ=
  username: a2xpbw==
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-external-cluster-dc-a
  namespace: dc-b
spec:
  serverAddress: klioserver-dc-a.dc-a
  clientSecretName: klio-client-dc-a
  serverSecretName: klioserver-dc-a-tls
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-external-cluster-dc-a-recovery
  namespace: dc-b
spec:
  serverAddress: klioserver-dc-a.dc-a
  clientSecretName: klio-client-dc-a
  serverSecretName: klioserver-dc-a-tls
  backupId: backup-20251029102351
  clusterName: cluster-dc-a
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-cluster-dc-b
  namespace: dc-b
spec:
  serverAddress: klioserver-dc-b.dc-b
  clientSecretName: klio-client-dc-b
  serverSecretName: klioserver-dc-b-tls
  pprof: true
