apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-dc-a
  namespace: dc-a
spec:
  instances: 3
  imagePullPolicy: Always
  
  postgresql:
    pg_hba:
      - local replication all peer

  plugins:
    - name: klio.cnpg.io
      enabled: true
      parameters:
        pluginConfigurationRef: client-config-cluster-dc-a

  storage:
    size: 1Gi

  replica:
    self: cluster-dc-a
    primary: cluster-dc-a
    source: cluster-dc-b

  externalClusters:
    - name: cluster-dc-a
      plugin:
        name: klio.cnpg.io
        parameters:
          pluginConfigurationRef: client-config-cluster-dc-a

    - name: cluster-dc-b
      plugin:
        name: klio.cnpg.io
        parameters:
          pluginConfigurationRef: client-config-external-cluster-dc-b
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-cluster-dc-a
  namespace: dc-a
spec:
  serverAddress: klioserver-dc-a.dc-a
  clientSecretName: cluster-dc-a-klio-user
  serverSecretName: klioserver-dc-a-tls
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-external-cluster-dc-b
  namespace: dc-a
spec:
  serverAddress: klioserver-dc-a.dc-b
  clientSecretName: cluster-dc-b-klio-user
  serverSecretName: klioserver-dc-b-tls
---
## Generate client certificate for local cluster in dc-a, using the CA in dc-a.
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: cluster-dc-a-klio-user
#  namespace: dc-a
#spec:
#  commonName: klio@cluster-dc-a
#  secretName: cluster-dc-a-klio-user
#
#  duration: 2160h # 90d
#  renewBefore: 360h # 15d
#
#  isCA: false
#  usages:
#    - client auth
#
#  issuerRef:
#    name: klioserver-dc-a-ca
#    kind: Issuer
#    group: cert-manager.io
#---
# Actual secret generated from the above cert-manager Certificate for client auth in dc-a
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQjIrb3p3WDVxUzFJMThGZVVtTEdkSjc0ZlF3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkxTVRBek1URXpNalF3TkZvWApEVEkyTURFeU9URXpNalF3TkZvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNOdEY2cDhwTlpGb1hCd3ZrN2NuL0xGTnZPRnkKQUQrdWxCMWhhdXBFV1UycEphQ1FSUkppTXB4dmZCZERlS3c1azZJYkZCTVUxZkRaY0lCV0NEcEJUek51N09wZApqVzd1Rk5GV2hSK1d2bXJEb092d0JKalRpTGU3dlVqV245bkpLM2RiRkNKSUJWclN6T3JGR1BSL2ZTTnBXODV1CjhvNDZoRGpRTXVwM0YzK3h4Y21TSjdQamVYcnJ3ekkrdDRyNXRtQ3VsZFhNSGxjUzZsMlVUeEQ4ZENmbjNEbjYKZ2VsM2RES1g3WWlSVmJYU1R2TkZZMnVhNVVBQUVmaFFzWTA3OWdETXJQS1kzYkhvWUU1alY5ZEtTcWVKd21YVgpNUUZXYnRTZ0xWb3Y1UUxubElQZnlQeHFHbWZvcHpaWjZ4Z1YvNVorQXMrWFFyNlhYaDFkL3BoQUlRSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKaFo1d2dseXJmYW5KYlk4N0M2VGxyWXZ3blhVd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBR3VkSFdKQnBxNApZVHIxc3JFaCtyMFZDUEVGaTEyOHlxdFdtSUFQR2svZlo4R2NScHg2ZFRlSy8reVVGUVAwcFVieXlPKytBSC9xCkNNOVlVU1hvanV5dW5NaFdXQmdMTDczNlNBVDBiOFNoY2F4djRIcDJ6N0R2WFNFdUsrTzZlbTFLWmI1Z0pWZCsKVHF4R0Y5ZHNCZE5FUHBlR25JVXZjR1d1aGIvWEVnYlA4SVJ1ZXcvLzVLWkNmT3FYczFobWFhMVRkTjZmZU9hYgpCbnZHUmtmZFlBS1lkTkFGckt1enV3N1MzdFRNMkNhZDVzRlMwLy81MHNRMHY1QnNFamVkRkdMcDFNZ0xIVlpLCitCRGo3SHVPOGpJa0ExMjFkUy9jejd1VW1RMkZ2R2xTY0VhUVJuNXNGUldxMGJQYXVaL2dtenQzNjMyektCQXMKc3FuZ0pTcE1WR009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lVRDZvaGJuM1M5Y3Q1SENMVUEvVzJrZ0xDWFpvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkxTVRBek1URXpNalF3TkZvWApEVEkyTURFeU9URXpNalF3TkZvd0hERWFNQmdHQTFVRUF3d1JhMnhwYjBCamJIVnpkR1Z5TFdSakxXRXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRG5HWEUwUzgzemIxQ1AwVURDZzlzajUvamkKQmpBREUvNk9tR3VMTW9PS0FQcUNDMG9HRHFNck9IUnh2dW1uMCtDbnVHYjNFWG5tOUpNOEp2dUR0VEthQjNJMQpXM1lCZjdBaWtaZ3VpOEo5ODY3cGQ2K0t4RGpRT0REclQ2ejhwc1c1ZkVaWnJ0NE9rZytIUERjYjJLejRpYWJ6CnlQZkpoRDRLV2tCcXppcGRXOEFhcy9SdlptVmw1N21ub1BLYUQ0ZUZYUC9nL0RuLzJzWTB1QWlkSEJlREoxdE0Kb25ZL0xWR3ZINEZadm1JRUNsVk4zdkQwV0JHcXk4V1VFMlZ4d29TQkNoRU4wOWp6VkcwMnBSNkYxai9tSjRYTAo0TEtnSG9FTFhZSGNEUVBmWHEyay9LKy9SdmZlNW9zWGNWdVNEd1o4NG1xMXNuVE1LYVUrcTRsTTZaSjlBZ01CCkFBR2pSakJFTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGoKQkJnd0ZvQVVoWjV3Z2x5cmZhbkpiWTg3QzZUbHJZdnduWFV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQU1rKwpneVgvaC92ejVhZUJCV3htMzVleW9mbklLVTNqRk1vWmxaOSs3Y216eXlxbk1FMGlYalJ2VGo4czNKc2ZJOHAzCkY4V0RmV25VVXlhaUVveWl3ZmlaV2REaTJ4aXdMaytpQ2ZHbUNQTU1jbG9JenllcFJpR2syN1VrZ0JSUU1RQ1UKb3lEWEJWZksxZ013MFp0TTV2cnpwOTk0WldVbS9XK2ZlY2dvdnFjSytUU29VOHpseDBrTmdCZUJjcU4zWnBQQgoyMkpiY0xhdkRvT3NQQlk0M3c2TisrRFpyZCtGZEQ2aXBsNTh6UFpiSXJQZFJjbkVvOGVKVllMS0Z0UlZ2N211CmpQZ2s5RzR5UFh6Y1ZSTTA0L1VYNzUyc3gvY3FNMFRHaHAwWjR1Mzloc1B3akR3YVNLYUZudU5EWFRGSDBxb2cKelZoZkZCdC9sWGVXSFlPOFcxMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBNXhseE5Fdk44MjlRajlGQXdvUGJJK2Y0NGdZd0F4UCtqcGhyaXpLRGlnRDZnZ3RLCkJnNmpLemgwY2I3cHA5UGdwN2htOXhGNTV2U1RQQ2I3ZzdVeW1nZHlOVnQyQVgrd0lwR1lMb3ZDZmZPdTZYZXYKaXNRNDBEZ3c2MCtzL0tiRnVYeEdXYTdlRHBJUGh6dzNHOWlzK0ltbTg4ajN5WVErQ2xwQWFzNHFYVnZBR3JQMApiMlpsWmVlNXA2RHltZytIaFZ6LzRQdzUvOXJHTkxnSW5Sd1hneWRiVEtKMlB5MVJyeCtCV2I1aUJBcFZUZDd3CjlGZ1Jxc3ZGbEJObGNjS0VnUW9SRGRQWTgxUnROcVVlaGRZLzVpZUZ5K0N5b0I2QkMxMkIzQTBEMzE2dHBQeXYKdjBiMzN1YUxGM0Zia2c4R2ZPSnF0YkowekNtbFBxdUpUT21TZlFJREFRQUJBb0lCQUFKdWJKZjV3akZ3OXQ2RQplNU53VXJKbWd1SlI0Vmh1OGVzckpGcUREZ282SjJpTjJOb0dkbVlDZ29zZDBKU0E4S2lqRW9ZLzYxSG9PZEpVCnNLbTZrczAzRGRjTTNzbDJQL0tsS0g0NDN6TjNDRnlSYzBuWTlhWVBLVWlZZm4vciswR1AwcWVuNU5NdmF6Vm4KaDBibU9TK21OeGp5Z05UZ2JNeXNGV2hxUWR6WWtLYmV2K3pPSVdaTW5lWnMzRkkzN2kzYnRjdlJpczlpbDBWWgpwUkE0M09abUFoUlcxV2hUWGI1N1lnOXZUVk8rZlk1b1hIN1I4VlB5ajBXMkZXYmJJSlRubDh2L2pma2hYbWYyCnRYck1MUUt6NjB1REJkOVNYWlI0eEtxU1FRQ1pmUFhscVRLcUhtYUR2QmIrS0VpRWRESURuZFpMbCt6VVpVbmQKekY0dTNyRUNnWUVBN29EYW14NVl6YVpob29aaHVSV0tXZVk0ZkxOQU5WT0N5SjRRYVNTZkZBZ2REbmFhTGJkSApHY09ZdlU4ZlI4dnV0ODluNUVFeGlRR0Iyb2hQUmExYVhZV0RTQ1NPTnR1cjZESGRsMVlxZXFqYmVqWjV6MDA1Cm85bjhWZ2hHSThMdWJOWitEcmJ5ZmpjQm9wUERLcDNaNTN3a0tha1pod1VOa2g2WGRzUGt5UFVDZ1lFQStBMksKVjNDWGN0VGQweXRjUjJsU3VMN3RzTlg4WTJDamZTVngwYVN5emVzenROb21GSDMxYWtrSzdWSlVrQldsYjM0ZgoxWDh4bmcwRkppcER6YnhwMktFOVlha1lXT0dDY3hMWWNVY3drMWpNVXhUUjNGTzczNnFvOXB1T21VQVYwc04vCkpwTGpCaU1jTU5TSFNpTG1zNGMzdUJRTWdIYWJrUlFxUXk0bXpta0NnWUFXL1NxVkd4YTZNOWhqWHdxYVdYNHQKYmloeHRLRnl3bXJ2eFhTVmZlY3JlaUM2M1NtOVVGWTFJSXBmYlBuNTVLbE01RndDUDFwejkwWTU5enVVM3NIQQpFL2QwZzdtRmhpVUt5NHV0WTZ2U2lPWW00SXRiTlBsaVZzZWd6MGxiZHhXZVBncUdocEhYSXB3d3ZJZHFXeTYrCnhsT0NCSCttYVJGR3pWWVNKNDJzNVFLQmdFeURLTFAxOTlFazFkT0lJV3Vwa2ltSVF4cnp0bWtVNnZqMEx0cUMKbWVDb2R3ZUc3bzRObUVDVGpUcE0xZWFudHFMZ1hZTm1PM0RNQlZXVFhkeTlERTBVMXpFamptNEVDVS9qZFQzagp2cGtFbituVWx6TUY1UUtGeXA1ZXR5cVFPT3NOQUZCdXFIWkJLRFhycUZ0MnpvQjc2ZlR1d2poeDNXUnZ1dVdECis5WlpBb0dBUmtETnA4clVUL3NJS1IrSDl2cUJSd3h6M3RaenNtZkFMUGJCbi9IcTFUU1ZYVUZRQ0dxcE50R2wKMkp4Z0k0UDYxVEdDRElwN0RBWkVDTWNmSXFQcm5tajIxY3IzQ1ZEdXVFMUU3empJNFR2a282YjNFa2JFMFB4TAppVWl1NnRLaVNvWHl0Tm5nYWxGeVN6ZHM1VnZJSUJHSGpGQmtIdG4vdGRNbXZwRDR5Z0E9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: cluster-dc-a-klio-user
  namespace: dc-a
type: kubernetes.io/tls
---
## Generate client certificate for external cluster in dc-b, using the CA in dc-a. The generated certificate
## secret needs to be copied to dc-b namespace to be used by the external cluster configuration.
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: cluster-dc-b-klio-user
#  namespace: dc-a
#spec:
#  commonName: klio@cluster-dc-a
#  secretName: cluster-dc-b-klio-user
#
#  duration: 2160h # 90d
#  renewBefore: 360h # 15d
#
#  isCA: false
#  usages:
#    - client auth
#
#  issuerRef:
#    name: klioserver-dc-a-ca
#    kind: Issuer
#    group: cert-manager.io
#---
# Actual secret generated by the cluster-dc-a-klio-user cert-manager Certificate in dc-b.
# Copied here.
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQnVkNzJLaWpvekFmaFRVcVFFZ3EwbkZBSlNZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1CNFhEVEkxTVRBek1URXpOVGN6TTFvWApEVEkyTURFeU9URXpOVGN6TTFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXh3S04wOFRFTEh3cFlDQzVGK3BLS3lCMHk5UmwKNi9IbWI4UXF1N2RRUnFXMDJOOUxOeXJIZmc1SlhxcFhmLzJtbVlYc1U4YUp3ZWVMMUpYV3J2NTJIN1RtemRBUwo4WVJFZWtjdDZtUk1hVFhHbGFHU1pneWswbzZmRm9iaEEzMmZEYXg1ZUsxTUh0bi9mblZZWDJUcFZJYTBkQkUvCmUxazdnS0VYc1NLNnRHa3pRZ2VxR0ZQUFVxN2xjbGplYXFZQXorSmhwSFhDbVRRc3VpdFFTVUlHcDF5QTJsTUYKaUZqVUJVcmMrYkJXUmlEM1FPWVorVlhISVVoaUpxdVlrdHdjNmg2eFV6NUJoQzN0T1hVNDA5R3E5dGx6b0tmaQpMbno2b0Q2emp3ZW1DeTdFblFEWUw2aE9TZGxBKzVJS3hhdmVKTWdQTmdubTdTRVFBNXIwZzRkUFN3SURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKWUJyY1VrL0NKUW4vbStoNnBsQlVhdjkzOXFNd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDVm44bUk4T1U2OQpoc085SWV4bW91RStrYjlLQXRqRC9MbnJrQmZpMHpFWTJHelRPWWUxQlJsaTFDaVZKcXZUWW9EQmk1bDYrbEY0Clp4QWpVRjM5TmJMN1JJcGJiTml2L0o2alBxSXhNbUQ3eDJuTmVlRW9BcTdDRHAzQmhsL0s4SmZYYnpXMzgxbi8Ka01EMXdqeFdVaDIrNGV6eW1US1JQRFNuLzUxTy9JbzZDQmhGbTJBZ053TFY3MkozR1FJZmtVYU5jR3oyZkJPSQpaV01CR2RjaXJ4cjVTVkdzSVc2ZW4zSnE0RTFIcTZvaGFtSUNxRHgvMnloTjhta1F4U3k1MFNOck9QOEhGZCtLCjBndGhvN29IK0lMbmNjWVhxMTZtczFyd0NSTnZvWm5Eay9scGNVSGlvWDl3NjU3c0sxdG1nUzVCSktRZmZVNnkKRDBsZjhFODVtamc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lVVjhTRSszMk84cEpnNVRqTnNRSk5XN3hRVXJBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1CNFhEVEkxTVRBek1URTBNRGN3T1ZvWApEVEkyTURFeU9URTBNRGN3T1Zvd0hERWFNQmdHQTFVRUF3d1JhMnhwYjBCamJIVnpkR1Z5TFdSakxXSXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ25QeDhna0gvWEFiOHlwN0ZwRjFaQ0NpTi8KNk9wdU9JVlVBSFd0MzlxTTlPME02U2JOZ2M2TVhFUHk4ZXFBTzlSSFNnVlRSQkQ1SFVrNk41UXBuMWRUNGJVVApzL0RzdE9FUjNGUzdpanQ5Y2QzUS8zRnRCQXRtUnRLU0lKWVIwSzBXWERBcUZsUFJuVkVQbng1dVNnTjU2UWh5CnlYNHlHMkpGYmRVcTUyYnE1WlFaRGhQelBTNlJVWlNBNCtwditvay9wWjZQRVc3bUVlc1NXb3VRVlNtcG1LKysKSURuZEc2eWRVaXZKU3BCK0U1aGpUU3pRUkNlVjlRWkJDMXhKa1A1Z2JONUlFelNkeTR1Sk53bXRESEJzTEI3dgpMSFIvcE4xOWVWaWdNbk1xWDdST3JEYUxRbGxUUVR4UTBaSTZXMFYxbTlCZUVpeDBIYmJLVHNXVi9TbHBBZ01CCkFBR2pSakJFTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGoKQkJnd0ZvQVVZQnJjVWsvQ0pRbi9tK2g2cGxCVWF2OTM5cU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQU1FRAo0aEhXWmxsQmJTRnVxenZGY2VUdDhUS3VES2dCZUxqRjR2WFFqMEtWVkx4VFNiMFNmcXdSL1I4L05oVDIwcFhjCm5NbStlT0RaQkljanloRXJWbTlZSVN4TEVJNitCSG04VWFLeGlDc1JmNjJzS3c1OEM4bWtZRVlBaU5TYkZZMlgKeXNHcWMrNkluMVRJTUdwRWlHdmJIRlQ2WjArNGpOM2xsVEdqM0xVRnM2dmw4eU1Na0tIOThrQzJZdmJ3bXdBOQpaTHhZbi9rYjUxMmVaWUlJZzRXNmdOVEhQaE4wN3M3cTM2TTYwTXRqTHlBMUlMblpqZ1RKdjNiNUR2dEF3TzJzCjdUZ1F0WTN0RmR1eHhXVjE0VndjemVQSmd1R0NaaEV2K1lXc0Y0eWlOVE8xNG0vdXRlRGlYZmtFVnJ5RUd0ekUKbFNzaFYzdThmZEtXejVuTTcwVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcHo4ZklKQi8xd0cvTXFleGFSZFdRZ29qZitqcWJqaUZWQUIxcmQvYWpQVHRET2ttCnpZSE9qRnhEOHZIcWdEdlVSMG9GVTBRUStSMUpPamVVS1o5WFUrRzFFN1B3N0xUaEVkeFV1NG83ZlhIZDBQOXgKYlFRTFprYlNraUNXRWRDdEZsd3dLaFpUMFoxUkQ1OGVia29EZWVrSWNzbCtNaHRpUlczVkt1ZG02dVdVR1E0VAo4ejB1a1ZHVWdPUHFiL3FKUDZXZWp4RnU1aEhyRWxxTGtGVXBxWml2dmlBNTNSdXNuVklyeVVxUWZoT1lZMDBzCjBFUW5sZlVHUVF0Y1NaRCtZR3plU0JNMG5jdUxpVGNKclF4d2JDd2U3eXgwZjZUZGZYbFlvREp6S2wrMFRxdzIKaTBKWlUwRThVTkdTT2x0RmRadlFYaElzZEIyMnlrN0ZsZjBwYVFJREFRQUJBb0lCQUJJN0owRjlmdklKRnJhRwo0U2Y3aTBPWHAxY0NKTXZ2RFZtaTB6RW8vY0h2MFFkZlF3T1Q2dGdTRnJZYytOc1Jxb282MzJtOE9iMXVHOVZrCnlabmY3TDBRRlpVWVFHTU5OSnVsMFBiQWtzdVI1Z1FxVkVyMTdlZ3dRRFA5cVY0M3lTWnUxakZBVGRMRHUxcGcKbGdpZnVORkpQY3FGZkdRcDZBUjVmSXM0dmxkTWtrRk1iZTRaWHA0RmZUYzE2dTYra1pQSndnd2x6eXhCSWUyRQpLcS9nblJZNjE5aGxrSkZsZ2hzMVFSVE5ZSXl3V2ZlMW1UYm41OGFCUlUvcGV4b05aSG15ejFIems0MTM5aTJyCmtadUJRV2o4YjhmYlBEM3FRdkREbGhUb2VhUUY1dTN5NkIrc05HY2JEVXhvdU42c2JwUmpTdVVDRURTdWxkb1UKUGpXZG82RUNnWUVBeXNWZmNLQ2M3OTZwcUZ1NG1SdTVPZlU0NDBOUHNpanpFakxMYU1NNFluV1FHQzhrZkZONQpPSXQ3SXFGVTRxY3h6KzZaNUlLTnJ0MzlMbWZ3R00yZUVkcUVMd05CNWk1MEpEWVpHbHhmVE8xY3dwTVNBM3BYCm1KM0E5b0g1OHg3N045Y0RZMDZ5SEVTdTBkYWdNWm1iUjZVOWtyMHFlZ3pTUEhTSzdMV2JYdHNDZ1lFQTB5WnYKVDRYM09ZOC9kUUhMeDBXVXVHcHBwK0NMdVRtR3NEYkd2bElDekxFR3AzOEZ2VW5HY3VXM0Q2MElId0JxM0lWWAp6TjlObUppdTVDSDNDT0JFWkdLc2NsTEN4b09Sd1NOM1p5MlpkL3ZnaUtQelRwUWVncS9tQVgyOElyYlhETkF0CkRRMWt6ZjdUQytUb0ZoMURZdnNEOXM4cktrYzdDL0VSUFNWVklnc0NnWUVBd2FNMG5rQ3pQaHBiMkV3bkFBZksKbmYrQklQNXh5QWgwLzhjRUd2cDdDUU9ONUpwNGRFWGV1Rkh5K0VJcTV2dVZoU1V0VDF3aFk0SFl1dzFFNnRySQovZkc0VTVEL3lJcEtIUjZRWUcwZ0VUMkhYTVRINmd4V1JJYzU4KzV4dkd1MHFrR3BtWmRZWGNoMVRpeHc5SXpsCkRjbE9BS2luUE1DcnNGSDNMVS9NblFzQ2dZRUFvTTFtZTlOMFFidWNBZ25LSFFvYWhvOVR3MnU0UE9sWWI1NW4Kb00xb0lHYTR3SnAxem4vK3g4VzFzaFIrV00zQ2xBcGdvVDkySXI0MGdyeHpHNmxmckd1UkZNZCtXaHdjeGsreQpRVHR5NHZOSlBnWk41d3ZhYUlCNDA2M2p0elF6ZGlpY0JwS3FzRTVlZjNKbVpXRUh6cnVIZTFDdWVOWWlXNmZOCkR4bjlTWjBDZ1lCcCtnYW9kS3gwTGdGTzdvVTBSZDc1Ym9WOXJMOFVmMU04ZndIV0N1ODgvT081Skh1cVdLbFcKNkdZSHlDNEFVaU5JbEp3aXllNGlOZDR4Skw4bG5haldCaW9zakl6ZndPT29xdkYxZ2lUVjR2RmJIVW9CTHlseApScUhkZGtRWXhoWDFoTUlBbkNhUEZmTHQ4M2lubnRVSzRrUlVsTjl2MTg3RkJTMWw1RCttSVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: cluster-dc-b-klio-user
  namespace: dc-a
type: kubernetes.io/tls
