apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-dc-a
  namespace: dc-a
spec:
  instances: 3
  imagePullPolicy: Always

  postgresql:
    pg_hba:
      - local replication all peer map=local

  plugins:
    - name: klio.cnpg.io
      enabled: true
      parameters:
        pluginConfigurationRef: client-config-cluster-dc-a

  storage:
    size: 1Gi

  replica:
    self: cluster-dc-a
    primary: cluster-dc-a
    source: cluster-dc-b

  externalClusters:
    - name: cluster-dc-a
      plugin:
        name: klio.cnpg.io
        parameters:
          pluginConfigurationRef: client-config-cluster-dc-a

    - name: cluster-dc-b
      plugin:
        name: klio.cnpg.io
        parameters:
          pluginConfigurationRef: client-config-external-cluster-dc-b
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-cluster-dc-a
  namespace: dc-a
spec:
  serverAddress: klioserver-dc-a.dc-a
  clientSecretName: cluster-dc-a-klio-user
  serverSecretName: klioserver-dc-a-tls
  clusterName: cluster-dc-a
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-external-cluster-dc-b
  namespace: dc-a
spec:
  serverAddress: klioserver-dc-a.dc-b
  clientSecretName: cluster-dc-b-klio-user-for-dc-a
  serverSecretName: klioserver-dc-b-tls
  clusterName: cluster-dc-b
---
## Generate client certificate for local cluster in dc-a, using the CA in dc-a.
## Commented out to use a well-known certificate defined below.
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: cluster-dc-a-klio-user
#  namespace: dc-a
#spec:
#  commonName: klio@cluster-dc-a
#  secretName: cluster-dc-a-klio-user
#
#  duration: 87600h # 10y
#  renewBefore: 78840h # 9y
#
#  isCA: false
#  usages:
#    - client auth
#
#  issuerRef:
#    name: klioserver-dc-a-ca
#    kind: Issuer
#    group: cert-manager.io
---
# Actual secret generated from the above cert-manager Certificate for client auth in dc-a
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQ3lFOWRlcE1LeWl1dUZtUDBVTWM1SkFhVkxJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkyTURJeU56RXpNekExTjFvWApEVE0yTURJeU5URXpNekExTjFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXFiK0p6a1RWdDlWUFBMMjRTY1l3Tmw1azJsUFoKY2JvcWk5bTN0cnZWd0tmdHZJMGliSlkwSnY4WmV5c094T0JoakpRN0crWkR6YzY2WHYrQ2o4aVhtY1NIQXVmWApXbjdNbmozNjlsYzk1bFJvQ3ZPb2JrK0pWaldGZmErREN4MVBiMGczTlFJYlRiNXE4cXhOVUp0QnVFYzFKNmNmCk1HcUZvRkhqKzd4SlM5SXBXc3p3SjdWWmFDQkpkY2t6bTVLZzBqNXp5UUNXbGU2RXltNGZKTU85V1pxQlB5bDcKaWNadjhqOEltUmUrdTdqK1NZd2NQdkZxMXk1VU1SZGlpUUR0eURaRmE0TVF0S3RqWUxLZWN0YWNGdFYydUhQTgpsdW9mNTdwZnJNdTRBM3FsRC9GdUw0YURVdGhUMjFBRm80L3NOL1dFaDYvLzJtdHVKU0pvb0FvamZRSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKa2JyalU0L3ZPYlNLYkU0d2FkcmZNUnZ0WEVNd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEVjRMSGpJVm5YVgoxOUcxRGpHMWNqSFJvNXFnTmFDdllOVmd6T2NTaXEzY0ZhdFMzYkFLMFBWSDNCN1p1RzJycHppMkhkRkkwUCtqCkN0dGNCakFBVG1wVWJaay9hcm5Mc1NuajkvMW9VTVpXRXUwTUp2YklLcUxVMVo2VEUxRm5Id0o2UE5uM1J0MDYKcEcyR1R1UmJoSHpjSFEyVjBPU3YzZklRVTJTREVvWk5KazdpYnJSbjdIVUlvSVJ3SlY2ekd2OVdrZjdtSUxmQwpLZVF0VlgvTGU1OTJYNVlpZG5ZSCtWT05hSE40b1hGbmdFWHlqVjhna3NRS3V2TUZwUEN0WXc2UU5sOEZZQzAzCjIxRjJRYU1FdmJTUW1uZ1Z1ODFMNXR4dEI4djIrVEZDNUZ3ODBiMmNhaFBXYkt6WlYzMVBvODZzUUtSMW9sR2oKRlpOVzBXQnl0N3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lVYVBKdFNrSWlwdTNLUzZYZExqaHZrNkptK0trd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkyTURJeU56RTBORGd5TWxvWApEVE0yTURJeU5URTBORGd5TWxvd0hERWFNQmdHQTFVRUF3d1JhMnhwYjBCamJIVnpkR1Z5TFdSakxXRXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGdVUWpSR0ZtN2dqdUtob1R5RkdSeUh3ZXIKdURBY3RMaCtzNUlKMXYxVWE5b291YVQ2amcxaVRKYWxhMng5R01MTzN1eEpyTUZBRWxLazFKMlM3YnQxckt1SQpNTFFTaElhcklCcko4dy9xWG0zV3BYbTROOEJFQ2NudkN3bmJZbkxFWWVPaDA2K3BoTUhDNmtwODdIdmNpVjVUClJTWTFRVmthb0JuQyt2Y1JWaFA0SHk1ejVEbkNSSHgvVXFuV0ZGc0ZIUU95ZFRoejdPc2o5UCt1Vm92aVV2Y0sKSDJXOThGelNldEZPU1JtcjZWVS8vbHI1M3d0TDBLR2ZBcFhWRWRiUWRKN29OTEQrZVhEd0J3WE4yVC9EUzV1awpLOFBCNDdBU2h0emlaVHRnajRZUlB5SytFK1JPYThBak9JK1hPcFI1SGd3ZEtkNXhDaWpIQjNyUS9kNWxBZ01CCkFBR2pSakJFTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGoKQkJnd0ZvQVVrYnJqVTQvdk9iU0tiRTR3YWRyZk1SdnRYRU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUJragpGemN4VFZrRzhYTHA1S2tQWnU0VGt3SHJMWGdvYW5wNVJiTTU4a0R5VWUzS0o1bm9RcUtwV2tieTd3SkNjNjFTCktDTlE5RnNaM0VQNDR0MC9qaEdxeUVQV05yRnlJYkpHMW1mSW1jNmE3YWRZb3JwdXozS3NnZVhMRnhwZUdwV3oKbG84Y2VBN2pWVFR4NjdGd1lTQkhtNXc2S1hySlJzNmZ0b0pmdkFQcC9sczV4MUZtWHNGcWZPNjNyQTJlUFRyNgprbElHWWJ4NWhxUG54cWVqYXVDelpTZVkzTFY2TVZpbVBXMGFPTHlSbGR6Mk56ZUZYMEM2Z2ZRRlBUVjhpcjV4Ck9nTjZ4Q1pNbWpjajdyN01XOUpPZm0remRsRm1kRm5XNEtKVCtKVVZnTzM4MFJBdC8rOFF1b205aVcvSHBORzEKa3NVN2FkVGFEcjZEMmVUejBtTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBNEZFSTBSaFp1NEk3aW9hRThoUmtjaDhIcTdnd0hMUzRmck9TQ2RiOVZHdmFLTG1rCitvNE5Za3lXcFd0c2ZSakN6dDdzU2F6QlFCSlNwTlNka3UyN2RheXJpREMwRW9TR3F5QWF5Zk1QNmw1dDFxVjUKdURmQVJBbko3d3NKMjJKeXhHSGpvZE92cVlUQnd1cEtmT3g3M0lsZVUwVW1OVUZaR3FBWnd2cjNFVllUK0I4dQpjK1E1d2tSOGYxS3AxaFJiQlIwRHNuVTRjK3pySS9UL3JsYUw0bEwzQ2g5bHZmQmMwbnJSVGtrWnErbFZQLzVhCitkOExTOUNobndLVjFSSFcwSFNlNkRTdy9ubHc4QWNGemRrL3cwdWJwQ3ZEd2VPd0VvYmM0bVU3WUkrR0VUOGkKdmhQa1RtdkFJemlQbHpxVWVSNE1IU25lY1Fvb3h3ZDYwUDNlWlFJREFRQUJBb0lCQUFtZkl0NFlmd3JXWG5oRgo1bHNkaWFSdjFTRlF2SGJvRlRkOEVOZDRDbDdqWkdvVm5Sc1JMNXp5aWppc3Q2eDlwM3pUbmpZdElUbnBhZlEvCmhCc2F0RGZWMjZLekYyK1VQSDdkR091N2VsM2V4ZDZCM21ESzVXWHJESklZRUFqQ0VOMnJFWkR1QVUxOUVBbVgKWHB3UlViWngzdmhQNXVzUnMwRW1NbUlGRXB3WDdPNk91N2JPUVZUTmhKK0crcE9MT2d5MXBjOVRISzdpbXoybgpRNWwzcmRLNTV5bG9XbDdZL2tUSmxDcFgrdThrbVUxKzBwR1ZTaVJ3TlpaNGtLWlJtNFNQSVIrS1k2V1ZTbDloCjM1MFlwbDJjUHI1bk5yWXBqU3dndlpmRjdJRDN4UjVyN2RNT1BwS3Qydk5razlST09ZazFoK2J1NHl2UEF4S3kKM2M5OGx4RUNnWUVBNFdqYjd6Q2huNklBUEZFUjJmQVd0clUzYTlpdXVhdm5UeWZuYnhKTjUyUi9kZUNZbzRpcApqM2hObjBsVFJDZ2xqSGY5MVB0c3Qwb1hOWEFDdTdYajVyeGNBK3dVRG0rRWNtbGxTYUFJYnUrVDA5TUVxRlRsCjV4Um03eXJkOWZOM0F1WWxEcFVpVEZrdUNJaENiOTF2Ym1KMitqTktaTzJxN2lOZFlScXc3akVDZ1lFQS9zSXoKUTBCQitaRlZjbEV2QllrUzMvMkIva1pDZjdqOStJdjhWSG5UMTVUdDV0ZUF5SlJzdm9OUXRXbzQ2eGdlaWVIdgovUnlyM05hcmtmMmtTM3RXOXJRbWFuMmwzNUdvSlBheThvTHMyR3cxZTZQbFVwL1NReFZleEtxdHZyazUvTGdmCndYVFI1OFZjYVJid3d0TDk0V3ZzbVJISm05dThwVFV1ZldaR29uVUNnWUFuTlo1TVZTRklLMTN2SUFzQzVnaU4KYjZoY1VpelNqMXlGSUdQWnBrMTIycnh4UE1oUWFnMVVyNUNSREtnM1N1UjlNc0lzc2krUEVveEc5MTBDV2ZseQp3WUVnRFlqUG1nWm9BSDFsK1RoK1U1NWJVbkdVOW0rbmFwMGRMVSsrNE1McTlpMnNBN1Vib3NlbkpFeXFPTktSCldQOXBObExTaTZVWUYzNit6VzNKZ1FLQmdIaUJNKzVqdnRGbVJaekZlaENNUGpsbG1NL0dQRDVlS3dRZWMwVWkKTzJxR0wrSTVuZGxESEEwaDRGTnY0MnlSQkNFRWxwaUxyMS9PeTJsTEtTUHJPNytHaDRWbjJjWmZCOEkwVDRFWApIU0ZpVGdvbUJKdUlyZFM5anc1SURkZGhsbVJNVS9rV1lSUFk3MVZtWEl4TGNYdm5xUXJldHhiYVllbGp0cEhxCmh3N2hBb0dBVDNrOW9pTFFOeUZ0cENsaEVBTkJVT1hzcG1hcElSYTgya290ZU9ZeXhNKzZQakpMM296M2dENXkKMEYrc1cvZm9iWXpzVHdYVDdFR0J6TFN4d20xUmVMRzV3M3R3anBabTBQRGFWREtRTEdjaVBncVNEb1JJZGhPMgoyaXRhcHRrUkQ4dlA0Q0c2OHUxRUtGR0N4M3BpNEhGU1l0TzFneENUNjhFbThnMjhMOE09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: cluster-dc-a-klio-user
  namespace: dc-a
type: kubernetes.io/tls
---
## Generate client certificate for external cluster in dc-b, using the CA in dc-a. The generated certificate
## secret needs to be copied to dc-b namespace to be used by the external cluster configuration.
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: cluster-dc-a-klio-user-for-dc-b
#  namespace: dc-a
#spec:
#  commonName: klio@cluster-dc-a
#  secretName: cluster-dc-a-klio-user-for-dc-b
#
#  duration: 87600h # 10y
#  renewBefore: 78840h # 9y
#
#  isCA: false
#  usages:
#    - client auth
#
#  issuerRef:
#    name: klioserver-dc-a-ca
#    kind: Issuer
#    group: cert-manager.io
---
# Actual secret generated by the cluster-dc-a-klio-user cert-manager Certificate in dc-b.
# Copied here.
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQjN3cDJiUldGR3JCV0xKNHc2UDIvRkUzUDZRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1CNFhEVEkyTURJeU56RTBNamcwTTFvWApEVE0yTURJeU5URTBNamcwTTFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXg3ckt3cVpKdGxZVHU0d3lUV08wTmNrOEM0OUwKSVpCRTl4VDJHTUlGeDFXb0xZVHB1R0l3QlBGeTRqaUMwZUFHbEV2aGY3UlJrNlNFc3lmWWs0ZWU1enNrbU1OaApIOXlzNDl0dHVEM3E0NlNabWJVODMrS1crOW1aT0NUb2VsNmV2SXA4OUFPa1cwQm9VbmhkOEFobUY0REE1cnFwCkJrZkhaOXNtdEhoWWlXQXhnS1g3bjVvbUlmWU5NZDdSMTZrVWc3cVJkbG1ud1o3SENvVllIaE9MNjdheTAxUUIKT2FKMU1TMzh1djU2WFJJcEpvazZxaDF0SDZyL3FTV0RJVGtGL3JtczVabEp2Skg0cUlma0ZBeElGYzhTbmw0NApkQUN4OHhyWmkraEJweGxCWjdLTzY2ZlVwWTNXTGtHYUxWVlRxcHJmY25EaUQwSC9WREl3L0FNUTh3SURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKUEpJSmxxV0x2N1ZhN2o0WS9JRitCdUhjcFc0d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFETkUvdHhiSnV1SwpyWlg4VjNJTEhWc3hwZ24yRGFQQXp4U1AvRWRxdUF1aWh0NHRaazczQ24zUzdDVEZ4cUlLUVFmYVRPRnBFMGdoCmlqeXFXTTAyb1dQaUZvMjhuK0tTY010QzZVM2JCUWZlZFNPYTBtMGFheE11eWJxdjBjTXRxMVFUSGpBKzBFbjEKSjNmMnNrcDA1bC9wSWtVc2tZL2NpejZPWHBBOFY3ZFZhdDdycGo4RDBNbk9abFpqaG1GRytvcXlMVUp6L2IzZwp1Y0lHWEs2dlNBUjFGblI0TkpHODVvOXhncVRwc2R3Z1oyU2Q0Vk5PWHR2YUExZHJHcGQySUpJdTc4b2Q2QjFJCml6YjNUNmNvM1JSQURLM2hJNFVjUHdtQzFKdytkMWN1Z0VQeFl6Q2d3a1FlZmJ4VXlmZUpySkIyY1VETzZObG0KcmttM2J6R0U3VFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lVTy8xalByYXhmU0VTSDF6RmRWZ3UzcXdTQ2JVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1CNFhEVEkyTURJeU56RTBORGd5TlZvWApEVE0yTURJeU5URTBORGd5TlZvd0hERWFNQmdHQTFVRUF3d1JhMnhwYjBCamJIVnpkR1Z5TFdSakxXSXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2VCRWZ3Zk1iNXAxQmQxaVJNdWtCQU5rVUEKYjBvenVUeFAwVVZOZGpXWk1LdEEyOEE4VGtBSE1PRHpoMEpETi9zMy9pQlFkRzc4dVhwTlFpeisyT3dwMndZQQpBRFduTGxoT2RCR0FDT3pHY2hnQTRZVzFITktzMzlMd2orMGU1aEJPOHQySzVSOXl0VFQ5bDdQeGc2ZlJmNzJwCm5vUGFqQlhQOU1WTVVKbmRQSFN4dWVSVkkrVHEwbjhFV2ZLRjRKMEFKVU1pckIxV3Voa3BkaWVzWVR5K0hYbHIKMzdwWEp0QnhSdmFiRUloRW8rcndOV0ZwakxJdUN6QzdyK0lMM0JWWHQxQzVJMTNDbERaUUZVNFB0WHlOT08yTwpvVHpoZ0g4YzdoakU2Q0ZXV29UM1lYdjlDQUhOWlNrNnhpTEh0V2NrZGc5aTR4TkYwekRJNmY0VlJvODVBZ01CCkFBR2pSakJFTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGoKQkJnd0ZvQVVQSklKbHFXTHY3VmE3ajRZL0lGK0J1SGNwVzR3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUNlawpHRDg5TisrVFIrelpSdkw3a1UxTTBrMm9RQi9BdEllSzZiSWJMY1R5Q0M1ekd0dmJzMmFaeVJ1c1ZZRUZiWG9rCkVmMmtzZk5mOVlkaVVLVWNZaHRlMzhTei85elE2RCs1SUwzRkVMbFJ0b1dVWnhkSTVITnVLM0J3RS9pRDVkREYKbXdEckUvVHBYaEJaY2xtN3NLZDdHNW9LcENJb1BydVRmbndSdUtpNHVBK3lOQndDSDdvZlpoQ3UyQURQMXNKcgpZOWpwdmNTTTg2TXhlWDl5RW1Kc29BdTJSa0trVTdoV1N2TjhieXhWREcrSjRqbE0wdEV1U0NQY3QydGEycTg1Ck1NM21PYmNvUUd3SjNXS0pGblNjS0wyUDBmbXN6U21DNnlac2cvUXlhaUh6b01FN2lWeE02L3hOWjFNR001QVcKUytSMG45dkZ6RG1vemNUVk02az0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbmdSSDhIekcrYWRRWGRZa1RMcEFRRFpGQUc5S003azhUOUZGVFhZMW1UQ3JRTnZBClBFNUFCekRnODRkQ1F6ZjdOLzRnVUhSdS9MbDZUVUlzL3Rqc0tkc0dBQUExcHk1WVRuUVJnQWpzeG5JWUFPR0YKdFJ6U3JOL1M4SS90SHVZUVR2TGRpdVVmY3JVMC9aZXo4WU9uMFgrOXFaNkQyb3dWei9URlRGQ1ozVHgwc2JuawpWU1BrNnRKL0JGbnloZUNkQUNWRElxd2RWcm9aS1hZbnJHRTh2aDE1YTkrNlZ5YlFjVWIybXhDSVJLUHE4RFZoCmFZeXlMZ3N3dTYvaUM5d1ZWN2RRdVNOZHdwUTJVQlZPRDdWOGpUanRqcUU4NFlCL0hPNFl4T2doVmxxRTkyRjcKL1FnQnpXVXBPc1lpeDdWbkpIWVBZdU1UUmRNd3lPbitGVWFQT1FJREFRQUJBb0lCQUNPcnpydWt4MXd6WDRxWApYV0Z1eUROV3JQUUFxNDBLbTJsZlVoZysvN0dCMFo4V0hJcmdsVWFxUzVYZUttQzNRZ0J0WDBrYVI3WElmeW55CnJ1cW0rSVVvV3Uza0hqaUwxMFo2b0RxNWlRM3hVcWJjUWsxVTRPQkN0TUUybEc1ZHZEKytSckhrc0ZrNk8raWwKZHVzbDc5djB6TkYrSmNEUHo5cStwRTFxZ3BsMUFmM0xxeSs0VnhTaGI5clMza2ZUSXhPZERlY2p4MVVOVmVZSQpVaU1kN3pFbmJYN28xUWkwTjBRSCszZlR5K1JCZE5IVytRcnU3cVpNK3RMR3RZVkg1eUhpOGNvR25QV2V6TGx1CmdEdFZxa3VmWGI1WStCR1FrWFR5YzdpQS9YQXovL1YvRmpsR3FzeHhuQXlRY08yMUFqZ1h0Zkh1alBWZ3FtTWEKWmlwMzBZTUNnWUVBejhway9QNzlRKzZRWnpNTkhmVE5zRW5BSFJEd3BGT3R5aVYwSWs1UnhlOTRpak51YzFzYgpLVjZENk5LNDlnNlFnL2Jtd0xoQnpKaXRKWTBQVTZIenNjOWtVeEc2KzhaUHMrTjZGUkJVaXV0d29McXVrUjNzCk84ajJ0WGhPNTBVQWh4Y0NBTUExeHp3bUJnNy9qRWxRaVBDenU1aS9NNnJQNzV6ZzkyVUZySmNDZ1lFQXdxMlkKVWIwejZiUnVHdlpjWUQweURrY0NQWVZuazNqa2FEaUhrWFdnZVA2ZDVkeXFuM0RLR1JWUmp3Y0ZMeTVjWjhYNgpya0tpdXFZZGVRRWt6YlgrVzMxcjU3alRYUUd0MytMbVBYa3kzdFhMYlAzcUdURXlKb2FTbTZxMzhTTkw2OFNtCnoreWxjZ2hWSFAyVlp2TDgxS0dvQWZkcVdFUUI1bnFBc2ExMWpLOENnWUJneFBnOUhwOWlXS0xsZk0vNkNIMFcKUVhKMzF1RExGckZUK0JkYXRyQzhocWJUYmRwZFhLdU1tNWpCQUFubGhhamwzRUZndFM3bmtwN29Zd1lsUThJVApKK3VvQ0JUVmxtaWQ5UzF3eTljamp6dzNqbGtuK2hCL1V6c2FEanBvMkNqRHdRSk15VGNDWDAreCtLQW9mQ2hHCmJocTJIZy9GaHlJcGpCejAraFluWndLQmdDd2I2eFF5RzA0TGZKc05VTmJaWnJzSGFjR0l0WFFiZ3h6K0dmRmkKUm03RHVnRDM0NHptb0ZQWW1iY2ZieFJHbTlkRGEwNEtlUlp6UnVCQTJ4Yms4bkhHVkNtWG5nUkh1aDZ0S1YrcQpVMVZiK1pDRFk0UTd1bEl5VVl1RnZkR2NIcnFYdnZnRGRXVUY4RXIyUmVDaWs1aVYzQnc5ODlGMTd6eEthMWhXCnBmaXZBb0dCQUx4K1RFV2JhSGo4MnBabUlNamtBZHIrcTNuRXJkdUVKWG1OdkhwMDJ5UVRveVlPSUJCQ0pKdWgKN3d3RFRDR0diTWFFd0dSQlE2QjcyVURxZ1gzTVFZMDZIMkFRYnMvd3o1VmVvNXJNYTlIZVk3ZFlCYTFxb0h4eQppdlluUjFRWFMzZmduQ1l0MHB5SXBwSkE0UHg1ZGZDa1R0UmJCMndSUHBGVFg5NjdQOC9SCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: cluster-dc-b-klio-user-for-dc-a
  namespace: dc-a
type: kubernetes.io/tls
