apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-dc-b
  namespace: dc-b
spec:
  instances: 3
  imagePullPolicy: Always

  bootstrap:
    recovery:
      source: cluster-dc-a-recovery

  postgresql:
    pg_hba:
      - local replication all peer

  plugins:
    - name: klio.cnpg.io
      enabled: true
      parameters:
        pluginConfigurationRef: client-config-cluster-dc-b

  storage:
    size: 1Gi

  replica:
    self: cluster-dc-b
    primary: cluster-dc-a
    source: cluster-dc-a

  externalClusters:
  - name: cluster-dc-a
    plugin:
      name: klio.cnpg.io
      parameters:
        pluginConfigurationRef: client-config-external-cluster-dc-a

  - name: cluster-dc-a-recovery
    plugin:
      name: klio.cnpg.io
      parameters:
        pluginConfigurationRef: client-config-external-cluster-dc-a-recovery

  - name: cluster-dc-b
    plugin:
      name: klio.cnpg.io
      parameters:
        pluginConfigurationRef: client-config-cluster-dc-b
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-external-cluster-dc-a
  namespace: dc-b
spec:
  serverAddress: klioserver-dc-a.dc-a
  clientSecretName: cluster-dc-a-klio-user-for-dc-b
  serverSecretName: klioserver-dc-a-tls
  clusterName: cluster-dc-a
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-external-cluster-dc-a-recovery
  namespace: dc-b
spec:
  serverAddress: klioserver-dc-a.dc-a
  clientSecretName: cluster-dc-a-klio-user-for-dc-b
  serverSecretName: klioserver-dc-a-tls
  clusterName: cluster-dc-a
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-cluster-dc-b
  namespace: dc-b
spec:
  serverAddress: klioserver-dc-b.dc-b
  clientSecretName: cluster-dc-b-klio-user
  serverSecretName: klioserver-dc-b-tls
  clusterName: cluster-dc-b
---
## Generate client certificate for local cluster in dc-b, using the CA in dc-b.
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: cluster-dc-b-klio-user
#  namespace: dc-b
#spec:
#  commonName: klio@cluster-dc-b
#  secretName: cluster-dc-b-klio-user
#
#  duration: 87600h # 10y
#  renewBefore: 78840h # 9y
#
#  isCA: false
#  usages:
#    - client auth
#
#  issuerRef:
#    name: klioserver-dc-b-ca
#    kind: Issuer
#    group: cert-manager.io
---
# Actual secret generated from the above cert-manager Certificate for client auth in dc-b
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQjN3cDJiUldGR3JCV0xKNHc2UDIvRkUzUDZRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1CNFhEVEkyTURJeU56RTBNamcwTTFvWApEVE0yTURJeU5URTBNamcwTTFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXg3ckt3cVpKdGxZVHU0d3lUV08wTmNrOEM0OUwKSVpCRTl4VDJHTUlGeDFXb0xZVHB1R0l3QlBGeTRqaUMwZUFHbEV2aGY3UlJrNlNFc3lmWWs0ZWU1enNrbU1OaApIOXlzNDl0dHVEM3E0NlNabWJVODMrS1crOW1aT0NUb2VsNmV2SXA4OUFPa1cwQm9VbmhkOEFobUY0REE1cnFwCkJrZkhaOXNtdEhoWWlXQXhnS1g3bjVvbUlmWU5NZDdSMTZrVWc3cVJkbG1ud1o3SENvVllIaE9MNjdheTAxUUIKT2FKMU1TMzh1djU2WFJJcEpvazZxaDF0SDZyL3FTV0RJVGtGL3JtczVabEp2Skg0cUlma0ZBeElGYzhTbmw0NApkQUN4OHhyWmkraEJweGxCWjdLTzY2ZlVwWTNXTGtHYUxWVlRxcHJmY25EaUQwSC9WREl3L0FNUTh3SURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKUEpJSmxxV0x2N1ZhN2o0WS9JRitCdUhjcFc0d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFETkUvdHhiSnV1SwpyWlg4VjNJTEhWc3hwZ24yRGFQQXp4U1AvRWRxdUF1aWh0NHRaazczQ24zUzdDVEZ4cUlLUVFmYVRPRnBFMGdoCmlqeXFXTTAyb1dQaUZvMjhuK0tTY010QzZVM2JCUWZlZFNPYTBtMGFheE11eWJxdjBjTXRxMVFUSGpBKzBFbjEKSjNmMnNrcDA1bC9wSWtVc2tZL2NpejZPWHBBOFY3ZFZhdDdycGo4RDBNbk9abFpqaG1GRytvcXlMVUp6L2IzZwp1Y0lHWEs2dlNBUjFGblI0TkpHODVvOXhncVRwc2R3Z1oyU2Q0Vk5PWHR2YUExZHJHcGQySUpJdTc4b2Q2QjFJCml6YjNUNmNvM1JSQURLM2hJNFVjUHdtQzFKdytkMWN1Z0VQeFl6Q2d3a1FlZmJ4VXlmZUpySkIyY1VETzZObG0KcmttM2J6R0U3VFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lVYnhxSWYzTUdtNE8wOEQwSXdtK0hnck9iRE5Nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1CNFhEVEkyTURJeU56RTBORGd5TlZvWApEVE0yTURJeU5URTBORGd5TlZvd0hERWFNQmdHQTFVRUF3d1JhMnhwYjBCamJIVnpkR1Z5TFdSakxXSXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFJhVGkza3JOMnlYcThSeS9vVm16dkhNZVgKb2lwRVRGci9nTVVLSG1PL1gwWVNxOVc2ZlN1Vk5WTHVTazN2dG1lQUZZSU9zTmVJNjR0TE1XbEMxQURBU3RNLwpDQ2dVeFlESFZEaTZzRis3dUVmbHVvYjNaUVJ4dUxRbnkyNEFjd0piaGZEVnhxTXVDS1BwQXJzNElpSlVjbGdtCkJodWdEZ0FnVUMrZHJrMVF6TklyNTJVZXlSSW9JV0lGbUIrT2tzWXBwQVhhMmtpeXJBb1FNRTRJWCsrNEZxLzUKbW5QWmRNMHZQSFdJTDNybi9zRDZVbGkzTmV4eVdrQlFBOHFxM1F3b3FOMStDTnIvOUp0Zm8rTllsTERFOTQ2TAoyYXR4ODVTOTc1Um9wZmhMTmJFYWkvYmFiWEc2K3VFM3NZYUZLU1ZVcEJGSzJSV2FhUk03UHBReTdQd0pBZ01CCkFBR2pSakJFTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGoKQkJnd0ZvQVVQSklKbHFXTHY3VmE3ajRZL0lGK0J1SGNwVzR3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURnLwpSTkwvSWkzcmM2U1lQait5cFpHZUd0KzhGZ3A4ZTdYQ2xWSHNYQWN6TnZWdUNIRGZtR3crclZJZDZldnUzanhHCmlMQUhEdXg3R1RCVkNZbi80T0FzVzliSlAzcGRkK0xVdlozdVRtUzNwbFRMdTdSZmpxdXR2d3gvbEdNRWVhN2MKZHFvSThwSUtEOHk5VXhrazF6NXArVVoyZ2NRR3RnVGZPTzlGTUllTkFwRkpkVVRnSWdrNlo0V0tMeXBJRTRiRApZU2dHeng0eWxIRTBxYVlQWUdiN0h0bnlGZ2VJUGdaOW5HbTFPWFVTaE5KSVhERHFsdUZGMytvNTdHTk16YldJCkJ3TkllY3poV1F1c2ljS08xK3NmV1FISEQ2RkdvVXp0Sk0rcnFLdzl0U1VuK0tJUm9EVWxON0pYeS9pcTJlSk0KbHEydGpBOENLWEI4cTY3OHJqQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMFdrNHQ1S3pkc2w2dkVjdjZGWnM3eHpIbDZJcVJFeGEvNERGQ2g1anYxOUdFcXZWCnVuMHJsVFZTN2twTjc3Wm5nQldDRHJEWGlPdUxTekZwUXRRQXdFclRQd2dvRk1XQXgxUTR1ckJmdTdoSDVicUcKOTJVRWNiaTBKOHR1QUhNQ1c0WHcxY2FqTGdpajZRSzdPQ0lpVkhKWUpnWWJvQTRBSUZBdm5hNU5VTXpTSytkbApIc2tTS0NGaUJaZ2ZqcExHS2FRRjJ0cElzcXdLRURCT0NGL3Z1QmF2K1pwejJYVE5MengxaUM5NjUvN0ErbEpZCnR6WHNjbHBBVUFQS3F0ME1LS2pkZmdqYS8vU2JYNlBqV0pTd3hQZU9pOW1yY2ZPVXZlK1VhS1g0U3pXeEdvdjIKMm0xeHV2cmhON0dHaFNrbFZLUVJTdGtWbW1rVE96NlVNdXo4Q1FJREFRQUJBb0lCQUNiekFMTVlMSndMOW5HZApkZm9yVlFDV1pFTStUTWsrUUhDa1pVR3dERkowYUlhaGdsTzQ0MG5SekxaNGlJMXM2a3hHODlWQ3JCd1IzMnNoCmFoZ2RjWFJTbG43elIrMHhIUFkySW9VS3VBdWt4MjZocG1mT1dLakVOM0h0WXV6ZmQxRkpsTlZXS0ZTd0U3aUwKb3dIYVMzTlVmek8zVUIwUmJaR1ZDSDQyQkxoaHdiNXNyaXo4bjQ5RkRRczFiWFR5NGdWV3Z2enhpeGhseEFhZQp3WWZaTllEcDBxUVdmcEE5UmpqWHg0MzJlbU9pWnhBTEFSVEdiYktXdWZFazFKMGIrbi9kR09DRnZETmJuMHh6CmJQdS9yV2J5KzRtZHhwVkZzdzBTTG5STWdFWkI1amxGSXZrSGpsSVNRZkhON2lHbFNFeXFBcGp2WUR6NUpDTEkKZy9aZ2hsY0NnWUVBMDhWdWNBZkRlT0VvSWd0OUhmcDlabmtrSW1POGxzenNVU1dmbzByZEUwQ29DZWlubWZ0egpQYmFrOHRxZjFYYVpwV3RCWmdtcU9IdzlzUmw2dDk4eUV5WWFmYUdxNkxZVThqTFZYOGQ2VVZ1dWxTSU15Snl1ClNKQVZ4UDlpMjFZUHBoanNwSCtxcU1pam8rVi9PTTB3cnVYUVRQYmFTa0JLeTNoblducVlQRXNDZ1lFQS9TV1oKa2lYQ1B0Q1RCelEzdmxWcTkzN1Y0akRTblBNVDBJNVo3dk9Za2MyUVV1RmpNa1RWYjh4TjlFZ1BMcHp5UVgweApQdlh0aE5WTys5dUNLSkNwWlRGbCs3RFdzT0I2L3hvVU9Fc0p2SGVSa1IzcUtJRlNMNUd5ekk0c2JnVEgzSUZMClpOVWdaekVQaDJubzk1RngzUzlORm8rMElUWEhCQnNUZkJFTmpIc0NnWUE0NjNVT21aZVprdk1saTI3NnNzd24KMGVHN2VKRkUreGw5aWg1SlZxTHJQTkt0cnlIMVNsZWtPOFpFSEMwZncvdnlNVXpucnl0WWVWUmZtSmlhZVZ4TgpOMDJoZk9XaUhPYXVYcWxwVUFWNWZxb0RIWjdRQVFUN0xmY2I5d1RNTFdxUlcxdW5yMFRnanVVazlWZG5uZ2M2Cnl6eGNvM0R5eWlzUVczRjBLVVZuMXdLQmdRRElGK0pOYk44ZSs0cGIxV0NDWjg0SEZ4QkVtOGErSER6N1NxbTMKZ0lDR0x1LzNNd1JQaGEwWGsydkN2UHFUSTZjeE1KMnVZSUYvejRPQS9EN2poWVQvNFkzMDVoQ3MrcUw5NVVVNgpRY1hPWE15STRoWm1NZUllaTVIQ3NsWllHQnRLSmtETDBOS3QvaytCLzZzUGxMMWwwYStqTjY5djJLd1lpTFpjCkNMYW01UUtCZ1FEUUtIaWpqbzVZdUlYS2lKdE5MSmdYVjgyS1JsMU1yK2ZSeU9GWHV1TnhMalpYaG9GSnNNN3MKbTdkVWdKZXVJK01hdUNXaVV1US9HWWdqSFN5YmcvRW96WnZDRVNOa1M4SGZVT1pIcmJ6UXIxcXY4Sm82VElhKwpXQ0J1Q1RzZXYydVFyME43ZzFxSGlhUVE3R2tSTytsVWNIb3NRTVBiZXJWZEVmNlR6WVE0a1E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: cluster-dc-b-klio-user
  namespace: dc-b
type: kubernetes.io/tls
---
## Generate client certificate for external cluster in dc-a, using the CA in dc-b. The generated certificate
## secret needs to be copied to dc-a namespace to be used by the external cluster configuration.
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: cluster-dc-b-klio-user-for-dc-a
#  namespace: dc-b
#spec:
#  commonName: klio@cluster-dc-b
#  secretName: cluster-dc-b-klio-user-for-dc-a
#
#  duration: 87600h # 10y
#  renewBefore: 78840h # 9y
#
#  isCA: false
#  usages:
#    - client auth
#
#  issuerRef:
#    name: klioserver-dc-b-ca
#    kind: Issuer
#    group: cert-manager.io
---
# Actual secret generated by the cluster-dc-b-klio-user cert-manager Certificate in dc-a.
# Copied here.
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQ3lFOWRlcE1LeWl1dUZtUDBVTWM1SkFhVkxJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkyTURJeU56RXpNekExTjFvWApEVE0yTURJeU5URXpNekExTjFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXFiK0p6a1RWdDlWUFBMMjRTY1l3Tmw1azJsUFoKY2JvcWk5bTN0cnZWd0tmdHZJMGliSlkwSnY4WmV5c094T0JoakpRN0crWkR6YzY2WHYrQ2o4aVhtY1NIQXVmWApXbjdNbmozNjlsYzk1bFJvQ3ZPb2JrK0pWaldGZmErREN4MVBiMGczTlFJYlRiNXE4cXhOVUp0QnVFYzFKNmNmCk1HcUZvRkhqKzd4SlM5SXBXc3p3SjdWWmFDQkpkY2t6bTVLZzBqNXp5UUNXbGU2RXltNGZKTU85V1pxQlB5bDcKaWNadjhqOEltUmUrdTdqK1NZd2NQdkZxMXk1VU1SZGlpUUR0eURaRmE0TVF0S3RqWUxLZWN0YWNGdFYydUhQTgpsdW9mNTdwZnJNdTRBM3FsRC9GdUw0YURVdGhUMjFBRm80L3NOL1dFaDYvLzJtdHVKU0pvb0FvamZRSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKa2JyalU0L3ZPYlNLYkU0d2FkcmZNUnZ0WEVNd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEVjRMSGpJVm5YVgoxOUcxRGpHMWNqSFJvNXFnTmFDdllOVmd6T2NTaXEzY0ZhdFMzYkFLMFBWSDNCN1p1RzJycHppMkhkRkkwUCtqCkN0dGNCakFBVG1wVWJaay9hcm5Mc1NuajkvMW9VTVpXRXUwTUp2YklLcUxVMVo2VEUxRm5Id0o2UE5uM1J0MDYKcEcyR1R1UmJoSHpjSFEyVjBPU3YzZklRVTJTREVvWk5KazdpYnJSbjdIVUlvSVJ3SlY2ekd2OVdrZjdtSUxmQwpLZVF0VlgvTGU1OTJYNVlpZG5ZSCtWT05hSE40b1hGbmdFWHlqVjhna3NRS3V2TUZwUEN0WXc2UU5sOEZZQzAzCjIxRjJRYU1FdmJTUW1uZ1Z1ODFMNXR4dEI4djIrVEZDNUZ3ODBiMmNhaFBXYkt6WlYzMVBvODZzUUtSMW9sR2oKRlpOVzBXQnl0N3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lVVkJNbHJpRnBDaThrUFVaQjZ1SHE1NWlGNUlrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkyTURJeU56RTBORGt6TkZvWApEVE0yTURJeU5URTBORGt6TkZvd0hERWFNQmdHQTFVRUF3d1JhMnhwYjBCamJIVnpkR1Z5TFdSakxXRXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzd2TkU2Zkhmd1pzaVdwMUZBYUdaR1dQRVgKQWZQMlpIWEdLaVhmbzF1YjN1VjdTdEJrYk1JTjMxakxaYStNdVBPTHp2V2IwcER0MlBVRW5TSWNIMzkwZFFFTgppTUpVZkJYNEZBRUNWWHZWdlZzWkdXRXdzVGFBaXpEMG5EZ1lzOVphQStFU2NMT1BRZnV1NG0rbGE3ZmxUcTl6CmNYeEgrZzQwZ1hKdzR5YlF0bVNlaVdhY1dUZy96ZVJ2d254R1cxQk40QU10cW5WbXczMDRhc0d0MXJpdVNZMWIKc1RFeDAzMXk5bkdHbUxhczhhUXlwVmFkMnVGbCtUWk0wZU9HRmk3VWorR08rREhyUTE2UzJ5SUx2VDJ3NjMwYgpKT2ltTHBwTlZDSU8ydFBKdVJQQy9wUVZaYS9WdUZ3NVhjMEdiUVh2RU9mck81Q2FOODJqd2lpRmJ5QmJBZ01CCkFBR2pSakJFTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGoKQkJnd0ZvQVVrYnJqVTQvdk9iU0tiRTR3YWRyZk1SdnRYRU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURMbwpwTE1ZUDB6QXFpZ2ZuQm9CY1dXSGhrcUIyM0ZabDBiZFlrRGhKRUhmWTJ0ZnBySFQydFhyM0F1MEFLV2J4WEhSCml4SW9iakhSbXkvV2dhaXlYbHNrZzdDaEVucmY5bnUydy9HdWYrcW5pTFEzc2dROXl5TVF6YlBFbHFGUGZGTHkKTHZqdldEeDdRRnpFLzF5MU1ibGo1WWNRS1prNm8rcktDb1JLaVpjZ0JHbHB0Y0dLRnRqL3Z1MVJ3NnUvbnl4cgorTnRxbW8zZituUWpBSDZsYUdGZnVnVVRnR1RWa2Z5WmlISzBXcnphM3V6L09RQ1JqeEV1K1hyYkxFemxoaEVVClRENFZDelZwdTA5MmZTRnVIYnlndGpYQjBMZ0JESHNlY2VhUGxpT2RWZFhBVXF0R0RLVWdMdHFrNklRMkxsS1EKemIyQmpoRUJ4dEY5NG5hODhaaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdTd6Uk9ueDM4R2JJbHFkUlFHaG1SbGp4RndIejltUjF4aW9sMzZOYm05N2xlMHJRClpHekNEZDlZeTJXdmpManppODcxbTlLUTdkajFCSjBpSEI5L2RIVUJEWWpDVkh3VitCUUJBbFY3MWIxYkdSbGgKTUxFMmdJc3c5Snc0R0xQV1dnUGhFbkN6ajBIN3J1SnZwV3UzNVU2dmMzRjhSL29PTklGeWNPTW0wTFprbm9sbQpuRms0UDgza2I4SjhSbHRRVGVBRExhcDFac045T0dyQnJkYTRya21OVzdFeE1kTjljdlp4aHBpMnJQR2tNcVZXCm5kcmhaZmsyVE5IamhoWXUxSS9oanZneDYwTmVrdHNpQzcwOXNPdDlHeVRvcGk2YVRWUWlEdHJUeWJrVHd2NlUKRldXdjFiaGNPVjNOQm0wRjd4RG42enVRbWpmTm84SW9oVzhnV3dJREFRQUJBb0lCQUNZTU5GTW9HcDZzRmdjQwpUZU5CeFVpSWlnUGhyM0hHRm1CYzltUUdsWEJYa2lhVW1QdGhWMHE4Y3lCMXNVaFJ5M29RTFpLdzhCSmtIL1FaCmJHcEtyK2dJTm5ocHVRaXFSVUdMdkZDZXhvUWc1aStHQno1NUM5U3RZUFNTSElSVkhpSU1HemREaEFDS25ObHEKcHJuZHhOMUNQeWlrWFUyeERlUHlRQ0ZFeC84UVB2K1B4TzBrUGJ1S0orTldyU0ZUc01yVEU1N0VXcThLRlBMZwpCM0dSODhjTVBvcUZsbEtVUUpnU09sdk5IcUErWTM5ZExoektCb2N0MkduY0J3TjR1cG5hTHEzMVpqOCs5T2ErCnFORFlwcTVIWDZiTjZmalVneTFZZVRHSHIrWEgxWjRaWnE3VExMN1FPd1c0TlNkTUJnejl2OXpzUk1KYUZGWGgKcnRYN0lNRUNnWUVBenpBNklhOCt3aXNYUjE3bUVsaVZ1cmlzQXJEWGh2Y1J0aGt4NCtFSjBpbUIxNVF2d012SQpYTU02aHFFTUpkcWsvUVZ0NjZraU1kc3ZuTXZpQmt0OFdtWFppamNNSnRkSWlTRWFGa0VHc1FzNFBHMVV4RjVSCit2VEFSalJ0eEtST0l0MlJYQjVLVldHTXNpeWhlZlFCQlA4d1FrWko2RFg5TFkrRno2WUhtWEVDZ1lFQTUvZDkKR0FuTXAxbVorNnhrbUtZL3FqSkFlNmNjcjJIK3VINWhHdFJ4MHJsY0YwRGtZR1hXOHZZNUp5K1NkSlBvbGhxOQpIU0NXUEpGTGcvL1VjSDVWM2hqUHNoOUsrK3FFWHlVZzJPcmZhM3BMTEZ4S29qUTdPRmp1Wmd5WlhNRWV0QzhJCjBzOVQzNk9IR3JCdFVtMGFobDgvYTg4SlMwai9adFhkTWlOVDBJc0NnWUFON3FsS0VKWEF5dE1DNnAvQUJoTHoKZm0yYXRMZVpqTTIxR0JhaHcwVTh5NnUraW1sM3BueHZ1SFVjRG9KWm5VMVE4bWVFM0ZlL1VJVHdIMG13c0t6SgpDMlpJaEJFZUg0WHlLcmF0WG13THhieGZXOTdDWWJGVGxkZkVJTXhzMTd1bFhvN2l5ZXFudVNxVDVLcHJIL3hkCmtLZDNIWERrMjVTTjFzUGh4Y0ZuRVFLQmdGWW5pSkdtQ2huWjRLUWwrbExyNUZkOVJJL29tSEhYVHJrTlQxbWMKc0EzWkJJZ3FkT2dNeXhJQU8yZi9ka0RRTXFHVm1zbTNzYlViTGRYLzdkSStTZndzY08reVNiSlkvd01ya2hDZQo0NDVTcEpyOFNFZ0lhRHBjWldjSHBPcGJXK0VHV3h1Wkg0aS9mczE5MjR5eXN4aFhSZ0h2cW44SXhMdFlFVWl1CjhGRlRBb0dCQUtxbnhmbmtwbmV6dFJkYWM0elBzSDExS1FOVHZjNUxGWEJTOUh6aWM3bko4VHg5NUVOMEQvL2kKK1Zad01mcWxucXp4QWgwTTFJM1NCaGgrMUt5WWRGL2dVaFNYSzVlMS8ydGxnWjQ5cG1lNDBNelZPZFMrU1dqaQpsdmRWOWNqaUZ5OTgxRWVsSWpuRnBuWTN1OXVTQldMYkZIcW5tQ0RrTTN2ekdvT0dySGowCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: cluster-dc-a-klio-user-for-dc-b
  namespace: dc-b
type: kubernetes.io/tls
