apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-dc-b
  namespace: dc-b
spec:
  instances: 3
  imagePullPolicy: Always

  bootstrap:
    recovery:
      source: cluster-dc-a-recovery

  postgresql:
    pg_hba:
      - local replication all peer

  plugins:
    - name: klio.cnpg.io
      enabled: true
      parameters:
        pluginConfigurationRef: client-config-cluster-dc-b

  storage:
    size: 1Gi

  replica:
    self: cluster-dc-b
    primary: cluster-dc-a
    source: cluster-dc-a

  externalClusters:
  - name: cluster-dc-a
    plugin:
      name: klio.cnpg.io
      parameters:
        pluginConfigurationRef: client-config-external-cluster-dc-a

  - name: cluster-dc-a-recovery
    plugin:
      name: klio.cnpg.io
      parameters:
        pluginConfigurationRef: client-config-external-cluster-dc-a-recovery

  - name: cluster-dc-b
    plugin:
      name: klio.cnpg.io
      parameters:
        pluginConfigurationRef: client-config-cluster-dc-b
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-external-cluster-dc-a
  namespace: dc-b
spec:
  serverAddress: klioserver-dc-a.dc-a
  clientSecretName: cluster-dc-a-klio-user
  serverSecretName: klioserver-dc-a-tls
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-external-cluster-dc-a-recovery
  namespace: dc-b
spec:
  serverAddress: klioserver-dc-a.dc-a
  clientSecretName: cluster-dc-a-klio-user
  serverSecretName: klioserver-dc-a-tls
  backupId: backup-20251031141912
  clusterName: cluster-dc-a
---
apiVersion: klio.cnpg.io/v1alpha1
kind: PluginConfiguration
metadata:
  name: client-config-cluster-dc-b
  namespace: dc-b
spec:
  serverAddress: klioserver-dc-b.dc-b
  clientSecretName: cluster-dc-b-klio-user
  serverSecretName: klioserver-dc-b-tls
---
## Generate client certificate for local cluster in dc-b, using the CA in dc-b.
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: cluster-dc-b-klio-user
#  namespace: dc-b
#spec:
#  commonName: klio@cluster-dc-b
#  secretName: cluster-dc-b-klio-user
#
#  duration: 2160h # 90d
#  renewBefore: 360h # 15d
#
#  isCA: false
#  usages:
#    - client auth
#
#  issuerRef:
#    name: klioserver-dc-b-ca
#    kind: Issuer
#    group: cert-manager.io
#---
# Actual secret generated from the above cert-manager Certificate for client auth in dc-b
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQnVkNzJLaWpvekFmaFRVcVFFZ3EwbkZBSlNZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1CNFhEVEkxTVRBek1URXpOVGN6TTFvWApEVEkyTURFeU9URXpOVGN6TTFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXh3S04wOFRFTEh3cFlDQzVGK3BLS3lCMHk5UmwKNi9IbWI4UXF1N2RRUnFXMDJOOUxOeXJIZmc1SlhxcFhmLzJtbVlYc1U4YUp3ZWVMMUpYV3J2NTJIN1RtemRBUwo4WVJFZWtjdDZtUk1hVFhHbGFHU1pneWswbzZmRm9iaEEzMmZEYXg1ZUsxTUh0bi9mblZZWDJUcFZJYTBkQkUvCmUxazdnS0VYc1NLNnRHa3pRZ2VxR0ZQUFVxN2xjbGplYXFZQXorSmhwSFhDbVRRc3VpdFFTVUlHcDF5QTJsTUYKaUZqVUJVcmMrYkJXUmlEM1FPWVorVlhISVVoaUpxdVlrdHdjNmg2eFV6NUJoQzN0T1hVNDA5R3E5dGx6b0tmaQpMbno2b0Q2emp3ZW1DeTdFblFEWUw2aE9TZGxBKzVJS3hhdmVKTWdQTmdubTdTRVFBNXIwZzRkUFN3SURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKWUJyY1VrL0NKUW4vbStoNnBsQlVhdjkzOXFNd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDVm44bUk4T1U2OQpoc085SWV4bW91RStrYjlLQXRqRC9MbnJrQmZpMHpFWTJHelRPWWUxQlJsaTFDaVZKcXZUWW9EQmk1bDYrbEY0Clp4QWpVRjM5TmJMN1JJcGJiTml2L0o2alBxSXhNbUQ3eDJuTmVlRW9BcTdDRHAzQmhsL0s4SmZYYnpXMzgxbi8Ka01EMXdqeFdVaDIrNGV6eW1US1JQRFNuLzUxTy9JbzZDQmhGbTJBZ053TFY3MkozR1FJZmtVYU5jR3oyZkJPSQpaV01CR2RjaXJ4cjVTVkdzSVc2ZW4zSnE0RTFIcTZvaGFtSUNxRHgvMnloTjhta1F4U3k1MFNOck9QOEhGZCtLCjBndGhvN29IK0lMbmNjWVhxMTZtczFyd0NSTnZvWm5Eay9scGNVSGlvWDl3NjU3c0sxdG1nUzVCSktRZmZVNnkKRDBsZjhFODVtamc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lVWFBtMERvL3NKbE9HWStFQU1ONWQrdzdPSkZRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1CNFhEVEkxTVRBek1URXpOVGN6TTFvWApEVEkyTURFeU9URXpOVGN6TTFvd0hERWFNQmdHQTFVRUF3d1JhMnhwYjBCamJIVnpkR1Z5TFdSakxXSXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFkzVEU1U2NPalcxR3hGWE1obUt3UEtacGMKblFWNEExcEV6aHY1UmsyQzFYZ0JkeDR4VnRxOHRyUGFYMjJ2TkRIUERaVk13VDA1UUEycHVtQUFZK3lHRE42cApIMWN3T1RxOTJzOGsvL0FiMFI4SHNxbG9OVzhDOWhvVTRnclNUVnpOM29CTjlIS2JWOStvWkxsWWxMN3NuY1R4ClRKUFVFRCs5L0tldFZVVC82dEthRTdwMWxpaGFPR00ySk1uTm9NYStTbkRabk5lckpTck15c0RjbmZOVXg0UFAKbXFzRVc4MTN6VVNsVUFPb0ZXUWRCckFtbHZsbXM3T0l3a2VJRlFVTGVKTGlaQ2dHakM4Mm5ha09LYzZRV3hHZwo1akNKQlY2TmYxR1pPcWRoQVFrd1lxOVY1ZWp6K2EzbExua2g5SU5EWEdxa2ZrcUJmSGlidVppUUI4YjdBZ01CCkFBR2pSakJFTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGoKQkJnd0ZvQVVZQnJjVWsvQ0pRbi9tK2g2cGxCVWF2OTM5cU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUcyNwpsZWg4a05ybkcwODNDSkc1bU9HRVBxU3lMWld1R3V3dGkvMER2cEhiV2ZkcXBGYlF4cjJ3ZGtvRndZWno0bHhxCm9uMmg2bUVjZUMrVGhncU5wWG1ISFY1NmlKRTgyQXNHUkp6ZFJhQUpvV1NQRW1lN1BwQmtDN0w5dzl0aTlEc2sKb1FpNkZqQUdXZmdlbXhYMEJQUGtyVVlLVlgxaHhmeEczRXZuUHJWazV1SEdzc21PWFp3RjN1bUhvTlRlaWtpTwpOMFZsNE9BWERuUzAvdUc0UzNBdUFpSWhmYWFYcjA5SzlEc3A2ZzAyaEU4MHFqVE9JcmcxNWFaVkQxRnhjZFM2CmhXWUVtNXlhb2sySDAxd21PTlJqR1JoWS9MM3lCai9RblRsM0lPUHM4ZWRYZmhkUGN3RDlzc3RZMnJMMS9BWGEKdStha1NZRlFGTVd5dFFydUJCMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMk4weE9VbkRvMXRSc1JWeklaaXNEeW1hWEowRmVBTmFSTTRiK1VaTmd0VjRBWGNlCk1WYmF2TGF6Mmw5dHJ6UXh6dzJWVE1FOU9VQU5xYnBnQUdQc2hnemVxUjlYTURrNnZkclBKUC93RzlFZkI3S3AKYURWdkF2WWFGT0lLMGsxY3pkNkFUZlJ5bTFmZnFHUzVXSlMrN0ozRThVeVQxQkEvdmZ5bnJWVkUvK3JTbWhPNgpkWllvV2poak5pVEp6YURHdmtwdzJaelhxeVVxek1yQTNKM3pWTWVEejVxckJGdk5kODFFcFZBRHFCVmtIUWF3CkpwYjVack96aU1KSGlCVUZDM2lTNG1Rb0Jvd3ZOcDJwRGluT2tGc1JvT1l3aVFWZWpYOVJtVHFuWVFFSk1HS3YKVmVYbzgvbXQ1UzU1SWZTRFExeHFwSDVLZ1h4NG03bVlrQWZHK3dJREFRQUJBb0lCQUF6OGZlaWMwckxURXByRQptbzdkK2h1MFZaS0xNcHNqdEVHZmlBeE8yZkJtUVJmeFhxVDh1ditHLzFFcDJzTWRvSWZ5Rzhrclh6T3c4c0NCCnNTTUUyTktVTGJjNThib3BDeXY0VU9RNTBWS1JITWNVdTFGS3RkbWJEQ2ZJKzNYcGZRKzA3Y0Q5VE9taGd2cXUKQVcxZEJ1dmJiTUk0WURmWU8wRHd3c2U5N2ZKWExNV2dkY3NoSkttMWdOdm5GRnJPVzQ1NngwN3VvRUpNazRxTworOWdIam5LVExGa3FFMnlPbndZVFMyQ0tIYkxLYVcwb0hlZDZIQ05CYlBlb0pBcWFmQ3RnMEhTdlpDKzJxbDg1ClMwcTcxdSsxcTB5TWFuakFhWXNWMGlFeUJJSUltYzZGT3IyOG5SZ2dGdGtLRXgvb000SlZQckU3Wnp0UloyZzUKV1NtaHprVUNnWUVBNDJPRDhleFBDdncrbERFdENCVjdUdXBUOGh6Q0hFWS9YTWIrVWtoaU5mUThVQUhFVzg5SQoxMXgzTWlqRXdHY3Vjd2VtNzRTeFpoRkxVRi9YOTBhckQyM25xZ1E3Ri9HN1lWYzBwaklETFROOFRpbmxDRk5yCk1Zb3FjZjVqY2owY0FOVEo0QjlIOTF4eDlFeFZLYTg1QzMxd0MvM0NiN2hZaU9USlM0bnptODBDZ1lFQTlDYXAKcHhseFplbnpnbWxVZjY0ZW1GczdDTWt2K2cyNkUrQmpCazVZTnZXbmpPTk5uSkFaNzVJaVdORU5NQlRsZmhPTApkQlBTZk9jaFZnS21iVzQ1M2IveHFJekRCRlUxWXB0dHJKYi9TT2Z2c01NTTFRZFVDSE41RUJJUzRZS3JKbnlaCi84ZTd1NWowQ3cvL3NDL3laZVhGcjVyU3A4S3NjMkFod09pSDllY0NnWUVBcjJkQ2pzbVVwNHF3MHl1ajZ3cDMKRmdiWVBubEVtdjd0UGFvYTRHb0pxRWtBaFU3M28wS2drOUExK2pGTXBJWnpaRFJRNTQ1YU1idkJkdnlYNFoxWApzdzA2bVFHdWUrZnlmVUlCMFBuZlRXemJ4SWU0cnRWNmFMcUZ4MjFPVlA4aXJObDM2RFQ1Rkt6eEVsd1hqWkltCjFPQXNJSFBkR3NUL05vb1ZaUG5ET3prQ2dZRUFtK09YelZiRWZmTU1CVWVscVVTT3ltN3QyYVZEMmVBcjRJY1UKRXpHd3g1N0FWWWZJeFYrSS85dUp6TFhtT3I0TTdod2luWUlPa3F1dE1GTE8ydTVYU2t4RlMzNWRBb1k1YVBXZQo2R1VkS1ByV28wRlhEeW4zc05HeUNkM1FhbWJaU3VDaUg1dnpOVXZxL3FrL2M4cVpkaEJvMGNBRUl4Tjhzc285Cm93T1YxQjhDZ1lBUWhYS1Y1L1RsUitlcDRNbThxeVVEaGkwQTFjWDVId1orRnFSS3drRENFNFhVVHNqQjRPVngKWXlOYTFjcCtvTlV3bllyRU94MFA1WWtBdGp2VzVFMkFPOVpwWTEyWnVKYkc1YW00K2lGcGpQZWF4QzFHbDB5awoxZmovTjhxdG1xWExoc09qUzQ5YlVnL0hSd1k1M1ZINFNTMFBMQnQ0d25HVGt3L0VIUG9XQ3c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: cluster-dc-b-klio-user
  namespace: dc-b
type: kubernetes.io/tls
#---
## Generate client certificate for external cluster in dc-a, using the CA in dc-b. The generated certificate
## secret needs to be copied to dc-a namespace to be used by the external cluster configuration.
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: cluster-dc-a-klio-user
#  namespace: dc-b
#spec:
#  commonName: klio@cluster-dc-b
#  secretName: cluster-dc-a-klio-user
#
#  duration: 2160h # 90d
#  renewBefore: 360h # 15d
#
#  isCA: false
#  usages:
#    - client auth
#
#  issuerRef:
#    name: klioserver-dc-b-ca
#    kind: Issuer
#    group: cert-manager.io
---
# Actual secret generated by the cluster-dc-b-klio-user cert-manager Certificate in dc-a.
# Copied here.
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQjIrb3p3WDVxUzFJMThGZVVtTEdkSjc0ZlF3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkxTVRBek1URXpNalF3TkZvWApEVEkyTURFeU9URXpNalF3TkZvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNOdEY2cDhwTlpGb1hCd3ZrN2NuL0xGTnZPRnkKQUQrdWxCMWhhdXBFV1UycEphQ1FSUkppTXB4dmZCZERlS3c1azZJYkZCTVUxZkRaY0lCV0NEcEJUek51N09wZApqVzd1Rk5GV2hSK1d2bXJEb092d0JKalRpTGU3dlVqV245bkpLM2RiRkNKSUJWclN6T3JGR1BSL2ZTTnBXODV1CjhvNDZoRGpRTXVwM0YzK3h4Y21TSjdQamVYcnJ3ekkrdDRyNXRtQ3VsZFhNSGxjUzZsMlVUeEQ4ZENmbjNEbjYKZ2VsM2RES1g3WWlSVmJYU1R2TkZZMnVhNVVBQUVmaFFzWTA3OWdETXJQS1kzYkhvWUU1alY5ZEtTcWVKd21YVgpNUUZXYnRTZ0xWb3Y1UUxubElQZnlQeHFHbWZvcHpaWjZ4Z1YvNVorQXMrWFFyNlhYaDFkL3BoQUlRSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKaFo1d2dseXJmYW5KYlk4N0M2VGxyWXZ3blhVd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBR3VkSFdKQnBxNApZVHIxc3JFaCtyMFZDUEVGaTEyOHlxdFdtSUFQR2svZlo4R2NScHg2ZFRlSy8reVVGUVAwcFVieXlPKytBSC9xCkNNOVlVU1hvanV5dW5NaFdXQmdMTDczNlNBVDBiOFNoY2F4djRIcDJ6N0R2WFNFdUsrTzZlbTFLWmI1Z0pWZCsKVHF4R0Y5ZHNCZE5FUHBlR25JVXZjR1d1aGIvWEVnYlA4SVJ1ZXcvLzVLWkNmT3FYczFobWFhMVRkTjZmZU9hYgpCbnZHUmtmZFlBS1lkTkFGckt1enV3N1MzdFRNMkNhZDVzRlMwLy81MHNRMHY1QnNFamVkRkdMcDFNZ0xIVlpLCitCRGo3SHVPOGpJa0ExMjFkUy9jejd1VW1RMkZ2R2xTY0VhUVJuNXNGUldxMGJQYXVaL2dtenQzNjMyektCQXMKc3FuZ0pTcE1WR009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lVQ1ZCMGZSeWtlWjhGUE81ZVdGVk8waDNaZW1nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkxTVRBek1URXpNelkxT1ZvWApEVEkyTURFeU9URXpNelkxT1Zvd0hERWFNQmdHQTFVRUF3d1JhMnhwYjBCamJIVnpkR1Z5TFdSakxXRXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzVXdnpCc2VXVHBxVkRsbDhpc01EcS9abW0KTjRYaVM4Z0wxRFhrbjlGSVl4Nk1aL2IxZXZ1Tkp4OE1UOTNUdWMvV3VEMktiakp0c1Q4c2FJeitKV2poVENOagowc2tuTnBGY1dHc3VFVjNyMnNzeG9EajhpUGxhSDZBdEs0UzduLzAyK0J1MHFITFF4aFNWc20vOUNZVmo1MVBCCmRMNjZQS3hjck9FQzl6YjlRRnJicGZ2UUpUYllpeitEbnNtclRucmR2ZXNXMzNKbEM5cXYzTkpud0Q3K0ljNkMKcHlBZWlSRFQ0dE8zT3NTVmthMFpIakJRYTVHNUQxVFlDWndjQnh2RmpXdjNhTkltZ1pJUWltRCswUzBUd0Z1Rwp6MkU1Q29vNUtyVkpCKzlMU3hNZ3MyUUdEOGNPYnk0eSsxUTZoMWtNVzV2NTFaTGlRYTZUQXVkenFPWXJBZ01CCkFBR2pSakJFTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGoKQkJnd0ZvQVVoWjV3Z2x5cmZhbkpiWTg3QzZUbHJZdnduWFV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUZmVApDNDB4YTNOWU1VMnAySEM1SkYrdHV5bldwTWxpZGcxclorN3FkWjFVVnF2M2xNSi9OODVYdmRqQ0w1ZUFZUzBVCmFjejEySWlWN2pEcFJFaVRiSG9kaDdhUWhBU1ZnUkZZWTRtczRWb2JXY0Zvd0pKU2svamZ3cExqditPU2VuQm4KUytTbWZWQmhqWXhnbnhWNzdQUENZSnEvaHJGNWcyYlZKNnd0UHNvK29KSzM0MG5RbjF6aG01MVc2QUYyTWFxRwpUZzRjbVl5bnBDWmhTRjF3R1ZnNUM0clRLSUNwWnNwK2hZRVNxaWhXWlkyUXhWUVVwYkhhVzFDVmJCSGZZVXRiCjZaVEsvcWFocGxvdU83TlhkUGdVWEhINHNFZWpRNXZBUExicHpraHVJTDVjellNN01hTUhpbFNkZS9jV1A4NisKaVFvZlhJRmxqV2lJZ0IrQlNRMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdVZyOHdiSGxrNmFsUTVaZklyREE2djJacGplRjRrdklDOVExNUovUlNHTWVqR2YyCjlYcjdqU2NmREUvZDA3blAxcmc5aW00eWJiRS9MR2lNL2lWbzRVd2pZOUxKSnphUlhGaHJMaEZkNjlyTE1hQTQKL0lqNVdoK2dMU3VFdTUvOU52Z2J0S2h5ME1ZVWxiSnYvUW1GWStkVHdYUyt1anlzWEt6aEF2YzIvVUJhMjZYNwowQ1UyMklzL2c1N0pxMDU2M2IzckZ0OXlaUXZhcjl6U1o4QSsvaUhPZ3FjZ0hva1EwK0xUdHpyRWxaR3RHUjR3ClVHdVJ1UTlVMkFtY0hBY2J4WTFyOTJqU0pvR1NFSXBnL3RFdEU4QmJoczloT1FxS09TcTFTUWZ2UzBzVElMTmsKQmcvSERtOHVNdnRVT29kWkRGdWIrZFdTNGtHdWt3TG5jNmptS3dJREFRQUJBb0lCQUZtSVhrd1BxdFhoNnJWVgpodG5DYUVWNlAwUS9VS0FKTy9XZXlYT0lVVGEyampTREtaTFZGM3BNdWQ0Z0hBWWdISWxhMEhzMEZJN1F6Yk9kClF2R21UMTE0Z2lXL1ZTUG9ZMW1vYWdsRUlVcUNrcUVEaEZOVHRLSzRZUTVBbGFwdHN3bmcyYjB2bXRwR3UvMjkKUmdRRG05ZXdqMUFFblBabnhWZzB0N0hQaVZQVmRWd2xEQ1pIOGtWZkxTc3kySGY0TWFEd0FCbHkrb1MvZmpRNQpkOXFHZXY0VlArV0xJTnRzVjNvM1B2MXF5eDNxZzVDRWN6SmZjc3phcHZxUml0dHZrY2sxQTl5SmlERGZEVVRECjZsMG1yMjRtN2FRL2s5eld6cFZPKzZaVFVpNXdCcXhaejQyWkhkaXpSUmhOVUFlZUR2a0syeERMWk5OdXdkdjUKaU9IRTJta0NnWUVBeHRoNGtrRzZqeS9JN0tjKyttVHcwRU1McWppTTJvS2Z5amp5UFd3eWx5NG1iczNiRWxPcwpWVDNFRG1Ebk1pUjNKT29rVEtCMjVWVnZqY25KT1BaMThBM3NkZFQwOGRKMUFDWjMwN2NtaFZrOStiWGx4cTRiCkpDdTJoT2luck5idnVmL2llanY4KzZLa1UyQ3ZsdFVMREdKNHNhclcyb0lKNkZTOWdvYWtMRE1DZ1lFQTdxSGcKcjdYenhqNjNtckpyZHllSW0waGpRdHV6cmdJVTlqSmlIK0sram1sSUZOZ2o2T1ZkZWJ3dHo0WjREaTR1SW5GeApCTG8zZkRXbG9Dd3FHTHRzbmRvdFhUSkxxYXltZGZXeEZKN0Y5S0dnbWFFNURDM2Y5aWlVblFVdFlxdVdpZVNEClMvNENjcFMwNTZCWUtxUkVTaDJPc3NtU004OXJPNEFFaGVXNDVpa0NnWUVBZzU5RTZHTlR6M1l0Qk9HTUlZangKa3BuZXZkVmkvejBaOG0wUmhERDdwL0RuaGM4RDVUUzN6VkR1VnlvenY1QTl3WlN2WkgyUFZpemdnN1YvV2hKaQpiUDE2ZVdEMnBwL056TVNwNnQzQVJPS1cwSlZrUE1pQXRNZXVzSG1rakJkV1pnT0ljYXNGd2JlZUdJYldrL3YvCnJUbjlkSFdHZE90QkRhWVNMN1ZhTk5zQ2dZRUF1bFNTSWdGOFFLN1dKS2Z1ZTlMVnV4SngxMUcvNGo1ajZiMTcKbXhRczRQeGFPVlJ2N2JtekhJd1FaVHZGWUtVMGh0WjNmazU5WnJKcENrR1IrVS9YeHdZR2FBQU96b1V1VVdzdwpBejdhcVdMUENVYTNTY2hFV1d4a1pwc1ZUamRYUzRLdjl0VjNTY3JOMnhMNzVRZncvc0pIbTFrRG5RcjMyelRoCjB6K0YrY2tDZ1lFQWxNTVh4S1RnVUF5NzFSL3E4T2tFYVNZVVlteUt2M0UrbmZ4eDgxVkM0Rk1EWWNIQVh6VmQKK1RiZWkzWUxNTk81NDIrcVdoc3BWRmw3blF0M3g2cmx3SCtzR3pGQ01VU3RUTlhTT2RsaFdlTjh6Y1ovMW9mQgpic2RoeW1HSkNwaW5oQmFUMVFjSG5WSEV2ZnlYWDFTTlk2KysvRjJMaVVNdGtpaWRJaEhPRi9jPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: cluster-dc-a-klio-user
  namespace: dc-b
type: kubernetes.io/tls
