apiVersion: v1
kind: Namespace
metadata:
  name: dc-a
spec: {}
---
apiVersion: klio.cnpg.io/v1alpha1
kind: Server
metadata:
  name: klioserver-dc-a
  namespace: dc-a
spec:
  baseConfiguration:
    adminUser:
      name: klioserver-dc-a-adm

  cacheConfiguration:
    pvcTemplate:
      resources:
        requests:
          storage: 1Gi
      accessModes:
      - ReadWriteOnce

  dataConfiguration:
    pvcTemplate:
      resources:
        requests:
          storage: 1Gi
      accessModes:
      - ReadWriteOnce

  password:
    name: klioserver-dc-a-encryption
    key: password

  tlsSecretName: klioserver-dc-a-tls
  caSecretName: klioserver-dc-a-ca

  image: registry.dev:5000/klio-testing:dev
  imagePullPolicy: Always
---
apiVersion: v1
data:
  htpasswd: a2xpb0BjbHVzdGVyLWRjLWE6JGFwcjEkTkFaT2IxZi4kSktpNkYvajNiNzJSUXFma3JVSkFHMQprbGlvQGNsdXN0ZXItZGMtYjokYXByMSRMLzNqYmU3RyRsNmk5V1gvNFBYc01GOUdNYnRrMm0xCg==
kind: Secret
metadata:
  name: klioserver-dc-a-users
  namespace: dc-a
---
apiVersion: v1
data:
  password: cGlwcG9waXBwbw==
  username: a29waWE=
kind: Secret
metadata:
  name: klioserver-dc-a-adm
  namespace: dc-a
---
apiVersion: v1
data:
  password: dGhpc3Bhc3N3b3Jk
kind: Secret
metadata:
  name: klioserver-dc-a-encryption
  namespace: dc-a
---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  name: selfsigned-issuer
#  namespace: dc-a
#spec:
#  selfSigned: {}
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: klioserver-dc-a
#  namespace: dc-a
#spec:
#  secretName: klioserver-dc-a-tls
#  commonName: klioserver-dc-a
#  dnsNames:
#    - klioserver-dc-a
#    - klioserver-dc-a.dc-a
#    - klioserver-dc-a.dc-a.svc
#    - klioserver-dc-a.dc-a.svc.cluster.local
#
#  duration: 87600h # 10y
#  renewBefore: 78840h # 9y
#
#  isCA: false
#  usages:
#    - server auth
#
#  issuerRef:
#    name: selfsigned-issuer
#    kind: Issuer
#    group: cert-manager.io
#
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: klioserver-dc-a-ca
#  namespace: dc-a
#spec:
#  commonName: klioserver-dc-a
#  secretName: klioserver-dc-a-ca
#
#  duration: 2160h # 90d
#  renewBefore: 360h # 15d
#
#  isCA: true
#  usages:
#    - cert sign
#
#  issuerRef:
#    name: selfsigned-issuer
#    kind: Issuer
#    group: cert-manager.io
#---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  name: klioserver-dc-a-ca
#  namespace: dc-a
#spec:
#  ca:
#    secretName: klioserver-dc-a-ca
#---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXakNDQWtLZ0F3SUJBZ0lSQUlMMDIwUXNXVEZkSytoR3d0KzhzdkV3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXhNUGEyeHBiM05sY25abGNpMWtZeTFoTUI0WERUSTFNRGd5TlRFd01EVXpORm9YRFRNMQpNRGd5TXpFd01EVXpORm93R2pFWU1CWUdBMVVFQXhNUGEyeHBiM05sY25abGNpMWtZeTFoTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcmhXZFpsd0M3WjE2TVNJVzhWeEdxK0hTREtRelpXM2wKaXRJcGRtVnN3a25YR0JvZDY2SmdaWXFXbmJhbEp1d3JVYUNMSlRKMjdrT2ZLUnkyeHJhUjVRcUhpVzhKczBkVQpwTzA5ZUdlREJESVRiTy85aWQvV2ZmZzh2bFlGU0krZ2dSemk5cEdFcEdnQVMvUUtlYkxKMGRDWjROZzBGaStjCnpFaUU0U1RPNUtSeW5jcWE3T3YyODQ5d3lNS0o0VGpxMStVZHVMeWFGanpOTFJDVmpyMzZkM3pxV3ZrUURNaGYKTWJvU1JsNDJQTU15K0RQaVVXTnRVZXJ4ZG9XSXg0WWRDcm1MakMrajNzRnFkRWlFdlR1TXluOVpzS1AzbmEzQgpBcUU1ZVMxcGZiVmtFYmpaYWVFbHdyb09uS0RqZkk1N2ZiYkF0UFQ4MDI5cllqbWd5ai83QXdJREFRQUJvNEdhCk1JR1hNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdjZ1lEVlIwUkJHc3cKYVlJUGEyeHBiM05sY25abGNpMWtZeTFoZ2hScmJHbHZjMlZ5ZG1WeUxXUmpMV0V1WkdNdFlZSVlhMnhwYjNObApjblpsY2kxa1l5MWhMbVJqTFdFdWMzWmpnaVpyYkdsdmMyVnlkbVZ5TFdSakxXRXVaR010WVM1emRtTXVZMngxCmMzUmxjaTVzYjJOaGJEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFxcU81L0lXWUt2SmNZVDJRU0dCWjRBUEgKRDQxZUJOclBSK0gvK2ZVQ0ZZMWgvS0l5VThyR3Y3bFpLcnZjUmtxaVVHRm0vbDdxMDdNelhjOWo1TUt0b1AyawpnUVZ1OUVtenBnemxscFRoMTI3TXZMS2pTUDIycTBYUWpEdVF4Smc4ckYrbTJ0RGdQeTE5Qlh5ZXJRTXo2c0swCjd4SDNyNXpBS3E2eC9lS3d6Tnl3QkZvYzlzV3B6Z0RvZHEzKzdxQm9mekloeExFNUwzS1JEOGI2dEJsTHFJUHQKbmtnNnFGL2RNYjFnU0xkZ3pnU1QzWkxYQ1ZERXR5QUdGeVVwZWZVREttOG9hRm04TlFiYWlGdWpVenlHdHdHMApNQTJsS0ZQcmk3TTlxSlFTaFFCZ3JvYTdub1NzeFQ5Tjd1Qm95TGpURE5VaE11QitIZDdwYzk3VU1TMmViUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXakNDQWtLZ0F3SUJBZ0lSQUlMMDIwUXNXVEZkSytoR3d0KzhzdkV3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXhNUGEyeHBiM05sY25abGNpMWtZeTFoTUI0WERUSTFNRGd5TlRFd01EVXpORm9YRFRNMQpNRGd5TXpFd01EVXpORm93R2pFWU1CWUdBMVVFQXhNUGEyeHBiM05sY25abGNpMWtZeTFoTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcmhXZFpsd0M3WjE2TVNJVzhWeEdxK0hTREtRelpXM2wKaXRJcGRtVnN3a25YR0JvZDY2SmdaWXFXbmJhbEp1d3JVYUNMSlRKMjdrT2ZLUnkyeHJhUjVRcUhpVzhKczBkVQpwTzA5ZUdlREJESVRiTy85aWQvV2ZmZzh2bFlGU0krZ2dSemk5cEdFcEdnQVMvUUtlYkxKMGRDWjROZzBGaStjCnpFaUU0U1RPNUtSeW5jcWE3T3YyODQ5d3lNS0o0VGpxMStVZHVMeWFGanpOTFJDVmpyMzZkM3pxV3ZrUURNaGYKTWJvU1JsNDJQTU15K0RQaVVXTnRVZXJ4ZG9XSXg0WWRDcm1MakMrajNzRnFkRWlFdlR1TXluOVpzS1AzbmEzQgpBcUU1ZVMxcGZiVmtFYmpaYWVFbHdyb09uS0RqZkk1N2ZiYkF0UFQ4MDI5cllqbWd5ai83QXdJREFRQUJvNEdhCk1JR1hNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdjZ1lEVlIwUkJHc3cKYVlJUGEyeHBiM05sY25abGNpMWtZeTFoZ2hScmJHbHZjMlZ5ZG1WeUxXUmpMV0V1WkdNdFlZSVlhMnhwYjNObApjblpsY2kxa1l5MWhMbVJqTFdFdWMzWmpnaVpyYkdsdmMyVnlkbVZ5TFdSakxXRXVaR010WVM1emRtTXVZMngxCmMzUmxjaTVzYjJOaGJEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFxcU81L0lXWUt2SmNZVDJRU0dCWjRBUEgKRDQxZUJOclBSK0gvK2ZVQ0ZZMWgvS0l5VThyR3Y3bFpLcnZjUmtxaVVHRm0vbDdxMDdNelhjOWo1TUt0b1AyawpnUVZ1OUVtenBnemxscFRoMTI3TXZMS2pTUDIycTBYUWpEdVF4Smc4ckYrbTJ0RGdQeTE5Qlh5ZXJRTXo2c0swCjd4SDNyNXpBS3E2eC9lS3d6Tnl3QkZvYzlzV3B6Z0RvZHEzKzdxQm9mekloeExFNUwzS1JEOGI2dEJsTHFJUHQKbmtnNnFGL2RNYjFnU0xkZ3pnU1QzWkxYQ1ZERXR5QUdGeVVwZWZVREttOG9hRm04TlFiYWlGdWpVenlHdHdHMApNQTJsS0ZQcmk3TTlxSlFTaFFCZ3JvYTdub1NzeFQ5Tjd1Qm95TGpURE5VaE11QitIZDdwYzk3VU1TMmViUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBcmhXZFpsd0M3WjE2TVNJVzhWeEdxK0hTREtRelpXM2xpdElwZG1Wc3drblhHQm9kCjY2SmdaWXFXbmJhbEp1d3JVYUNMSlRKMjdrT2ZLUnkyeHJhUjVRcUhpVzhKczBkVXBPMDllR2VEQkRJVGJPLzkKaWQvV2ZmZzh2bFlGU0krZ2dSemk5cEdFcEdnQVMvUUtlYkxKMGRDWjROZzBGaStjekVpRTRTVE81S1J5bmNxYQo3T3YyODQ5d3lNS0o0VGpxMStVZHVMeWFGanpOTFJDVmpyMzZkM3pxV3ZrUURNaGZNYm9TUmw0MlBNTXkrRFBpClVXTnRVZXJ4ZG9XSXg0WWRDcm1MakMrajNzRnFkRWlFdlR1TXluOVpzS1AzbmEzQkFxRTVlUzFwZmJWa0VialoKYWVFbHdyb09uS0RqZkk1N2ZiYkF0UFQ4MDI5cllqbWd5ai83QXdJREFRQUJBb0lCQURIN0FyWGd0UGFEd0JGYgpPRHNUd3phV0h6aUI3RCt5emJTTm9sbmJ4TjREVlQ0V1FZRGxuY2VKZ3JURk82VnhLUDdHbVN5VTBKQ1gyWnAwCkpBWHBaUG5kakF4cFZOK2tHeWsrOCtjZDBQL2pZTEJtTnVUZTN6WkxqeVVXalczSHpzMUMvZWJNNE1oVEU4SzYKemtjaWpjOHZsUDU1Rkh0S01EcDJsN0FNWVZwRFkxT3pkVHZEa0pvVTZ2V3ZaaEFwRGl3b1grdDFXRUxKeFgxTgpMQmJKMHBLQmdDTHBoTnA0Q2lHMjRxKzZWTUdUMi96c3ZOV01EbFRJZEo5d1RDQ1NjUDNRaWNvZTJhbzZzTC9XCktSRGdqbzlmVDVvRVJXL0lVaktMU1l3WS9pN3ZSejJMMUlxdzVOcFVVaVBCbUQyU1RtTzFNR0N0cUVwZ2lFUzgKWGZwU1VBRUNnWUVBeXRwZ1hPWlllaFUvWmIyemU5RlM2V3FNVjY3UVR5azRvYzVIOENLbGRGWVplRktBUEprZAo2QUYxUTRacm9hVmxWWDVuOG41aDNodzVGU1k1UHNmeUhDb3lhYTNBTWR6clh0bVFCVEZFRW9zOGhKbHdSbDBRCi8ybXVCS096YmdxNkpoNGNBQWVvRnZ0NVlYVHdtSDZ1WnZIeEhqZjluOTRwemVOaDJ6R2lsVE1DZ1lFQTI3R3cKcHI1bTZVNy8zWjY2TnY1SEhkK0xITmdBUlBBSlNBSTdCWllIYXNCMldTZ2ZkL2dQMkZ5cHdTbkl1VGZuQ29hOQpPQkMxVVBDWWV4NHB2TFVtRE5pcm1hdGhCc2dXL0FGZi93UC93ZDM3NFY4MElweTVkc2h3cGJhSHhqbkRwZFRnCmhYeEZlTnRmYXhZQlU3WGxKRnIySDVRUlhSRUVEaStLckhpY1l2RUNnWUJHT01pSkFGaDZrcVpxc3Z2U0RnbDAKc2lTNUtkUUV3MUZPZWhsZklLOUVFWllwbCsyNmpJclV5TVJ1UnJjMXN3cmNTTEQxT2hqcENiNGMreWx2K1Vsdgp4SS9GRTVmbjZ3RXp5WDdZdlZCQ1Z4N3hEQ2pZd3RqaWdoUHltVFRCRUVlV2NHL2k5c09TaVNWZ3ZsbVhnS3NoCkNmb2RLdWJLazk3RzNrTCszVFRhRHdLQmdIMUQrKzJYY3laa25RL0lpWFVCMTVyNDgyRW02RUJtZldSSm9VMjIKRmRTUW1PcU5MaVJCbFFkUkRwbk5NVjRxdWRvT3FhVm1JWHhkTXhSQVJwd0t6ZjlWSzhNYkxOK3BCekg1dHJxNQpsUUw5aDdraGg2Q1VyRXRHVHJTdU53eVhzeTdEQ3FJU0VhcXZxdUJzVTZWZmVhQVpIVzAwQ0JLQXVVYzlaRnlqCkNNaUJBb0dBWFZXcGIwbGYwdEFxZ1FQb0Z6bE5NVHlKUDFpdngrZ1pPMmlxSG9scW9DWXJkN1NmWkN1Vm5IV3gKdjdkZFR2cWVJbXE3Rm1NdzVodHZxS0dZcytOZTRYUTFwdlNIOWhISnViMXdCQ08xUjIyNW1tS2UwaVpPWC9ZMQpkU1dXSzh1eGhrWDBRRlhwVVh1YzA1bWZjTHcvaGNIR1dlTDdCQndTWXl5MkNmN2t2azg9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: klioserver-dc-a-tls
  namespace: dc-a
type: kubernetes.io/tls
---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXVENDQWtHZ0F3SUJBZ0lRUUtDUDZtdkpiWE1BdThNcno4RE1HVEFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFERXc5cmJHbHZjMlZ5ZG1WeUxXUmpMV0l3SGhjTk1qVXdPREkxTVRBd05qQTFXaGNOTXpVdwpPREl6TVRBd05qQTFXakFhTVJnd0ZnWURWUVFERXc5cmJHbHZjMlZ5ZG1WeUxXUmpMV0l3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURwVVFaK3lEQlF5dGwxVlY2c3NqblJuV2E1Z1B3cWkyOTcKMGR1U1ZxN3NsZUhnL3FzTXY2K1ZmQXJ0Ym9vdTAyT2VmVWd4Rm4wOXNGR0ZqbU53YUV4YktkSU1JR3QvT3FSbgpTY0hLbDVFbEVEL1ltbTdxK2h1TVgxdi9XQm1aS2Mrc3NMQjJod3JCNjhJNTJEZFpOOFdsRm9uR0Y1STB1K2VmCk81dElaTzM3TDdrbWJUQjhwRURsZTY5RjVlSUpDT0dQVHg1a2t1VkdkU3ZRaFFEM0V2YzhDajJ2a0hkTGlQWEMKb0pIWUJrdC9kMXNnYkF0M0RpYlVqVHNyT29VTVZnUDlRcTI2aE5jbUhYQWRFZ1JsY0Q4Y291Y0F0bk9XMFNJQQpXSndkSS9SaEo3YTZjV0dwVHVGMkQ3amVNTGxFUitBVnlHMVh6SUZIOGFUcUJEb3dwcUovQWdNQkFBR2pnWm93CmdaY3dFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQnlCZ05WSFJFRWF6QnAKZ2c5cmJHbHZjMlZ5ZG1WeUxXUmpMV0tDRkd0c2FXOXpaWEoyWlhJdFpHTXRZaTVrWXkxaWdoaHJiR2x2YzJWeQpkbVZ5TFdSakxXSXVaR010WWk1emRtT0NKbXRzYVc5elpYSjJaWEl0WkdNdFlpNWtZeTFpTG5OMll5NWpiSFZ6CmRHVnlMbXh2WTJGc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWRJKzhqb0VCUVM5SlFTUnB1QVk4Z0lmdXQKK0xvRld4bVAreVltN0lLaS83clRjengvNFQyblp6TURrb0t3UDM0MVpVSXhUSEJLZXpwV21vYm1xL1ZIcFhjSwp6R1B5dGhKRlFhOGZHQ0grTVFTL0NEbDRxSWZFc3lOM045bDdFek53ZHd4U3R5alVjL3U1NGtsS0dtS0hmazFxCkZTRU5xNEJJSGxHaDU2MFFwVS9zb1lvVTh5eWx0L1EvOHpzUlBoL2hnNjJtMUJ2KzZ5dnQzUEJGSG9BU0lFSmkKSVJlTFdReE9qNWVXb1JsMitraDhQbFRrTnIwNWFoWkhoRVI2dmNvMnh0U2RjZVg4enl4UHFUdWNTYVpLRml4Kwo5VEp4R0s5MjMzQTBqamZBYzNvSU9mT2Zmamo4QTRnS1VCSTdBSEs3TjdRQ0k5M29GdjQ1QXFMalJDWS8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXVENDQWtHZ0F3SUJBZ0lRUUtDUDZtdkpiWE1BdThNcno4RE1HVEFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFERXc5cmJHbHZjMlZ5ZG1WeUxXUmpMV0l3SGhjTk1qVXdPREkxTVRBd05qQTFXaGNOTXpVdwpPREl6TVRBd05qQTFXakFhTVJnd0ZnWURWUVFERXc5cmJHbHZjMlZ5ZG1WeUxXUmpMV0l3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURwVVFaK3lEQlF5dGwxVlY2c3NqblJuV2E1Z1B3cWkyOTcKMGR1U1ZxN3NsZUhnL3FzTXY2K1ZmQXJ0Ym9vdTAyT2VmVWd4Rm4wOXNGR0ZqbU53YUV4YktkSU1JR3QvT3FSbgpTY0hLbDVFbEVEL1ltbTdxK2h1TVgxdi9XQm1aS2Mrc3NMQjJod3JCNjhJNTJEZFpOOFdsRm9uR0Y1STB1K2VmCk81dElaTzM3TDdrbWJUQjhwRURsZTY5RjVlSUpDT0dQVHg1a2t1VkdkU3ZRaFFEM0V2YzhDajJ2a0hkTGlQWEMKb0pIWUJrdC9kMXNnYkF0M0RpYlVqVHNyT29VTVZnUDlRcTI2aE5jbUhYQWRFZ1JsY0Q4Y291Y0F0bk9XMFNJQQpXSndkSS9SaEo3YTZjV0dwVHVGMkQ3amVNTGxFUitBVnlHMVh6SUZIOGFUcUJEb3dwcUovQWdNQkFBR2pnWm93CmdaY3dFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQnlCZ05WSFJFRWF6QnAKZ2c5cmJHbHZjMlZ5ZG1WeUxXUmpMV0tDRkd0c2FXOXpaWEoyWlhJdFpHTXRZaTVrWXkxaWdoaHJiR2x2YzJWeQpkbVZ5TFdSakxXSXVaR010WWk1emRtT0NKbXRzYVc5elpYSjJaWEl0WkdNdFlpNWtZeTFpTG5OMll5NWpiSFZ6CmRHVnlMbXh2WTJGc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWRJKzhqb0VCUVM5SlFTUnB1QVk4Z0lmdXQKK0xvRld4bVAreVltN0lLaS83clRjengvNFQyblp6TURrb0t3UDM0MVpVSXhUSEJLZXpwV21vYm1xL1ZIcFhjSwp6R1B5dGhKRlFhOGZHQ0grTVFTL0NEbDRxSWZFc3lOM045bDdFek53ZHd4U3R5alVjL3U1NGtsS0dtS0hmazFxCkZTRU5xNEJJSGxHaDU2MFFwVS9zb1lvVTh5eWx0L1EvOHpzUlBoL2hnNjJtMUJ2KzZ5dnQzUEJGSG9BU0lFSmkKSVJlTFdReE9qNWVXb1JsMitraDhQbFRrTnIwNWFoWkhoRVI2dmNvMnh0U2RjZVg4enl4UHFUdWNTYVpLRml4Kwo5VEp4R0s5MjMzQTBqamZBYzNvSU9mT2Zmamo4QTRnS1VCSTdBSEs3TjdRQ0k5M29GdjQ1QXFMalJDWS8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBNlZFR2ZzZ3dVTXJaZFZWZXJMSTUwWjFtdVlEOEtvdHZlOUhia2xhdTdKWGg0UDZyCkRMK3ZsWHdLN1c2S0x0TmpubjFJTVJaOVBiQlJoWTVqY0doTVd5blNEQ0JyZnpxa1owbkJ5cGVSSlJBLzJKcHUKNnZvYmpGOWIvMWdabVNuUHJMQ3dkb2NLd2V2Q09kZzNXVGZGcFJhSnhoZVNOTHZubnp1YlNHVHQreSs1Sm0wdwpmS1JBNVh1dlJlWGlDUWpoajA4ZVpKTGxSblVyMElVQTl4TDNQQW85cjVCM1M0ajF3cUNSMkFaTGYzZGJJR3dMCmR3NG0xSTA3S3pxRkRGWUQvVUt0dW9UWEpoMXdIUklFWlhBL0hLTG5BTFp6bHRFaUFGaWNIU1AwWVNlMnVuRmgKcVU3aGRnKzQzakM1UkVmZ0ZjaHRWOHlCUi9HazZnUTZNS2FpZndJREFRQUJBb0lCQUFjcnN1ODBsUkxEWmd6Qgp1ZTRybzA0VUkxbCsvU2R5WXRQRGxUQ1ptUVdBQnBISVNGYTdYajhlNUtTdkVBb24rOWpROFV4MXVSV3JSOHlICm5mcGQxd3lIQllQVEdOcXZsSUpYVzhiSk5pTmlFM2QyajV6ditvQmU4ZW5qVTNyaFozMHNPMm5GOVNJVkI5d2kKRHovU0hURW1VTWV2TThXOTcrTU93SVpvZUlEQjl4cVRLSUFjcUpjL2EzM2x6dG1LaGVLbHBOTEdRM2dZZzZHSAozR3lMVTdGMWgvVzFVY1BDZlFubHJEYXJRRVpqajFhR2w3WDY4aWtjZllpZXYvNksveE4yYnc0RDJzeDNPcTJxCkxtbURrc0VtQkkrN2V5QUFIaWhveHNUcG0wbkJuNDdYaHJlem5TTVdPcWoyRjNGVFA4RXZsb0lWTDRRRkhCZFUKcjdDM0FKRUNnWUVBOGNEUllrNDdwUFJUK1I2bXZJbkd2TTlnN2hDcXpHYTRycjluajEya2dKcUJBdWE1NnBEUApEQkJrMkFZU3F2akxDSkEwN3k3ckdTUUE1azZyYytzTGRvREdPSEZkaUhuQm8rQlVudW56NDUrNEpSbGR4Y2kzCm9oaUt0czl6M0dXQ0g3VXV1QkJUWFVobTJ3YjNZV0xlbHFudjJPV2NRcEZvU2ZKVlkwQ3Rub2NDZ1lFQTl4RHQKcFkxT0R1QWw2aGlLbjZ0M1pPTVJ0MkVkSGVNRWZHWjJTbTFjTzV2UVJsaHNRdTB0WGxrbUxuUEtIOFZuY2VVTQpqYlVHNVdyMzdUWk45emM2dlVSNUZuMTZlbTR0eTZxRTU0cTlSU2QxeWNwQzFoV3M4Q3JZQ25TYnRRZU43MnZlClNUUUdYWlFueXdHTnZFK1gzdUkwNUVFZDZ1MzVLV1R3WGxKVm9ra0NnWUFENFhCNi8zNTltMTV0dFV3LzRvWksKS1pvSXVFUEZuRENDdlpmUCtWVFdxNlErZzYyZ1VrckFpdExUbE9WZjBUYVJJSjk0NTJ2bXIybEVTU2IvYVZwNQp3SDl1RUlQTDJRaCt0TzhtemVLWVdNdi83SFJRNUhQdUtpNnYySXlua1FtUnNMcmJRWWZWQzRCN0s1VjAvcjFMCjlkWmZ5Ty9GTWNoV3g0a1BXczV1cVFLQmdRRFhRbnlMM1UzQlVESTRnQ0ZuZEhHV0NQRUtvU1pKUDk1TXRNa2oKbDV6Z29xVVlaVG9PSmE5OW9KYlBxanJVNjUxeGNtczVuQnZpRHd6c05JQkJnSEZCTGtPQ0FObVJpaVdFYVpGYQpXMXNFd1ppeXMvTC9xK3I5WlpiTnBVTjB1cHhEbWV3V1E2bTRKcmwwK21tUFJKbkJxNzBCa21xS29jU1ErRTBsCklQOVRZUUtCZ0EzZytYWktENVMxdmRiMGdzSk5PajVsRzVpTG81VkQydzlYTjhHdFBiZlRIV2RKQ01HRjhQc3IKWnBHeUMyaTVQUE8zdW9KdDFEczhFK2NVc3pwdU1RRy9wZUJxSHFOY1V0Zks3cWRDbVlwREZEcjNPQnJmQ2JXNgpsOWlEMVZaRVVIajZmYTh4ZVErZkFRN0IweG9Dd3JINXgxemhLSjVmcHVZOHhyS0pCSDJICi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: klioserver-dc-b-tls
  namespace: dc-a
type: kubernetes.io/tls
---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQjIrb3p3WDVxUzFJMThGZVVtTEdkSjc0ZlF3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkxTVRBek1URXpNalF3TkZvWApEVEkyTURFeU9URXpNalF3TkZvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNOdEY2cDhwTlpGb1hCd3ZrN2NuL0xGTnZPRnkKQUQrdWxCMWhhdXBFV1UycEphQ1FSUkppTXB4dmZCZERlS3c1azZJYkZCTVUxZkRaY0lCV0NEcEJUek51N09wZApqVzd1Rk5GV2hSK1d2bXJEb092d0JKalRpTGU3dlVqV245bkpLM2RiRkNKSUJWclN6T3JGR1BSL2ZTTnBXODV1CjhvNDZoRGpRTXVwM0YzK3h4Y21TSjdQamVYcnJ3ekkrdDRyNXRtQ3VsZFhNSGxjUzZsMlVUeEQ4ZENmbjNEbjYKZ2VsM2RES1g3WWlSVmJYU1R2TkZZMnVhNVVBQUVmaFFzWTA3OWdETXJQS1kzYkhvWUU1alY5ZEtTcWVKd21YVgpNUUZXYnRTZ0xWb3Y1UUxubElQZnlQeHFHbWZvcHpaWjZ4Z1YvNVorQXMrWFFyNlhYaDFkL3BoQUlRSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKaFo1d2dseXJmYW5KYlk4N0M2VGxyWXZ3blhVd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBR3VkSFdKQnBxNApZVHIxc3JFaCtyMFZDUEVGaTEyOHlxdFdtSUFQR2svZlo4R2NScHg2ZFRlSy8reVVGUVAwcFVieXlPKytBSC9xCkNNOVlVU1hvanV5dW5NaFdXQmdMTDczNlNBVDBiOFNoY2F4djRIcDJ6N0R2WFNFdUsrTzZlbTFLWmI1Z0pWZCsKVHF4R0Y5ZHNCZE5FUHBlR25JVXZjR1d1aGIvWEVnYlA4SVJ1ZXcvLzVLWkNmT3FYczFobWFhMVRkTjZmZU9hYgpCbnZHUmtmZFlBS1lkTkFGckt1enV3N1MzdFRNMkNhZDVzRlMwLy81MHNRMHY1QnNFamVkRkdMcDFNZ0xIVlpLCitCRGo3SHVPOGpJa0ExMjFkUy9jejd1VW1RMkZ2R2xTY0VhUVJuNXNGUldxMGJQYXVaL2dtenQzNjMyektCQXMKc3FuZ0pTcE1WR009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQjIrb3p3WDVxUzFJMThGZVVtTEdkSjc0ZlF3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkxTVRBek1URXpNalF3TkZvWApEVEkyTURFeU9URXpNalF3TkZvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNOdEY2cDhwTlpGb1hCd3ZrN2NuL0xGTnZPRnkKQUQrdWxCMWhhdXBFV1UycEphQ1FSUkppTXB4dmZCZERlS3c1azZJYkZCTVUxZkRaY0lCV0NEcEJUek51N09wZApqVzd1Rk5GV2hSK1d2bXJEb092d0JKalRpTGU3dlVqV245bkpLM2RiRkNKSUJWclN6T3JGR1BSL2ZTTnBXODV1CjhvNDZoRGpRTXVwM0YzK3h4Y21TSjdQamVYcnJ3ekkrdDRyNXRtQ3VsZFhNSGxjUzZsMlVUeEQ4ZENmbjNEbjYKZ2VsM2RES1g3WWlSVmJYU1R2TkZZMnVhNVVBQUVmaFFzWTA3OWdETXJQS1kzYkhvWUU1alY5ZEtTcWVKd21YVgpNUUZXYnRTZ0xWb3Y1UUxubElQZnlQeHFHbWZvcHpaWjZ4Z1YvNVorQXMrWFFyNlhYaDFkL3BoQUlRSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKaFo1d2dseXJmYW5KYlk4N0M2VGxyWXZ3blhVd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBR3VkSFdKQnBxNApZVHIxc3JFaCtyMFZDUEVGaTEyOHlxdFdtSUFQR2svZlo4R2NScHg2ZFRlSy8reVVGUVAwcFVieXlPKytBSC9xCkNNOVlVU1hvanV5dW5NaFdXQmdMTDczNlNBVDBiOFNoY2F4djRIcDJ6N0R2WFNFdUsrTzZlbTFLWmI1Z0pWZCsKVHF4R0Y5ZHNCZE5FUHBlR25JVXZjR1d1aGIvWEVnYlA4SVJ1ZXcvLzVLWkNmT3FYczFobWFhMVRkTjZmZU9hYgpCbnZHUmtmZFlBS1lkTkFGckt1enV3N1MzdFRNMkNhZDVzRlMwLy81MHNRMHY1QnNFamVkRkdMcDFNZ0xIVlpLCitCRGo3SHVPOGpJa0ExMjFkUy9jejd1VW1RMkZ2R2xTY0VhUVJuNXNGUldxMGJQYXVaL2dtenQzNjMyektCQXMKc3FuZ0pTcE1WR009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBM050RjZwOHBOWkZvWEJ3dms3Y24vTEZOdk9GeUFEK3VsQjFoYXVwRVdVMnBKYUNRClJSSmlNcHh2ZkJkRGVLdzVrNkliRkJNVTFmRFpjSUJXQ0RwQlR6TnU3T3Bkalc3dUZORldoUitXdm1yRG9PdncKQkpqVGlMZTd2VWpXbjluSkszZGJGQ0pJQlZyU3pPckZHUFIvZlNOcFc4NXU4bzQ2aERqUU11cDNGMyt4eGNtUwpKN1BqZVhycnd6SSt0NHI1dG1DdWxkWE1IbGNTNmwyVVR4RDhkQ2ZuM0RuNmdlbDNkREtYN1lpUlZiWFNUdk5GClkydWE1VUFBRWZoUXNZMDc5Z0RNclBLWTNiSG9ZRTVqVjlkS1NxZUp3bVhWTVFGV2J0U2dMVm92NVFMbmxJUGYKeVB4cUdtZm9welpaNnhnVi81WitBcytYUXI2WFhoMWQvcGhBSVFJREFRQUJBb0gvZDhYSCtrcXI0K0VpTjN4bQorNG90K3JHQ1RHeWhrU3VpckZ0Q3BEaTlMYkVhMzNlMEd4YXlmOEFCWUhVOVRMUVoyc3ZrT05RZ1RlWFFCZ2c5CjlUaE5NdEV4MXZTWUhQRGhMTDVhV0N6MEUxQW9ja2VCdUZIVHUzdm8xSk9CSnRvZnZ2TFE4ZStsZEpkTXV0U1gKRHh3MEIzNnN6MGVramp1VDFjdWtjcU1LU0RNZ2xXZDdjMktjMGdqdGo1Z0RMQTFTbjhhakkrQVNvZW8rNWRUegpBV3FiS3lGeHE3ZHpVdkdvM2lFNzE3ZklpRHpUTldNNlN4ODZJYnpJZ3FyNE9ZcTRmN2JFRnpKU0lsQjZZdVF1CkFZZW05SExqVWFhTXJhbFJEMndORXVVSWN1Z0M3T3d6ajFEcGNKam9sc3FvbEtVSC9WY21MQ0ZDWktnOUpETlYKaEJZdkFvR0JBUGZXMSthTzRLcHFDSGd1cnBNN1htbVhEUDM5MTlhckRBWXdrdG8xRmVCbVBVd1BqODBrTHZ2OAo2UXJBRVQ5V3NUNURqQnQwejR1N21uN1FNcjhHbjUvcDZnZ1pwZVIxT1NsRWZxT3VPYlovNUF1cFhRZU9zeXN5ClZFVXp0SEcvcXZGYTk2RlpDZXhYUmlsaW1STXRha3VQb21BZ0phRUVFTlVxM2JsYXBQR0RBb0dCQU9RZytzVEIKOFlmNGJ1dVJGL2kvVytaMmJMY3p5QmVNaENFTUF2RWExOTV1NXJhWWJsVStSTTdLV0d4WVJlcVU4L0JYT2hyWQp3bS9QRFRxNjhubVdVUG0wbjFoemFEaEJNVDJwdW12ejZKUnZUWGFKSXR4a3dsaWVaNUIwKytkTzhiSlBMcFZ4CkpQSEVDWERkU3NPLzRzQmEvQ2llT3lUcVVhQW13cHVpM2dxTEFvR0FObjExQUlyL1dGaHh2a0s5UFQrN1ZVblIKb0hKVUp5MTZPazRwcTNJcWVpamdaejJ3cHpEQ1o4TEdWZ2UrZ3dlRGRxWVJRdVFlMGFFUXFic0t2VGN1bDFFdApsRlJYUmZDRC9jL0NiQ2hkSmdQZVZyWUk3eVZ2dlJxV3JwUmNvdm02RXRDbVMwSXhUVll1NWVCNHVWK3QxQ2tqClVURWdOTk9aQTlVbDVKL0tUaE1DZ1lFQW5hRThKV0J0YUNwOVdrQXpkQ21sY3FVNWtZMHlJVE55eVBMbnhYbHEKMThPQm40SE1HeEtmc05PWUxhVUJDb3BKMURReGJnT0F0b2syOXZIZVFhMWYzbXEwQUFZZWFXQ0NpYjBSbHk0OQo4dkxGYjdacVpDY3JNdGloYnV1bWM3blV3QVIraDd4YWJzT3FVbFpXSnRRYjloWG9UcGltL1diN1o5SGdmbklYClF1a0NnWUVBdDB5T2xWc1FhcHpIQm5TdWNwbFZKaGUvMDRUeTZIL3FtMnBZdzhtUFJZZ0xVMGJTUnkvbXBZY0wKMk04bzREc0ZtNW1FV0Y2cUNpdHNjRUpjUHMrM3Bad0Q3dU0xZkY5UVVzQ3lhZG95ckJJcVhJKzlPNVFiNUwrZAo2OW54Q1FadmRQQWFHK2VTcmxmTHZUdVBtbTlDbDVJenVEa2xVRzBOcHRHWlRPOWdIeGs9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: klioserver-dc-a-ca
  namespace: dc-a
type: kubernetes.io/tls
