apiVersion: v1
kind: Namespace
metadata:
  name: dc-a
spec: {}
---
apiVersion: klio.cnpg.io/v1alpha1
kind: Server
metadata:
  name: klioserver-dc-a
  namespace: dc-a
spec:
  tier1:
    cache:
      pvcTemplate:
        resources:
          requests:
            storage: 1Gi
        accessModes:
        - ReadWriteOnce

    data:
      pvcTemplate:
        resources:
          requests:
            storage: 1Gi
        accessModes:
        - ReadWriteOnce

    encryptionKeyFile:
      fileReference:
        volume:
          secret:
            secretName: klioserver-dc-a-encryption
        path: encryption-key

    identityFile:
      fileReference:
        volume:
          secret:
            secretName: klioserver-dc-a-encryption
        path: secret-key

  queue:
    pvcTemplate:
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce

  tlsSecretName: klioserver-dc-a-tls
  caSecretName: klioserver-dc-a-ca

  image: registry.dev:5000/klio-testing:dev
  imagePullPolicy: Always
---
apiVersion: v1
stringData:
  secret-key: AGE-SECRET-KEY-1P7TWJ8H837DPVLSRVHAP0ZCZVHXJRTUS7S0A5VZAR49URW0Z9Q0SFW4HVM
  public-key: age16y2zu5qptkzateyuarcahs0am75qjpu0xd2ty2dvm5jusnfzxg0scjh5uu
  encryption-key: |
    -----BEGIN AGE ENCRYPTED FILE-----
    YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMzJERW1QTUhjNGdlNmdi
    WmFLZ3FLL1lZclduUWEvZkJncGdJZmtVd1FzCmZwSHVTcWNMRFN6a2xpY0NHNVRv
    MlltSlNRY1B4bmNoOUxuZzZ5RENSSmsKLS0tIGNYUUNzSGVqNUZhS3VodnZ1cXNP
    T3JHS3JRSUNkR1RyeEROYnZYNnNSV00KUd3HyxvvqCyW6hC1sWNDn/xeptHsoz/e
    hxCgWoSJvfSfNk174njMwEeW+ic=
    -----END AGE ENCRYPTED FILE-----
kind: Secret
metadata:
  name: klioserver-dc-a-encryption
  namespace: dc-a
---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  name: selfsigned-issuer
#  namespace: dc-a
#spec:
#  selfSigned: {}
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: klioserver-dc-a
#  namespace: dc-a
#spec:
#  secretName: klioserver-dc-a-tls
#  commonName: klioserver-dc-a
#  dnsNames:
#    - klioserver-dc-a
#    - klioserver-dc-a.dc-a
#    - klioserver-dc-a.dc-a.svc
#    - klioserver-dc-a.dc-a.svc.cluster.local
#
#  duration: 87600h # 10y
#  renewBefore: 78840h # 9y
#
#  isCA: false
#  usages:
#    - server auth
#
#  issuerRef:
#    name: selfsigned-issuer
#    kind: Issuer
#    group: cert-manager.io
#
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: klioserver-dc-a-ca
#  namespace: dc-a
#spec:
#  commonName: klioserver-dc-a
#  secretName: klioserver-dc-a-ca
#
#  duration: 87600h # 10y
#  renewBefore: 78840h # 9y
#
#  isCA: true
#  usages:
#    - cert sign
#
#  issuerRef:
#    name: selfsigned-issuer
#    kind: Issuer
#    group: cert-manager.io
#---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  name: klioserver-dc-a-ca
#  namespace: dc-a
#spec:
#  ca:
#    secretName: klioserver-dc-a-ca
---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQ3lFOWRlcE1LeWl1dUZtUDBVTWM1SkFhVkxJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkyTURJeU56RXpNekExTjFvWApEVE0yTURJeU5URXpNekExTjFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXFiK0p6a1RWdDlWUFBMMjRTY1l3Tmw1azJsUFoKY2JvcWk5bTN0cnZWd0tmdHZJMGliSlkwSnY4WmV5c094T0JoakpRN0crWkR6YzY2WHYrQ2o4aVhtY1NIQXVmWApXbjdNbmozNjlsYzk1bFJvQ3ZPb2JrK0pWaldGZmErREN4MVBiMGczTlFJYlRiNXE4cXhOVUp0QnVFYzFKNmNmCk1HcUZvRkhqKzd4SlM5SXBXc3p3SjdWWmFDQkpkY2t6bTVLZzBqNXp5UUNXbGU2RXltNGZKTU85V1pxQlB5bDcKaWNadjhqOEltUmUrdTdqK1NZd2NQdkZxMXk1VU1SZGlpUUR0eURaRmE0TVF0S3RqWUxLZWN0YWNGdFYydUhQTgpsdW9mNTdwZnJNdTRBM3FsRC9GdUw0YURVdGhUMjFBRm80L3NOL1dFaDYvLzJtdHVKU0pvb0FvamZRSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKa2JyalU0L3ZPYlNLYkU0d2FkcmZNUnZ0WEVNd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEVjRMSGpJVm5YVgoxOUcxRGpHMWNqSFJvNXFnTmFDdllOVmd6T2NTaXEzY0ZhdFMzYkFLMFBWSDNCN1p1RzJycHppMkhkRkkwUCtqCkN0dGNCakFBVG1wVWJaay9hcm5Mc1NuajkvMW9VTVpXRXUwTUp2YklLcUxVMVo2VEUxRm5Id0o2UE5uM1J0MDYKcEcyR1R1UmJoSHpjSFEyVjBPU3YzZklRVTJTREVvWk5KazdpYnJSbjdIVUlvSVJ3SlY2ekd2OVdrZjdtSUxmQwpLZVF0VlgvTGU1OTJYNVlpZG5ZSCtWT05hSE40b1hGbmdFWHlqVjhna3NRS3V2TUZwUEN0WXc2UU5sOEZZQzAzCjIxRjJRYU1FdmJTUW1uZ1Z1ODFMNXR4dEI4djIrVEZDNUZ3ODBiMmNhaFBXYkt6WlYzMVBvODZzUUtSMW9sR2oKRlpOVzBXQnl0N3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVQ3lFOWRlcE1LeWl1dUZtUDBVTWM1SkFhVkxJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkyTURJeU56RXpNekExTjFvWApEVE0yTURJeU5URXpNekExTjFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXFiK0p6a1RWdDlWUFBMMjRTY1l3Tmw1azJsUFoKY2JvcWk5bTN0cnZWd0tmdHZJMGliSlkwSnY4WmV5c094T0JoakpRN0crWkR6YzY2WHYrQ2o4aVhtY1NIQXVmWApXbjdNbmozNjlsYzk1bFJvQ3ZPb2JrK0pWaldGZmErREN4MVBiMGczTlFJYlRiNXE4cXhOVUp0QnVFYzFKNmNmCk1HcUZvRkhqKzd4SlM5SXBXc3p3SjdWWmFDQkpkY2t6bTVLZzBqNXp5UUNXbGU2RXltNGZKTU85V1pxQlB5bDcKaWNadjhqOEltUmUrdTdqK1NZd2NQdkZxMXk1VU1SZGlpUUR0eURaRmE0TVF0S3RqWUxLZWN0YWNGdFYydUhQTgpsdW9mNTdwZnJNdTRBM3FsRC9GdUw0YURVdGhUMjFBRm80L3NOL1dFaDYvLzJtdHVKU0pvb0FvamZRSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKa2JyalU0L3ZPYlNLYkU0d2FkcmZNUnZ0WEVNd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEVjRMSGpJVm5YVgoxOUcxRGpHMWNqSFJvNXFnTmFDdllOVmd6T2NTaXEzY0ZhdFMzYkFLMFBWSDNCN1p1RzJycHppMkhkRkkwUCtqCkN0dGNCakFBVG1wVWJaay9hcm5Mc1NuajkvMW9VTVpXRXUwTUp2YklLcUxVMVo2VEUxRm5Id0o2UE5uM1J0MDYKcEcyR1R1UmJoSHpjSFEyVjBPU3YzZklRVTJTREVvWk5KazdpYnJSbjdIVUlvSVJ3SlY2ekd2OVdrZjdtSUxmQwpLZVF0VlgvTGU1OTJYNVlpZG5ZSCtWT05hSE40b1hGbmdFWHlqVjhna3NRS3V2TUZwUEN0WXc2UU5sOEZZQzAzCjIxRjJRYU1FdmJTUW1uZ1Z1ODFMNXR4dEI4djIrVEZDNUZ3ODBiMmNhaFBXYkt6WlYzMVBvODZzUUtSMW9sR2oKRlpOVzBXQnl0N3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcWIrSnprVFZ0OVZQUEwyNFNjWXdObDVrMmxQWmNib3FpOW0zdHJ2VndLZnR2STBpCmJKWTBKdjhaZXlzT3hPQmhqSlE3RytaRHpjNjZYditDajhpWG1jU0hBdWZYV243TW5qMzY5bGM5NWxSb0N2T28KYmsrSlZqV0ZmYStEQ3gxUGIwZzNOUUliVGI1cThxeE5VSnRCdUVjMUo2Y2ZNR3FGb0ZIais3eEpTOUlwV3N6dwpKN1ZaYUNCSmRja3ptNUtnMGo1enlRQ1dsZTZFeW00ZkpNTzlXWnFCUHlsN2ljWnY4ajhJbVJlK3U3aitTWXdjClB2RnExeTVVTVJkaWlRRHR5RFpGYTRNUXRLdGpZTEtlY3RhY0Z0VjJ1SFBObHVvZjU3cGZyTXU0QTNxbEQvRnUKTDRhRFV0aFQyMUFGbzQvc04vV0VoNi8vMm10dUpTSm9vQW9qZlFJREFRQUJBb0lCQUFJWEM2V2h3SkcrSEo1RApUVWZqMzdzcnBEV2l2TkNuOXptRzBoMEZ0Nmd4bWxyNzBBZzdkL3hOWlFOaWN2TlZuTmp4ZnBnMFJOVFdNTWRwCnZHMVdvWTFmNWozNFRSeUFtR2ZCSm1FZjhZNjBtd29jWjNLbXQ3NVQxbC9hM25GcWx4L3g4dW1heVg5R2VsQjUKRUN0QWhZSXJNTDRNWmh5R3B1MmUzbGtoSWd5ck9xSlhHVW8rS2N2YzZOR3Vob2EvTmM3Y0I4SUtDRzdva3YzZQpkNUpramgrRXJwUytuTjdLNmZkYWZiR0N3RVJBRTA1MnJNOHZFeWNZUklZQUtCSEw1d2tRUnBkSUQrSjVxZ2pYCm5JQTZrekF3L2tqaXlkQW9NWnNxVXhpZ01LNVR4ckFZRkRiSm5zWWFndDJRLy9pbzFkL3hBQmNkdDBkSjErRGYKUFRIbFhUa0NnWUVBMWlxZUYxUHlSU1NWSHBtNmh3RzBlWS9vNktNQXp3UDI3T1o5QWJPWWRLQW9JQnNtNFdwQQpCNzNpUlRZM3RLUjk2dGRVbitwZ2Y0dktqZVZUTWRQaDJLZWphT28rVG9RYUttUHZxZVdJYVJJblkrZm01ZHFoCk1RcllaQXVQQ0FuVlprQmg5VEd6RjMwVHJNNitRMGt3OGRxSkcyOWZkOHIvZ0QzZmdYSTU3bXNDZ1lFQXl1ZkoKaWx0ZzlqMEYvenVLQzJ3clNpOE9yRkRyVTAyQzA1YkFsT1Z3YmFZbjlzWWRVeVl1d0I4STBvUXErMnhqK0xrdwpvNTMyUEhVMUNpYnh3VXI0Mkg1Ym4wc1VUL1E4bjFNRlRJNHZNaGVDMzVxcXpGalBxNmxwY052akdaUXNuRkh0CnJEV2VIWHpTYzJLY3lrVTVuZEppTXhOeVI0Si9ZQlZTMTVjMVg3Y0NnWUVBeG9VWXFBMFRmTTR0UUFGRjZ0RkUKeG80RVdtaUdYbDZSYkFVM0NQVytNeFVtUEtTT2hOS2xhY2UwejIwemM4b3FRaDY1L2NZWER3TzRqWkZ1YmJpMwpGOHBFNmdLQUlPM0pCMVE5bXlIK01VODNuaDhmWkI4bDNienMyc2Z3SElaby9uQmRuUmdscDNjMFhySUJvWU5kCjBFSS9aMlAwZmFsNDd4bnJiU1ZCMStNQ2dZQlp0R3ZuM1VwYTB0UEo2VnE0ZmhRTmNneDhwakhEM0dyUWZMK2IKbEd4R0xjVlJWbmswZjViL25UamJTVTl2WkpZMktqbVV2SXRXWTBNVnYrMzExTjE3YVRHOGxRYmY2a3k2NjR0VwpNeTR1YVRLVkJONHFCY0dhVlFXbXZiQURhUHpvQjFpYVlBSU5hMWZuWjF1R0dXREZvM09DdlVBeTJVRFRDOXBhCk1pR0l0UUtCZ0ZwQk5jTEkrSjJtZnZxRlk1d2g4YmZtamlVMWM1YzA3a1FrVjlJRnFHalp1NTZucG95M1NmaXcKT1ZGcVUxcm5ERmREYjVYT1E1ZU9xQTYxdjhMdXZJdXhsUlhLN2J6aDFqeE1qeitCMFpCUW54Y0NTSTdhQzhvOQpBa3RJOWkxUnBrSnZ5QWVOTlFwTGxGcW5GQWw4V013UVduc0cwZmV1OXdMT3ltbEJ3ZWo3Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: klioserver-dc-a-ca
  namespace: dc-a
type: kubernetes.io/tls
---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lVR0lDek5NSWIyZFhiU0lHTDcveGJhVG1vQllnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkyTURJeU56RXpNekExTjFvWApEVE0yTURJeU5URXpNekExTjFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTJzTXp4ZzJSWkZnMEZid0Q1aTNCUVpPNXV3RVIKcVlmNkcwSm0rbit3UTFUVkFhSkJXUG10VjRYcVdZcDJ1ZThRMXl3cWt5VFVuTExmUEgyWXpQOE04YUswT1dYWgpMZDdFSkNmaDVyVk9qWkFENitQMi9ERzBPZ1d1WUlPTTFpNlBXbWlsekh3ZkF0NEQ4N3JSMjNwTHhmNWljUm8wCmNXakx4VTF1WW1WKzBnTUE1Q0xSMWRsamY3MWI0WXNzU3pCUUxyUlRKU1RtSFBQNDk3MFptSTZVejl3K0J1VEsKZVpOVThYNXB0Qkc4YTRlQWRaMW5yT2QxRWJwVVRGeVo2MHdkWm9BNHdJQllETStVTkxVSzFWRVl6NEFXN200cgpRSlJFWUFWM0dEbWFkdFZlMkYzaGJReThHQ1p5WTRQbWxsS2Q5QXVEUzdUOGk4UVVoYm1TWVZXRnp3SURBUUFCCm80R2FNSUdYTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3Y2dZRFZSMFIKQkdzd2FZSVBhMnhwYjNObGNuWmxjaTFrWXkxaGdoUnJiR2x2YzJWeWRtVnlMV1JqTFdFdVpHTXRZWUlZYTJ4cApiM05sY25abGNpMWtZeTFoTG1SakxXRXVjM1pqZ2lacmJHbHZjMlZ5ZG1WeUxXUmpMV0V1WkdNdFlTNXpkbU11ClkyeDFjM1JsY2k1c2IyTmhiREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBeHFWRjJHZlI2RjMwbkhOaVkzd0sKdTV4bjAzbC9OTjdMeFY4RWF1M3A3MmVzWVl0ODlMdkUwS3pFNG9xOUovVFkzMEQwZC8yaWFSdWdrSzdxTnhydwovRWxYbXl6L3NMWVFoM3F5WS9td0JaQTlhNncrYkh4ZlRrQmtYN0NtOFA1QUpmQUYrWitlbGhLa0cxRFNxcyt3CnR6MTdTWXduRWtkT2NvYW1DdlZyZUo5cU9jdE1jVUozRzRzR2lOSjRBUVJPbTZiS0F0MHpBUnZlamJGWHhGY1YKNGNHWEo3b3BCWHdVYWpyeXZkQzhWOVpkU3lNZUJpcVFEbVNlNTQwTUt5TzZSZlJsTStodktIeG9ibGlLa1lVUApwSE9ZRCtPQ0t5eFIybUluVDZ5SUFpRTJVdkd0SjVTdUpyK0xiQS9HTHZOQkZaSENmS2JZSFJUWjVWZk90VG9PCjZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lVR0lDek5NSWIyZFhiU0lHTDcveGJhVG1vQllnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1CNFhEVEkyTURJeU56RXpNekExTjFvWApEVE0yTURJeU5URXpNekExTjFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTJzTXp4ZzJSWkZnMEZid0Q1aTNCUVpPNXV3RVIKcVlmNkcwSm0rbit3UTFUVkFhSkJXUG10VjRYcVdZcDJ1ZThRMXl3cWt5VFVuTExmUEgyWXpQOE04YUswT1dYWgpMZDdFSkNmaDVyVk9qWkFENitQMi9ERzBPZ1d1WUlPTTFpNlBXbWlsekh3ZkF0NEQ4N3JSMjNwTHhmNWljUm8wCmNXakx4VTF1WW1WKzBnTUE1Q0xSMWRsamY3MWI0WXNzU3pCUUxyUlRKU1RtSFBQNDk3MFptSTZVejl3K0J1VEsKZVpOVThYNXB0Qkc4YTRlQWRaMW5yT2QxRWJwVVRGeVo2MHdkWm9BNHdJQllETStVTkxVSzFWRVl6NEFXN200cgpRSlJFWUFWM0dEbWFkdFZlMkYzaGJReThHQ1p5WTRQbWxsS2Q5QXVEUzdUOGk4UVVoYm1TWVZXRnp3SURBUUFCCm80R2FNSUdYTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3Y2dZRFZSMFIKQkdzd2FZSVBhMnhwYjNObGNuWmxjaTFrWXkxaGdoUnJiR2x2YzJWeWRtVnlMV1JqTFdFdVpHTXRZWUlZYTJ4cApiM05sY25abGNpMWtZeTFoTG1SakxXRXVjM1pqZ2lacmJHbHZjMlZ5ZG1WeUxXUmpMV0V1WkdNdFlTNXpkbU11ClkyeDFjM1JsY2k1c2IyTmhiREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBeHFWRjJHZlI2RjMwbkhOaVkzd0sKdTV4bjAzbC9OTjdMeFY4RWF1M3A3MmVzWVl0ODlMdkUwS3pFNG9xOUovVFkzMEQwZC8yaWFSdWdrSzdxTnhydwovRWxYbXl6L3NMWVFoM3F5WS9td0JaQTlhNncrYkh4ZlRrQmtYN0NtOFA1QUpmQUYrWitlbGhLa0cxRFNxcyt3CnR6MTdTWXduRWtkT2NvYW1DdlZyZUo5cU9jdE1jVUozRzRzR2lOSjRBUVJPbTZiS0F0MHpBUnZlamJGWHhGY1YKNGNHWEo3b3BCWHdVYWpyeXZkQzhWOVpkU3lNZUJpcVFEbVNlNTQwTUt5TzZSZlJsTStodktIeG9ibGlLa1lVUApwSE9ZRCtPQ0t5eFIybUluVDZ5SUFpRTJVdkd0SjVTdUpyK0xiQS9HTHZOQkZaSENmS2JZSFJUWjVWZk90VG9PCjZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBMnNNenhnMlJaRmcwRmJ3RDVpM0JRWk81dXdFUnFZZjZHMEptK24rd1ExVFZBYUpCCldQbXRWNFhxV1lwMnVlOFExeXdxa3lUVW5MTGZQSDJZelA4TThhSzBPV1haTGQ3RUpDZmg1clZPalpBRDYrUDIKL0RHME9nV3VZSU9NMWk2UFdtaWx6SHdmQXQ0RDg3clIyM3BMeGY1aWNSbzBjV2pMeFUxdVltViswZ01BNUNMUgoxZGxqZjcxYjRZc3NTekJRTHJSVEpTVG1IUFA0OTcwWm1JNlV6OXcrQnVUS2VaTlU4WDVwdEJHOGE0ZUFkWjFuCnJPZDFFYnBVVEZ5WjYwd2Rab0E0d0lCWURNK1VOTFVLMVZFWXo0QVc3bTRyUUpSRVlBVjNHRG1hZHRWZTJGM2gKYlF5OEdDWnlZNFBtbGxLZDlBdURTN1Q4aThRVWhibVNZVldGendJREFRQUJBb0lCQUFFUW1DenJuZnlPRFZyWgp1bThoWStKczFLZWJYcm1qaHMwaEtwMG5oL1ViOFpsN2I3UCtLeURVN3dvV2lYTm9QWDIrb2twckVIbmV5UVZqCld4NE1VOFROVlBFK2xLc0xmWXJyZ3NiN3RQRXRkVWR0cWFNYW50VDFlQjdTSlJwWnlhclgvWTZjUUE1a2hFSm8KYzJNTkdsZFJZS3RLUkYwVTlJRDJXb1l5RmtieGFIN2lGVHdoN3JFdG00czljOXJ6Q3UyT2kyc0FkbG1mVUt6eQpEMndDT1lYdGZTVWJ4SldKY3JvYmZOSWt4cUcxR1pIWGxZOTkySlUvdVozcUJuSzhPOThBdmFPY2JiTys3cWJiCkpXclppam1ZdkdNTjV1R1kvRFNGbXRkQmZVRFI1bzJpOWoxaWlaaWNlU3Z5N1pMVGh6N1RWa3dzbjRkeDQ1R0kKbWkzRkZGa0NnWUVBNzRjS2tmcTJhZUYvaktrMHRrVEZHRHVDcy9majJkUHJGWDNNQVFoWU4wbUpLNFc4STgvRgpYSWtxUWZTdzhOTmFmT3ZtQlEzNVl3L1pOZTB6QVkxNnByMkFZUVhyQS9Gd2Fkczd1Y2VNUDBDZVZVanBKM203Ckwxek5GbHV5ZlNiZXk2VndlMEcxaFBydmszejVQVFU4aG1EOXlPQXBXSHg1bzZJUURyaVRUL1VDZ1lFQTZjNlcKSmdDNFlkcjkxUFc3Z0NLV3B3UjRRMENjUUdGZzdPV3dtYlkydmJRT3pRSnV0MFYzRm5UL0phTFB1TCsyMHFHcgpCa1dHZktvb3BrajZ3a29DdTN4ZTAyOFg0dEE2dThYNWY1bzk5L0dmS1Zha1hVRzlKeEEyZTFTOVJzdHRDL0pRCk5QQWlROVc4UXVBS3BNTHBHQmZOYmNWOWJ3b2o2TzBudlNRak9ETUNnWUJ5ZS8wVllOdW5KOXlyQW9UclNWdGIKQmJhbkJpaWxpS0NvR1FSVXlnUkFDS25EWDV4WkVZbW5mUGZ4cGw2Yi9La1haRGtBMlhrRlhDSFpvSkhzZ0E3TAplMi9NNytNd2MwbmpqcUd4WGlzdVlGaE5NeGdkZ2hWeHdjMVVqbWQxWWdyREUwUDc1YUE0K3lkZk96QjFqT2hzCjRoYnEyQmxxN2JQRi9rUG1oVm9Ec1FLQmdGNmJxS2d5REdvVWFqZjlRMlRqR2lEMUx4RFBtU3AzL1BkL0xnblUKOEt1c3EzeUxhbStnblVLcUR3Q1V0QWNuRkh5QXpLcWFBWVI2ZWo1bk00amcxK0F6d0U5QUdlTStyVFdFTTZSTgpycHVnMnUyb1VKUW40TGxvMXhMcXhEaGNZb0MrQ1hTU1l0c2VKckxNNDZHdCtSSTF0M3VldVZYd1BYMm9VVGM0CjQwTi9Bb0dBUTNpcFMwNUJuaTNUV2xNMXZ5ZDlZWmlCT0hZQzM5NEljM0wyR2s1Wk1tUEFGQXl2TWtDWlZkZEoKQkg0MHYzVWc1V2l6aHkxMUdjdW9NWTZsakdBc0lGMUlldzNXdUpXN1Z1VnZWeFo1bFZ3L205TlprODVWOXJIeQpTa3YxS2Z0TWREU1BTam1rQXRQV3p3a0kzbHpNN2FER1M4eS91NkNPV25DNmR5NWkvZlE9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: klioserver-dc-a-tls
  namespace: dc-a
type: kubernetes.io/tls
---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lVVmRlRlpOaTErVCtFQW9jU2phZXlpaWRBRUo4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1CNFhEVEkyTURJeU56RTBNamcwTTFvWApEVE0yTURJeU5URTBNamcwTTFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXYyZVVwRnRZZFRLbis5ZVVkTXpHQXhuTWFtWTkKaFR0b3VQNkFMZGhFa2RVOE15b0tDc0xjQWVOR1ZGWS8yQVBnQnBGSnBrWGxjVXI0dU5XVnA0cGQxNmFoOXRtbgp1U21OQXZPWmNyYjVQc2ZWNXovWkRUa20xQitEcmRPWHdwNG9EOTAzVTc5Si9qZkJ0azhKY3ZqV2RnM2Fxb3A4Cklvc0JpUU55Z1ZTSXZoQTlrc1hVUU14OW00dG40NkhaKzBqNjRVeU1ZZVFyenJSODBSV3JURWRYeTR3azhNM00KNnRhSzNaUElLMkVSNFBLK3dqKzE2dE9GWnQyQWF1Q05BRGlNeXl4Z0E1dzZOM29iRnU2ck0vaUo5YWlJY0k4cgpIS2pGeEF6R3pEUDlWenJxVFhzWGZkNEVPdDdwY2FzMUJndnpjSDFoc29YQ3ZkSUFKRFBoSW9PMHJRSURBUUFCCm80R2FNSUdYTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3Y2dZRFZSMFIKQkdzd2FZSVBhMnhwYjNObGNuWmxjaTFrWXkxaWdoUnJiR2x2YzJWeWRtVnlMV1JqTFdJdVpHTXRZb0lZYTJ4cApiM05sY25abGNpMWtZeTFpTG1SakxXSXVjM1pqZ2lacmJHbHZjMlZ5ZG1WeUxXUmpMV0l1WkdNdFlpNXpkbU11ClkyeDFjM1JsY2k1c2IyTmhiREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcnlaTVNRUTZ0eFZpenNUWFk4RkEKNnBtNEJ3K1pXb0lGQ3hyMkFZYXpDczhCcVRwUVgrOXhnMkR2c3lFNU0vczRGYzFkZXBVeGpBUzNYaWJ3MWE1cgpmT0RIZSsySjF3UjRXeUhvZ1l6TlcwWkUwaEp4Z1BCME1qVW14ejc3UjlCV2h0TU5CUy9CQ3ZhL1ljdHF2TU90Clk4eUNlY08xemVXWHVGaUZ0S3dVSXBENEZHMXFKS0JDN0p4NkxHVXRRb2RnR2NueW1DN0s4NUNPbVNnZm5CdTcKcWE1Y1FQVFNuM0RpVWVCaGFDc08zNGQvQjRmVUVTdlpYWmhNOUhGYUJtVmYzTE1vVTNQYXo1dzNUN0k1LzNtKwo3NjRjQ25GVFlhUFpBMzNEM2hyRmZlZS9mWGZ1c2x6WVlzSlZMbitmOGxVMmRobWNMczJKNDNiSklGOHFLZDFvCk53PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lVVmRlRlpOaTErVCtFQW9jU2phZXlpaWRBRUo4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1CNFhEVEkyTURJeU56RTBNamcwTTFvWApEVE0yTURJeU5URTBNamcwTTFvd0dqRVlNQllHQTFVRUF4TVBhMnhwYjNObGNuWmxjaTFrWXkxaU1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXYyZVVwRnRZZFRLbis5ZVVkTXpHQXhuTWFtWTkKaFR0b3VQNkFMZGhFa2RVOE15b0tDc0xjQWVOR1ZGWS8yQVBnQnBGSnBrWGxjVXI0dU5XVnA0cGQxNmFoOXRtbgp1U21OQXZPWmNyYjVQc2ZWNXovWkRUa20xQitEcmRPWHdwNG9EOTAzVTc5Si9qZkJ0azhKY3ZqV2RnM2Fxb3A4Cklvc0JpUU55Z1ZTSXZoQTlrc1hVUU14OW00dG40NkhaKzBqNjRVeU1ZZVFyenJSODBSV3JURWRYeTR3azhNM00KNnRhSzNaUElLMkVSNFBLK3dqKzE2dE9GWnQyQWF1Q05BRGlNeXl4Z0E1dzZOM29iRnU2ck0vaUo5YWlJY0k4cgpIS2pGeEF6R3pEUDlWenJxVFhzWGZkNEVPdDdwY2FzMUJndnpjSDFoc29YQ3ZkSUFKRFBoSW9PMHJRSURBUUFCCm80R2FNSUdYTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3Y2dZRFZSMFIKQkdzd2FZSVBhMnhwYjNObGNuWmxjaTFrWXkxaWdoUnJiR2x2YzJWeWRtVnlMV1JqTFdJdVpHTXRZb0lZYTJ4cApiM05sY25abGNpMWtZeTFpTG1SakxXSXVjM1pqZ2lacmJHbHZjMlZ5ZG1WeUxXUmpMV0l1WkdNdFlpNXpkbU11ClkyeDFjM1JsY2k1c2IyTmhiREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcnlaTVNRUTZ0eFZpenNUWFk4RkEKNnBtNEJ3K1pXb0lGQ3hyMkFZYXpDczhCcVRwUVgrOXhnMkR2c3lFNU0vczRGYzFkZXBVeGpBUzNYaWJ3MWE1cgpmT0RIZSsySjF3UjRXeUhvZ1l6TlcwWkUwaEp4Z1BCME1qVW14ejc3UjlCV2h0TU5CUy9CQ3ZhL1ljdHF2TU90Clk4eUNlY08xemVXWHVGaUZ0S3dVSXBENEZHMXFKS0JDN0p4NkxHVXRRb2RnR2NueW1DN0s4NUNPbVNnZm5CdTcKcWE1Y1FQVFNuM0RpVWVCaGFDc08zNGQvQjRmVUVTdlpYWmhNOUhGYUJtVmYzTE1vVTNQYXo1dzNUN0k1LzNtKwo3NjRjQ25GVFlhUFpBMzNEM2hyRmZlZS9mWGZ1c2x6WVlzSlZMbitmOGxVMmRobWNMczJKNDNiSklGOHFLZDFvCk53PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdjJlVXBGdFlkVEtuKzllVWRNekdBeG5NYW1ZOWhUdG91UDZBTGRoRWtkVThNeW9LCkNzTGNBZU5HVkZZLzJBUGdCcEZKcGtYbGNVcjR1TldWcDRwZDE2YWg5dG1udVNtTkF2T1pjcmI1UHNmVjV6L1oKRFRrbTFCK0RyZE9Yd3A0b0Q5MDNVNzlKL2pmQnRrOEpjdmpXZGczYXFvcDhJb3NCaVFOeWdWU0l2aEE5a3NYVQpRTXg5bTR0bjQ2SForMGo2NFV5TVllUXJ6clI4MFJXclRFZFh5NHdrOE0zTTZ0YUszWlBJSzJFUjRQSyt3aisxCjZ0T0ZadDJBYXVDTkFEaU15eXhnQTV3Nk4zb2JGdTZyTS9pSjlhaUljSThySEtqRnhBekd6RFA5VnpycVRYc1gKZmQ0RU90N3BjYXMxQmd2emNIMWhzb1hDdmRJQUpEUGhJb08wclFJREFRQUJBb0lCQUErNEs3UDlNSWJ5TWNEMApLVGx0SVRkYlQySWtUVzhtRVpRSDRCME9iWlhsMlB1QlpnWm1PYzFmT0svRkpFUjl1bEN2dy9NSGtJVm53OW8zCmt3S0owWlV4YStIVnZ2bVhybFlNdURzblNIeGR5eC9OS3VxZXcvcVloVkdwckFWaGJ5YmJ1SHlFbkVpOWxESXIKSVkvZUJ6YjJMUHc1UXJmNk5KWm53R2dHRDU0KzhOZ0lyYUFLT1lqZTI4RFkzb2xid1VVbmEydVoxS2hBWTVFcApuSS9IbEs0TjJVZFo2cHBlZk1JZ2s0NjhqbVo1V2VVaEEzb0ROVGMwRGF6eEYwWXM0UDVGNThQWDk3UnJ6c01SCndsSGxnUXFDejJpSnhzOTJKNW4yN3JOT3dTQkc3MU05UEEzYThhakdjNXRiNi9mTzY4bE4vRkdVcFhBWC9MbmsKZzIwL3QvMENnWUVBNEhydVVGcno4dHRNV1A3bG5yQ1liNFkzdXNPelpLdEp3WENJdS9MWFhqZGlFU1o3ejNnNQo3SFl4MG9HNFY5aCtyc2U5RkdDbi93a3pkS0dRZWVMR3VLaGcwNUdHYlIvTWNHWVdFd25WWnhsd3ZPN2t2bk5jCnhVOTVMbEhUUG15dExkM0RWdDBjbXI3V01uT2xaOEhTNzVBUTYrb3hJY1o1UzEveE5BZGYvMXNDZ1lFQTJrZTYKbE5mNi8zTkJPM1ZNRjJzZEhkNjhFaFNvZDBLaHhWN3cxSldoS2ppczhHVFgzY0hVNVVaMEFFRWdRd3QyTDJrbApiUi9CUGd6djM5S1JKWDVPci9zVnRxRlA1YVh5V3RxdFB2ZjNkZDl4aGtFSTNqYnc4b09FaEtvZ0dsU3lEN29RCldUQ2lPOXBzN1lJczFlTmp3d21idFVTaFdOZGhPbnpqZ05ZT0lwY0NnWUVBamJrTy9HeHYxOFBjVDlPZDVMSloKaXcrUjM3ZnVhb0E1OElhN3pPMWtTM2RyMHFnWlFzTUV6dVZRVHpiV3k1OURXOVYrNm42YmtjaWRVK1VzOGNiYQo3M3BlcHpRWlNvdm81bzJOSWpmekkwUk1pUHZLTHZObWZxdk9OaEF5N2hadXY2Wml6VlNMMnFiaFZManVsTE1xCkdWVTdXYlpoanBGZnd0YXYwY2xXTWtFQ2dZRUF4ZFIrcVFuNnBXeks4VjJFNGpDbFNmNGx5K2xIS2hlTTBIb1UKb1VjZnMwbDhpNytKMmFVa0U4dy90RDlTUXhGdlF0YjBJYXZIRXpyY2FLbkovUVkxd004NnhiUDcycklGTGd6RgpPYTI1Yk81ZlVJTSt5MDlXSHlYTmhBTkFaenpkeU4wa2xnRTYrQzRselRqTzgrZEw4bWVSNUw3WDBOSWJmOHZTCjBXQ3ZuTzhDZ1lBeGxYYVVzYktncE9yU1BlejZiZDQ2WWlHSUZueGtSU0lBZytlbllqeHY5ZWo3b1FrTnhETkMKSStBUFlMd2QyRTVIZXRJa2ZJRFBDNG1qbEdBcWtDSTkyMEFxZlhncWg1WHdHNzRBcUdqV1R6dEljSnRVQTJnZgpuYTU1VzFlc25aTlhrNXhFUXFjc0pSU2l4UnI3ckpSR1hSWW5lWTFsN3k1MkNPZWdyQytrM3c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: klioserver-dc-b-tls
  namespace: dc-a
type: kubernetes.io/tls
