version: "2"
linters:
  default: all
  disable:
    - mnd
    - depguard
    - exhaustruct
    - funlen
    - paralleltest
    - testpackage
    - wsl
    - wsl_v5
    - err113
    - wrapcheck
    - varnamelen
    - nilnil
    - goconst
    - godox
    - gomodguard
    - noinlineerr
  settings:
    lll:
      line-length: 120
    nlreturn:
      block-size: 3
    varnamelen:
      ignore-names:
        - g
    tagliatelle:
      case:
        overrides:
          - pkg: pkg/config
            rules:
              json: snake
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: should not use dot imports
        source: ginkgo|gomega
      - linters:
          - lll
        source: //\s*\+
    paths:
      - zz_generated.*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      no-prefix-comments: false
      no-inline-comments: false
      sections:
        - standard
        - default
        - prefix(github.com/cloudnative-pg/klio)
        - blank
        - dot
  exclusions:
    generated: lax
    paths:
      - zz_generated.*
      - third_party$
      - builtin$
      - examples$
