# Refresh the "licenses" directory and create a PR if there are any changes

name: Refresh licenses directory
on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * 1"

permissions: read-all

jobs:
  licenses:
    name: Refresh licenses
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup dagger
        uses: ./.github/actions/setup-dagger

      - name: Generate licenses
        run: |
          task core:licenses operator:licenses

      - name: Create Pull Request if licenses have been updated
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          title: "chore: refresh licenses directory"
          body: "Refresh the licenses directory"
          branch: "license-updater"
          author: "license-updater <license-updater@users.noreply.github.com>"
          add-paths: |
            core/licenses/**
            operator/licenses/**
          commit-message: "chore: refresh licenses directory"
          signoff: true
