name: Renovate
on:
  schedule:
    - cron: '0 0-7,17-23 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'info'
        type: choice
        options:
          - warning
          - info
          - debug

permissions: read-all

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
