name: Renovate
on:
  schedule:
    - cron: '0 0/6 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'info'
        type: choice
        options:
          - warning
          - info
          - debug

permissions: read-all

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@a889a8abcb11ef7feaafaf5e483ea01d4bf7774e # v43.0.5
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
