name: Renovate
on:
  schedule:
    - cron: '0 0/6 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'info'
        type: choice
        options:
          - warning
          - info
          - debug

permissions: read-all

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@c91a61c730fa166439cd3e2c300c041590002b1d # v44.0.3
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
